import { CONFIG } from "./core/config.js?v=5.0.0";
import { Diagnostics } from "./core/diagnostics.js?v=5.0.0";
import { ContractService } from "./domain/contract-service.js?v=5.0.0";
import { createGameState, normalizeState } from "./domain/game-state.js?v=5.0.0";
import { PortfolioService } from "./domain/portfolio-service.js?v=5.0.0";
import { ResourceService } from "./domain/resource-service.js?v=5.0.0";
import { InventoryService } from "./domain/inventory-service.js?v=5.0.0";
import { CollectionService } from "./domain/collection-service.js?v=5.0.0";
import { ColonyService } from "./domain/colony-service.js?v=5.0.0";
import { TradeService } from "./domain/trade-service.js?v=5.0.0";
import { WorldService } from "./domain/world-service.js?v=5.0.0";
import { SiteService } from "./domain/site-service.js?v=5.0.0";
import { TechnologyService } from "./domain/technology-service.js?v=5.0.0";
import { SurveyService } from "./domain/survey-service.js?v=5.0.0";
import { SimulationEngine } from "./domain/simulation-engine.js?v=5.0.0";
import { SaveRepository } from "./persistence/save-repository.js?v=5.0.0";
import { ResourceIcons } from "./ui/resource-icons.js?v=5.0.0";
import { WorldView } from "./ui/world-view.js?v=5.0.1";
import { UIController } from "./ui/ui-controller.js?v=5.0.0";
import { TradeUI } from "./ui/trade-ui.js?v=5.0.0";

class MineITApp {
  constructor(){
    this.diagnostics=new Diagnostics();window.mineITBoot=this;addEventListener("error",e=>this.diagnostics.error("window.error",e.error||e.message));addEventListener("unhandledrejection",e=>this.diagnostics.error("unhandledrejection",e.reason));
    this.contracts=new ContractService();this.repo=new SaveRepository(this.diagnostics);this.resources=new ResourceService();this.inventory=new InventoryService(this.resources);this.technology=new TechnologyService();this.collection=new CollectionService(this.resources,this.inventory,this.technology);this.colony=new ColonyService(this.inventory,this.technology);this.trade=new TradeService(this.resources,this.inventory);this.world=new WorldService(this.resources,this.contracts);this.sites=new SiteService(this.contracts,this.technology,this.inventory);this.survey=new SurveyService(this.world,this.contracts);this.engine=new SimulationEngine(this.resources,this.technology,this.collection,this.trade,this.inventory,this.colony);this.portfolio=new PortfolioService();this.icons=new ResourceIcons();
    const saved=this.repo.load();this.state=normalizeState(saved||createGameState(this.contracts.first()));this.portfolio.ensure(this.state);this.repo.setBeforeSave(()=>this.portfolio.captureActive(this.state,true));this.prepareActive();
    this.ui=new UIController({state:this.state,repo:this.repo,resources:this.resources,inventory:this.inventory,collection:this.collection,colony:this.colony,portfolio:this.portfolio,sites:this.sites,technology:this.technology,survey:this.survey,contracts:this.contracts,world:this.world,icons:this.icons,diagnostics:this.diagnostics,onHardReset:()=>this.hardReset(),onNewContract:c=>this.addColony(c),onSwitchColony:id=>this.switchColony(id),onRemoveColony:mode=>this.removeColony(mode),onMakeLiability:()=>this.makeLiability(),onRelocateColony:()=>this.relocateColony(),onRecalculate:()=>{this.engine.recalculate(this.state);this.view?.safeDraw()}});
    this.tradeUI=new TradeUI({state:this.state,trade:this.trade,repo:this.repo,ui:this.ui});this.view=new WorldView({state:this.state,world:this.world,survey:this.survey,resources:this.resources,technology:this.technology,icons:this.icons,diagnostics:this.diagnostics,onTap:(x,y)=>this.tap(x,y),onMulti:cells=>this.multi(cells)});
    this.accumulator=0;this.lastFrame=performance.now();this.renderAll();requestAnimationFrame(now=>this.loop(now));document.addEventListener("visibilitychange",()=>{if(document.hidden)this.repo.save(this.state)});
  }
  prepareActive(){this.technology.recompute(this.state);this.engine.recalculate(this.state);this.survey.fill(this.state);}
  renderAll(){this.ui?.render();this.tradeUI?.render();this.ui?.syncSpeed();this.view?.safeDraw();}
  tap(x,y){if(x===0&&y===0){this.ui.company();return}const tile=this.world.get(this.state,x,y);if(!tile.revealed){const r=this.survey.enqueue(this.state,x,y);if(r.ok){this.ui.toast(r.active?`Surveying ${x},${y}...`:`Queued ${x},${y}.`);this.view.safeDraw()}else this.ui.tile(tile);return}this.ui.tile(tile);}
  multi(cells){const n=this.survey.enqueueMany(this.state,cells);this.ui.toast(n?`${n} cell${n===1?"":"s"} added to survey queue.`:this.state.contract.ended?"Mining contract ended; surveying is disabled.":"No new cells selected.");this.view.safeDraw();}
  addColony(contract){if(!this.technology.meetsRequirements(this.state,contract.requiredTech)){this.ui.toast("Technology requirements not met.");return false;}if(this.state.trade.active)this.trade.depart(this.state);this.portfolio.addColony(this.state,contract);this.prepareActive();this.ui.modal.classList.add("hidden");this.ui.tilePanel.classList.add("hidden");this.renderAll();this.repo.save(this.state);this.ui.toast(`${this.state.contract.colonyName} established.`);return true;}
  switchColony(id){if(this.state.trade.active)this.trade.depart(this.state);if(!this.portfolio.switchTo(this.state,id)){this.ui.toast("Colony could not be loaded.");return false;}if(this.state.trade.active){this.state.trade.active=false;this.state.trade.arrivedAt=null;if(this.contracts.isOperating(this.state))this.state.speed=1;}this.prepareActive();this.ui.modal.classList.add("hidden");this.ui.tilePanel.classList.add("hidden");this.renderAll();this.repo.save(this.state);if(this.state.status==="deadline-missed")this.ui.deadline("extension");else if(this.state.status==="failed")this.ui.deadline("failed");return true;}
  removeColony(){const result=this.portfolio.removeActive(this.state);if(!result.ok){this.ui.toast(result.reason);return false;}this.prepareActive();this.ui.modal.classList.add("hidden");this.ui.tilePanel.classList.add("hidden");this.renderAll();this.repo.save(this.state);this.ui.toast("Colony returned to the corporation.");this.ui.coloniesPanel();return true;}
  makeLiability(){this.contracts.endAsLiability(this.state);this.prepareActive();this.repo.save(this.state);this.renderAll();this.ui.toast("Contract ended. Colony remains your responsibility.");}
  relocateColony(){const cost=this.colony.relocationCost(this.state);if(this.state.portfolio.colonies.length<=1){this.ui.toast("Open another colony before disposing of your final colony.");return false;}if(this.state.company.cash<cost){this.ui.toast(`Relocation requires £${Math.round(cost).toLocaleString()}.`);return false;}this.state.company.cash-=cost;const result=this.portfolio.removeActive(this.state);if(!result.ok){this.state.company.cash+=cost;this.ui.toast(result.reason);return false;}this.prepareActive();this.renderAll();this.repo.save(this.state);this.ui.toast("Population relocated and colony closed.");this.ui.coloniesPanel();return true;}
  hardReset(){if(!confirm("Erase all MineIT saves on this browser?"))return;this.repo.clearAll();const fresh=createGameState(this.contracts.first());Object.keys(this.state).forEach(k=>delete this.state[k]);Object.assign(this.state,fresh);this.portfolio.ensure(this.state);this.prepareActive();this.ui.modal.classList.add("hidden");this.ui.tilePanel.classList.add("hidden");this.renderAll();this.repo.save(this.state);this.ui.toast("Corporation reset to Year 1 Day 1.");}
  advanceColony(local,active=false){if(!this.contracts.isOperating(local))return{discoveries:[],shipArrived:false,deadline:null};this.engine.tick(local);const discoveries=local.contract.ended?[]:this.survey.tick(local);this.engine.recalculate(local);let shipArrived=false;if(active&&this.trade.shouldArrive(local)){shipArrived=this.trade.arrive(local);this.engine.recalculate(local);}return{discoveries,shipArrived,deadline:this.contracts.deadlineState(local)};}
  resolveBackgroundDeadline(local,kind){if(kind==="complete"){this.contracts.awardCompletion(local);local.speed=1;}else if(kind==="renewal-ended"){this.contracts.enterHoldover(local);local.speed=1;}else if(kind==="extension"){local.status="deadline-missed";local.speed=0;}else if(kind==="failed"){local.contract.ended=true;local.status="liability";local.speed=1;}}
  tick(){
    this.diagnostics.ticks++;this.diagnostics.lastTick=Date.now();let result;
    try{result=this.advanceColony(this.state,true);this.portfolio.captureActive(this.state,true);this.portfolio.simulateInactive(this.state,temp=>{const background=this.advanceColony(temp,false);if(background.deadline)this.resolveBackgroundDeadline(temp,background.deadline);});}catch(error){this.diagnostics.error("simulation core crashed",error);this.state.speed=0;this.ui.syncSpeed();return;}
    if(result.deadline){this.ui.deadline(result.deadline);}else if(result.shipArrived){try{this.tradeUI.open()}catch(e){this.diagnostics.error("trade ship UI failed",e)}}else if(result.discoveries.length){try{const rare=result.discoveries.filter(t=>t.quality>=CONFIG.RARE_QUALITY).sort((a,b)=>b.quality-a.quality);if(rare.length)this.ui.rare(rare[0]);else if(result.discoveries.length===1)this.ui.toast(`${result.discoveries[0].name} discovered • Q${Math.round(result.discoveries[0].quality)}`);else this.ui.toast(`${result.discoveries.length} surveys completed.`)}catch(e){this.diagnostics.error("discovery UI failed",e)}}
    try{this.ui.render();this.tradeUI.render()}catch(e){this.diagnostics.error("HUD render failed",e)}this.view.safeDraw();const absoluteDay=(this.state.year-1)*CONFIG.DAYS_PER_YEAR+this.state.day;if(absoluteDay%30===0)this.repo.save(this.state);
  }
  loop(now){this.diagnostics.heartbeat++;try{const delta=Math.min(120,now-this.lastFrame);this.lastFrame=now;if(this.state.speed>0&&this.contracts.isOperating(this.state)){this.accumulator+=delta*this.state.speed;while(this.accumulator>=CONFIG.DAY_MS){this.accumulator-=CONFIG.DAY_MS;this.tick()}}this.ui.render();this.tradeUI.render()}catch(e){this.diagnostics.error("animation loop failed",e)}requestAnimationFrame(next=>this.loop(next));}
}
addEventListener("DOMContentLoaded",()=>{try{const app=new MineITApp();window.mineIT=app;window.mineITBoot=app}catch(error){console.error(error);const app=window.mineITBoot;app?.diagnostics?.error("startup failed",error);const badge=document.querySelector("#errorBadge");if(badge){badge.textContent="STARTUP ERROR • TAP FOR DETAILS";badge.classList.remove("hidden");if(app?.ui)badge.onclick=()=>app.ui.diagnosticsPanel();}}});
