import { CONFIG } from "./core/config.js?v=5.5.0";
import { Diagnostics } from "./core/diagnostics.js?v=5.5.0";
import { ContractService } from "./domain/contract-service.js?v=5.5.0";
import { createGameState, normalizeState } from "./domain/game-state.js?v=5.5.0";
import { PortfolioService } from "./domain/portfolio-service.js?v=5.5.0";
import { ResourceService } from "./domain/resource-service.js?v=5.5.0";
import { InventoryService } from "./domain/inventory-service.js?v=5.5.0";
import { CollectionService } from "./domain/collection-service.js?v=5.5.0";
import { ColonyService } from "./domain/colony-service.js?v=5.5.0";
import { TradeService } from "./domain/trade-service.js?v=5.5.0";
import { WorldService } from "./domain/world-service.js?v=5.5.0";
import { SiteService } from "./domain/site-service.js?v=5.5.0";
import { TechnologyService } from "./domain/technology-service.js?v=5.5.0";
import { SurveyService } from "./domain/survey-service.js?v=5.5.0";
import { SimulationEngine } from "./domain/simulation-engine.js?v=5.5.0";
import { GameLogService } from "./domain/game-log-service.js?v=5.5.0";
import { TransportService } from "./domain/transport-service.js?v=5.5.0";
import { SaveRepository } from "./persistence/save-repository.js?v=5.5.0";
import { ResourceIcons } from "./ui/resource-icons.js?v=5.5.0";
import { WorldView } from "./ui/world-view.js?v=5.5.0";
import { UIController } from "./ui/ui-controller.js?v=5.5.0";
import { TradeUI } from "./ui/v55-trade-ui.js?v=5.5.0";

class MineITApp {
  constructor(){
    this.diagnostics=new Diagnostics();window.mineITBoot=this;addEventListener("error",e=>this.diagnostics.error("window.error",e.error||e.message));addEventListener("unhandledrejection",e=>this.diagnostics.error("unhandledrejection",e.reason));
    this.contracts=new ContractService();this.repo=new SaveRepository(this.diagnostics);this.resources=new ResourceService();this.inventory=new InventoryService(this.resources);this.technology=new TechnologyService();this.collection=new CollectionService(this.resources,this.inventory,this.technology);this.colony=new ColonyService(this.inventory,this.technology);this.trade=new TradeService(this.resources,this.inventory);this.world=new WorldService(this.resources,this.contracts);this.sites=new SiteService(this.contracts,this.technology,this.inventory,this.colony,this.resources);this.survey=new SurveyService(this.world,this.contracts);this.engine=new SimulationEngine(this.resources,this.technology,this.collection,this.trade,this.inventory,this.colony);this.portfolio=new PortfolioService();this.gameLog=new GameLogService();this.transport=new TransportService();this.icons=new ResourceIcons();
    const saved=this.repo.load();this.state=normalizeState(saved||createGameState(this.contracts.first()));this.portfolio.ensure(this.state);this.gameLog.ensure(this.state);if(!this.state.gameLog.events.length)this.gameLog.event(this.state,saved?"save-migrated":"corporation-founded",saved?"Save migrated to the synchronized v5.5 corporation simulation.":"Mining corporation founded and Contract 01 established.",{build:"5.5.0",saveVersion:this.state.version});this.repo.setBeforeSave(()=>this.portfolio.captureActive(this.state,true));this.prepareActive();
    this.ui=new UIController({state:this.state,repo:this.repo,resources:this.resources,inventory:this.inventory,collection:this.collection,colony:this.colony,portfolio:this.portfolio,sites:this.sites,technology:this.technology,survey:this.survey,contracts:this.contracts,world:this.world,icons:this.icons,diagnostics:this.diagnostics,transport:this.transport,gameLog:this.gameLog,onHardReset:()=>this.hardReset(),onNewContract:c=>this.addColony(c),onSwitchColony:id=>this.switchColony(id),onRemoveColony:mode=>this.removeColony(mode),onMakeLiability:()=>this.makeLiability(),onRelocateColony:()=>this.relocateColony(),onRecalculate:()=>{this.engine.recalculate(this.state);this.view?.safeDraw()},onCapturePortfolio:()=>this.portfolio.captureActive(this.state,true)});
    this.tradeUI=new TradeUI({state:this.state,trade:this.trade,repo:this.repo,ui:this.ui,gameLog:this.gameLog,onDepart:()=>this.onShipDepart()});this.view=new WorldView({state:this.state,world:this.world,survey:this.survey,resources:this.resources,technology:this.technology,icons:this.icons,diagnostics:this.diagnostics,onTap:(x,y)=>this.tap(x,y),onMulti:cells=>this.multi(cells)});
    this.accumulator=0;this.lastFrame=performance.now();this.pendingActiveDeadline=null;this.renderAll();requestAnimationFrame(now=>this.loop(now));document.addEventListener("visibilitychange",()=>{if(document.hidden)this.repo.save(this.state)});queueMicrotask(()=>{if(this.state.company.gameOver)this.ui.gameOver?.();else if(this.state.company.pendingEvents?.length)this.processPendingShipEvent();else this.checkInitialDeadline();});
  }
  absoluteDay(){return(this.state.year-1)*CONFIG.DAYS_PER_YEAR+this.state.day;}
  advanceGlobalDate(){this.state.day++;if(this.state.day>CONFIG.DAYS_PER_YEAR){this.state.day=1;this.state.year++;}}
  prepareActive(){this.technology.recompute(this.state);this.engine.recalculate(this.state);this.survey.fill(this.state);}
  renderAll(){this.ui?.render();this.tradeUI?.render();this.ui?.syncSpeed();this.view?.safeDraw();}
  tap(x,y){if(x===0&&y===0){this.ui.company();return}const tile=this.world.get(this.state,x,y);if(!tile.revealed){const r=this.survey.enqueue(this.state,x,y);if(r.ok){this.ui.toast(r.active?`Surveying ${x},${y}...`:`Queued ${x},${y}.`);this.view.safeDraw()}else this.ui.tile(tile);return}this.ui.tile(tile);}
  multi(cells){const n=this.survey.enqueueMany(this.state,cells);this.ui.toast(n?`${n} cell${n===1?"":"s"} added to survey queue.`:this.state.contract.ended?"Mining contract ended; surveying is disabled.":"No new cells selected.");this.view.safeDraw();}
  addColony(contract){if(this.state.company.pendingEvents?.length){this.ui.toast("Resolve the pending corporate ship first.");return false;}if(this.state.company.gameOver){this.ui.toast("This corporation has ended. Start a new corporation to continue.");return false;}if(!this.technology.meetsRequirements(this.state,contract.requiredTech)){this.ui.toast("Technology requirements not met.");return false;}const entry=this.portfolio.addColony(this.state,contract);this.prepareActive();this.gameLog.event(this.state,"colony-established",`${this.state.contract.colonyName} established: ${this.state.contract.name}.`,{colonyId:entry.id,environment:this.state.contract.environment,tier:this.state.contract.colonyTier,advance:this.state.contract.advance});this.ui.modal.classList.add("hidden");this.ui.tilePanel.classList.add("hidden");this.renderAll();this.repo.save(this.state);this.ui.toast(`${this.state.contract.colonyName} established. Secure Food, Fuel, workers and Industry before expanding.`);return true;}
  switchColony(id,force=false){if(this.state.company.pendingEvents?.length&&!force&&id!==this.state.company.pendingEvents[0]?.colonyId){this.ui.toast("Resolve the pending corporate ship before switching colonies.");return false;}if(!this.portfolio.switchTo(this.state,id)){this.ui.toast("Colony could not be loaded.");return false;}this.prepareActive();this.ui.modal.classList.add("hidden");this.ui.tilePanel.classList.add("hidden");this.renderAll();this.repo.save(this.state);if(!force){if(this.state.status==="dead")this.ui.colonyPanel();else if(this.state.status==="deadline-missed")this.ui.deadline("extension");else if(this.state.status==="failed")this.ui.deadline("failed");}return true;}
  removeColony(mode="corporate-return"){const oldName=this.state.contract.colonyName,oldId=this.state.colonyId,result=this.portfolio.removeActive(this.state);if(!result.ok){this.ui.toast(result.reason);return false;}this.gameLog.event(this.state,mode==="abandon-dead"?"dead-colony-abandoned":"colony-returned",mode==="abandon-dead"?`${oldName} dead-colony record abandoned.`:`${oldName} returned to the corporation.`,{removedColonyId:oldId},oldId,oldName);this.prepareActive();this.ui.modal.classList.add("hidden");this.ui.tilePanel.classList.add("hidden");this.renderAll();this.repo.save(this.state);this.ui.toast(mode==="abandon-dead"?"Dead colony record abandoned.":"Colony returned to the corporation.");this.ui.coloniesPanel();return true;}
  makeLiability(){this.contracts.endAsLiability(this.state);this.gameLog.event(this.state,"liability-colony",`${this.state.contract.colonyName} mining rights ended; colony became a support liability.`,{});this.prepareActive();this.repo.save(this.state);this.renderAll();this.ui.toast("Contract ended. Colony remains your responsibility and can still be lost if life support fails.");}
  relocateColony(){const cost=this.colony.relocationCost(this.state);if(this.state.portfolio.colonies.length<=1){this.ui.toast("Open another colony before disposing of your final colony.");return false;}if(this.state.company.cash<cost){this.ui.toast(`Relocation requires £${Math.round(cost).toLocaleString()}.`);return false;}const oldName=this.state.contract.colonyName,oldId=this.state.colonyId,pop=this.state.pop;this.state.company.cash-=cost;const result=this.portfolio.removeActive(this.state);if(!result.ok){this.state.company.cash+=cost;this.ui.toast(result.reason);return false;}this.gameLog.event(this.state,"colony-relocated",`${formatNumberSafe(pop)} colonists relocated from ${oldName}; colony closed.`,{removedColonyId:oldId,population:pop,cost},oldId,oldName);this.prepareActive();this.renderAll();this.repo.save(this.state);this.ui.toast("Population relocated and colony closed.");this.ui.coloniesPanel();return true;}
  hardReset(){if(!confirm("Erase all MineIT saves on this browser?"))return;this.repo.clearAll();const fresh=createGameState(this.contracts.first());Object.keys(this.state).forEach(k=>delete this.state[k]);Object.assign(this.state,fresh);this.portfolio.ensure(this.state);this.gameLog.ensure(this.state);this.gameLog.event(this.state,"corporation-founded","Mining corporation reset and Contract 01 established.",{build:"5.5.0"});this.prepareActive();this.ui.modal.classList.add("hidden");this.ui.tilePanel.classList.add("hidden");this.renderAll();this.repo.save(this.state);this.ui.toast("Corporation reset to Year 1 Day 1.");}
  logSimulationEvents(local,result,entryName){for(const {tile,event} of result.renewableEvents||[])this.gameLog.event(local,`renewable-${event.kind}`,event.kind==="wiped"?`${tile.name} at ${tile.x},${tile.y} was wiped out by over-farming.`:`${tile.name} at ${tile.x},${tile.y} changed from ${event.from} to ${event.to}.`,{x:tile.x,y:tile.y,resource:tile.name,from:event.from,to:event.to,harvestIntensity:tile.harvestIntensity},local.colonyId,entryName);for(const tile of result.depletedSites||[])this.gameLog.event(local,"deposit-depleted",`${tile.name} deposit at ${tile.x},${tile.y} was depleted.`,{x:tile.x,y:tile.y,resource:tile.name,quality:tile.quality,size:tile.depositScale},local.colonyId,entryName);if((result.deaths||0)>0)this.gameLog.event(local,"population-deaths",`${formatNumberSafe(result.deaths)} colonists died during a survival shortage.`,{deaths:result.deaths,population:local.pop,survivalSupply:local.metrics.survivalSupply},local.colonyId,entryName);if(result.colonyDied)this.gameLog.event(local,"colony-lost",`${entryName||local.contract.colonyName} was lost after population reached zero.`,{population:0,industryLevel:local.colony.industryLevel},local.colonyId,entryName);}
  advanceColony(local,entryName){if(!this.contracts.isOperating(local))return{discoveries:[],died:false};const tickResult=this.engine.tick(local);this.engine.recalculate(local);this.logSimulationEvents(local,tickResult,entryName);if(tickResult.colonyDied)return{discoveries:[],died:true,deaths:tickResult.deaths};const discoveries=local.contract.ended?[]:this.survey.tick(local);for(const tile of discoveries)this.gameLog.event(local,"survey-discovery",`${tile.name} discovered at ${tile.x},${tile.y} • Q${Math.round(tile.quality)} • ${tile.depositScale||tile.abundanceLabel}.`,{x:tile.x,y:tile.y,resource:tile.name,type:tile.type,quality:tile.quality,size:tile.depositScale||tile.abundanceLabel,miningLevel:tile.requiredMiningLevel},local.colonyId,entryName);this.engine.recalculate(local);return{discoveries,died:false,deaths:tickResult.deaths};}
  resolveBackgroundDeadline(local,kind,entryName){if(kind==="complete"){const r=this.contracts.awardCompletion(local);this.gameLog.event(local,"contract-complete",`${entryName} completed its initial contract with ${r.score?.rating||"Bronze"} performance.`,{rating:r.score?.rating,profit:r.score?.profit},local.colonyId,entryName);}else if(kind==="renewal-ended"){this.contracts.enterHoldover(local);this.gameLog.event(local,"renewal-ended",`${entryName} entered holdover after its renewal term ended.`,{},local.colonyId,entryName);}else if(kind==="extension"){local.status="deadline-missed";this.gameLog.event(local,"contract-deadline-missed",`${entryName} missed its contract objectives and requires an extension decision.`,{},local.colonyId,entryName);}else if(kind==="failed"){local.contract.ended=true;local.status="liability";this.gameLog.event(local,"contract-failed",`${entryName} exhausted all deadline extensions and became a liability colony.`,{},local.colonyId,entryName);}}
  processScheduledFor(local,entryName,isActive=false){const arrivals=this.transport.processArrivals(local);for(const order of arrivals)this.gameLog.event(local,"transport-arrived",`Dedicated transport delivered ${formatNumberSafe(order.amount)} colonists to ${entryName}.`,{quantity:order.amount,cost:order.cost,population:local.pop,orderId:order.id},local.colonyId,entryName);this.engine.recalculate(local);const deadline=this.contracts.deadlineState(local);if(deadline){if(isActive)this.pendingActiveDeadline=deadline;else this.resolveBackgroundDeadline(local,deadline,entryName);}if(this.trade.shouldArrive(local)){this.trade.arrive(local);if(!this.state.company.pendingEvents.some(e=>e.type==="ship"&&e.colonyId===local.colonyId))this.state.company.pendingEvents.push({type:"ship",colonyId:local.colonyId,colonyName:entryName});this.gameLog.event(local,"ship-arrived",`Corporate trade ship arrived at ${entryName}.`,{visit:local.trade.visits,importCapacity:this.trade.cargoCapacity(local),exportCapacity:this.trade.exportCapacity(local)},local.colonyId,entryName);}}
  collectShipEventsAndScheduled(){this.processScheduledFor(this.state,this.state.contract.colonyName,true);this.portfolio.captureActive(this.state,true);this.portfolio.simulateInactive(this.state,(temp,entry)=>this.processScheduledFor(temp,temp.contract?.colonyName||entry.name,false));this.portfolio.captureActive(this.state,true);}
  beginShipQueueIfNeeded(previousSpeed){if(!this.state.company.pendingEvents.length)return false;const startingQueue=!this.state.company.eventReturnColonyId;if(startingQueue){this.state.company.eventReturnColonyId=this.state.portfolio.activeColonyId;this.state.company.eventResumeSpeed=previousSpeed>0?previousSpeed:1;}this.state.speed=0;this.repo.save(this.state);this.processPendingShipEvent();return true;}
  processPendingShipEvent(){const event=this.state.company.pendingEvents?.[0];if(!event)return false;this.state.speed=0;if(this.state.portfolio.activeColonyId!==event.colonyId)this.switchColony(event.colonyId,true);if(!this.state.trade.active){this.state.company.pendingEvents.shift();return this.processPendingShipEvent();}this.renderAll();this.tradeUI.open();return true;}
  onShipDepart(){const current=this.state.company.pendingEvents?.[0];if(current?.type==="ship"&&current.colonyId===this.state.colonyId)this.state.company.pendingEvents.shift();this.portfolio.captureActive(this.state,true);if(this.state.company.pendingEvents.length){this.repo.save(this.state);this.processPendingShipEvent();return;}const returnId=this.state.company.eventReturnColonyId,resume=Math.max(1,Number(this.state.company.eventResumeSpeed)||1);this.state.company.eventReturnColonyId=null;this.state.company.eventResumeSpeed=1;if(returnId&&this.state.portfolio.colonies.some(e=>e.id===returnId)&&returnId!==this.state.portfolio.activeColonyId)this.switchColony(returnId,true);this.state.speed=this.state.company.gameOver?0:resume;this.renderAll();this.repo.save(this.state);if(this.pendingActiveDeadline){const kind=this.pendingActiveDeadline;this.pendingActiveDeadline=null;this.state.speed=0;this.ui.deadline(kind);}}
  checkInitialDeadline(){const kind=this.contracts.deadlineState(this.state);if(kind){this.state.speed=0;this.ui.deadline(kind);}}
  tick(){this.diagnostics.ticks++;this.diagnostics.lastTick=Date.now();const previousSpeed=this.state.speed;let activeResult,backgroundDeaths=[];try{activeResult=this.advanceColony(this.state,this.state.contract.colonyName);this.portfolio.captureActive(this.state,true);this.portfolio.simulateInactive(this.state,(temp,entry)=>{const r=this.advanceColony(temp,temp.contract?.colonyName||entry.name);if(r.died)backgroundDeaths.push(temp.contract?.colonyName||entry.name||"Colony");});this.portfolio.captureActive(this.state,true);this.advanceGlobalDate();this.collectShipEventsAndScheduled();this.state.company.gameOver=!this.state.portfolio.colonies.some(entry=>entry?.data?.status!=="dead");}catch(error){this.diagnostics.error("simulation core crashed",error);this.state.speed=0;this.ui.syncSpeed();return;}if(this.absoluteDay()%CONFIG.LOG_TELEMETRY_INTERVAL_DAYS===0){this.portfolio.captureActive(this.state,true);this.gameLog.telemetry(this.state,this.state.portfolio);}if(this.state.company.gameOver){this.state.speed=0;this.repo.save(this.state);this.ui.gameOver?.();}else if(this.beginShipQueueIfNeeded(previousSpeed))return;else if(this.pendingActiveDeadline){const kind=this.pendingActiveDeadline;this.pendingActiveDeadline=null;this.state.speed=0;this.repo.save(this.state);this.ui.deadline(kind);return;}else if(activeResult.died){this.repo.save(this.state);this.ui.colonyLost?.();}else if(activeResult.discoveries.length){try{const rare=activeResult.discoveries.filter(t=>t.quality>=CONFIG.RARE_QUALITY).sort((a,b)=>b.quality-a.quality);if(rare.length)this.ui.rare(rare[0]);else if(activeResult.discoveries.length===1)this.ui.toast(`${activeResult.discoveries[0].name} discovered • Q${Math.round(activeResult.discoveries[0].quality)}`);else this.ui.toast(`${activeResult.discoveries.length} surveys completed.`)}catch(e){this.diagnostics.error("discovery UI failed",e)}}else if(backgroundDeaths.length)this.ui.toast(`${backgroundDeaths.join(", ")} lost. Review your colony portfolio.`);try{this.ui.render();this.tradeUI.render()}catch(e){this.diagnostics.error("HUD render failed",e)}this.view.safeDraw();if(this.absoluteDay()%30===0)this.repo.save(this.state);}
  loop(now){this.diagnostics.heartbeat++;try{const delta=Math.min(120,now-this.lastFrame);this.lastFrame=now;if(this.state.speed>0&&!this.state.company.gameOver&&!this.state.company.pendingEvents?.length){this.accumulator+=delta*this.state.speed;while(this.accumulator>=CONFIG.DAY_MS&&this.state.speed>0&&!this.state.company.pendingEvents?.length){this.accumulator-=CONFIG.DAY_MS;this.tick()}}this.ui.render();this.tradeUI.render()}catch(e){this.diagnostics.error("animation loop failed",e)}requestAnimationFrame(next=>this.loop(next));}
}
function formatNumberSafe(value){const n=Number(value)||0;return Math.abs(n)>=1000?Math.round(n).toLocaleString():n>=10?Math.round(n).toString():n.toFixed(1).replace(/\.0$/,"");}
addEventListener("DOMContentLoaded",()=>{try{const app=new MineITApp();window.mineIT=app;window.mineITBoot=app}catch(error){console.error(error);const app=window.mineITBoot;app?.diagnostics?.error("startup failed",error);const badge=document.querySelector("#errorBadge");if(badge){badge.textContent="STARTUP ERROR • TAP FOR DETAILS";badge.classList.remove("hidden");if(app?.ui)badge.onclick=()=>app.ui.diagnosticsPanel();}}});
