import { CONFIG } from "./core/config.js?v=5.5.0";
import { Diagnostics } from "./core/diagnostics.js?v=5.5.0";
import { ContractService } from "./domain/contract-service.js?v=5.5.0";
import { createGameState, normalizeState } from "./domain/game-state.js?v=5.5.0";
import { PortfolioService } from "./domain/portfolio-service.js?v=5.5.0";
import { ResourceService } from "./domain/resource-service.js?v=5.5.0";
import { InventoryService } from "./domain/inventory-service.js?v=5.5.0";
import { CollectionService } from "./domain/collection-service.js?v=5.5.0";
import { ColonyService } from "./domain/colony-service.js?v=5.5.0";
import { TradeService } from "./domain/trade-service.js?v=5.5.0";
import { LandService } from "./domain/land-service.js?v=5.5.0";
import { DevelopmentService } from "./domain/development-service.js?v=5.5.0";
import { WorldService } from "./domain/world-service.js?v=5.5.0";
import { SiteService } from "./domain/site-service.js?v=5.5.0";
import { TechnologyService } from "./domain/technology-service.js?v=5.5.0";
import { SurveyService } from "./domain/survey-service.js?v=5.5.0";
import { SimulationEngine } from "./domain/simulation-engine.js?v=5.5.0";
import { SaveRepository } from "./persistence/save-repository.js?v=5.5.0";
import { ResourceIcons } from "./ui/resource-icons.js?v=5.5.0";
import { WorldView } from "./ui/world-view.js?v=5.5.0";
import { UIController } from "./ui/ui-controller.js?v=5.5.0";
import { TradeUI } from "./ui/industry-trade-ui.js?v=5.5.0";

class MineITApp {
  constructor(){
    this.diagnostics=new Diagnostics();window.mineITBoot=this;addEventListener("error",e=>this.diagnostics.error("window.error",e.error||e.message));addEventListener("unhandledrejection",e=>this.diagnostics.error("unhandledrejection",e.reason));
    this.contracts=new ContractService();this.repo=new SaveRepository(this.diagnostics);this.resources=new ResourceService();this.inventory=new InventoryService(this.resources);this.technology=new TechnologyService();this.collection=new CollectionService(this.resources,this.inventory,this.technology);this.colony=new ColonyService(this.inventory,this.technology);this.trade=new TradeService(this.resources,this.inventory);this.land=new LandService();this.development=new DevelopmentService(this.inventory,this.land);this.world=new WorldService(this.resources,this.contracts,this.land);this.sites=new SiteService(this.contracts,this.technology,this.inventory,this.colony);this.survey=new SurveyService(this.world,this.contracts);this.engine=new SimulationEngine(this.resources,this.technology,this.collection,this.trade,this.inventory,this.colony);this.portfolio=new PortfolioService();this.icons=new ResourceIcons();
    const saved=this.repo.load();this.state=normalizeState(saved||createGameState(this.contracts.first()));this.land.ensure(this.state);this.development.sync(this.state);this.portfolio.ensure(this.state);this.portfolio.captureActive(this.state,true);this.repo.setBeforeSave(()=>this.portfolio.captureActive(this.state,true));this.prepareActive();
    this.ui=new UIController({state:this.state,repo:this.repo,resources:this.resources,inventory:this.inventory,collection:this.collection,colony:this.colony,portfolio:this.portfolio,sites:this.sites,technology:this.technology,survey:this.survey,contracts:this.contracts,world:this.world,icons:this.icons,diagnostics:this.diagnostics,land:this.land,development:this.development,onHardReset:()=>this.hardReset(),onNewContract:c=>this.addColony(c),onSwitchColony:id=>this.switchColony(id),onRemoveColony:mode=>this.removeColony(mode),onMakeLiability:()=>this.makeLiability(),onRelocateColony:()=>this.relocateColony(),onRecalculate:()=>{this.development.sync(this.state);this.engine.recalculate(this.state);this.view?.safeDraw()},onSelectLand:(index,options)=>this.selectLand(index,options),onPlaceDevelopment:(tile,kind)=>this.placeDevelopment(tile,kind),onDemolishDevelopment:tile=>this.demolishDevelopment(tile)});
    this.tradeUI=new TradeUI({state:this.state,trade:this.trade,repo:this.repo,ui:this.ui});this.view=new WorldView({state:this.state,world:this.world,survey:this.survey,resources:this.resources,technology:this.technology,icons:this.icons,diagnostics:this.diagnostics,land:this.land,onTap:(x,y)=>this.tap(x,y),onMulti:cells=>this.multi(cells),onInspect:(x,y)=>this.inspect(x,y)});
    this.accumulator=0;this.lastFrame=performance.now();this.renderAll();requestAnimationFrame(now=>this.loop(now));document.addEventListener("visibilitychange",()=>{if(document.hidden)this.repo.save(this.state)});if(this.state.status==="site-selection")queueMicrotask(()=>this.ui.landSelection());else if(this.state.company.gameOver)queueMicrotask(()=>this.ui.gameOver?.());
  }
  prepareActive(){this.land.ensure(this.state);this.development.sync(this.state);this.technology.recompute(this.state);this.engine.recalculate(this.state);if(this.state.status!=="site-selection")this.survey.fill(this.state);}
  renderAll(){this.ui?.render();this.tradeUI?.render();this.ui?.syncSpeed();this.view?.syncView?.();this.view?.safeDraw();}
  inspect(x,y){if(this.state.status==="site-selection"){this.ui.landSelection();return;}const tile=this.world.get(this.state,x,y);this.ui.landTile(tile);}
  tap(x,y){
    if(this.state.status==="site-selection"){this.ui.landSelection();return;}if(this.land.isShipTile(x,y)){this.ui.company();return;}const tile=this.world.get(this.state,x,y);
    if(!tile.revealed){const r=this.survey.enqueue(this.state,x,y);if(r.ok){this.ui.toast(r.active?`Surveying ${x},${y}...`:`Queued ${x},${y}.`);this.view.safeDraw()}else this.ui.landTile(tile);return;}
    if(tile.development?.kind==="housing"||tile.development?.kind==="industry"){const r=this.development.upgrade(this.state,tile);if(r.ok){this.prepareActive();this.repo.save(this.state);this.ui.toast(`${this.development.label(tile.development.kind)} upgraded to L${tile.development.level}.`);this.view.safeDraw()}else this.ui.toast(r.reason);return;}
    if(tile.resourceId&&!tile.resourceCovered){const r=tile.developed?this.sites.upgrade(this.state,tile):this.sites.develop(this.state,tile);if(r.ok){this.land.syncExtraction(tile,r.build);this.prepareActive();this.repo.save(this.state);this.ui.toast(`${tile.name} ${tile.level===1?"developed":`upgraded to L${tile.level}`}.`);this.view.safeDraw()}else this.ui.toast(r.reason);return;}
    this.ui.buildChoice(tile);
  }
  multi(cells){const n=this.survey.enqueueMany(this.state,cells);this.ui.toast(n?`${n} cell${n===1?"":"s"} added to survey queue.`:this.state.contract.ended?"Mining contract ended; surveying is disabled.":"No new cells selected.");this.view.safeDraw();}
  selectLand(index,{abandon=false}={}){const result=this.land.settle(this.state,index,{abandon});if(!result.ok){this.ui.toast(result.reason);return false;}this.prepareActive();this.ui.modal.classList.add("hidden");this.ui.tilePanel.classList.add("hidden");this.portfolio.captureActive(this.state,true);this.renderAll();this.repo.save(this.state);this.ui.toast(abandon?`Relocated to landing site ${index+1}. Most local stock and all development were left behind.`:`Landing site ${index+1} established. Survey the land to find resources and building space.`);return true;}
  placeDevelopment(tile,kind){const r=this.development.place(this.state,tile,kind);if(!r.ok){this.ui.toast(r.reason);return false;}this.prepareActive();this.ui.modal.classList.add("hidden");this.repo.save(this.state);this.renderAll();this.ui.toast(`${this.development.label(kind)} L1 constructed${r.destroyedFood?" • natural Food resource destroyed":r.coversResource?" over the known resource":""}.`);return true;}
  demolishDevelopment(tile){const r=this.development.demolish(this.state,tile);if(!r.ok){this.ui.toast(r.reason);return false;}this.prepareActive();this.ui.modal.classList.add("hidden");this.repo.save(this.state);this.renderAll();this.ui.toast(`Development demolished${r.recover?` • ${r.recover} Build recovered`:""}.`);return true;}
  addColony(contract){if(this.state.company.gameOver){this.ui.toast("This corporation has ended. Start a new corporation to continue.");return false;}if(!this.technology.meetsRequirements(this.state,contract.requiredTech)){this.ui.toast("Technology requirements not met.");return false;}if(this.state.trade.active)this.trade.depart(this.state);this.portfolio.addColony(this.state,contract);this.land.ensure(this.state);this.development.sync(this.state);this.prepareActive();this.ui.modal.classList.add("hidden");this.ui.tilePanel.classList.add("hidden");this.renderAll();this.repo.save(this.state);this.ui.landSelection();return true;}
  switchColony(id){if(this.state.trade.active)this.trade.depart(this.state);if(!this.portfolio.switchTo(this.state,id)){this.ui.toast("Colony could not be loaded.");return false;}if(this.state.trade.active){this.state.trade.active=false;this.state.trade.arrivedAt=null;if(this.contracts.isOperating(this.state))this.state.speed=1;}this.prepareActive();this.ui.modal.classList.add("hidden");this.ui.tilePanel.classList.add("hidden");this.renderAll();this.repo.save(this.state);if(this.state.status==="site-selection")this.ui.landSelection();else if(this.state.status==="dead")this.ui.colonyPanel();else if(this.state.status==="deadline-missed")this.ui.deadline("extension");else if(this.state.status==="failed")this.ui.deadline("failed");return true;}
  removeColony(mode="corporate-return"){const result=this.portfolio.removeActive(this.state);if(!result.ok){this.ui.toast(result.reason);return false;}this.prepareActive();this.ui.modal.classList.add("hidden");this.ui.tilePanel.classList.add("hidden");this.renderAll();this.repo.save(this.state);this.ui.toast(mode==="abandon-dead"?"Dead colony record abandoned.":"Colony returned to the corporation.");this.ui.coloniesPanel();return true;}
  makeLiability(){this.contracts.endAsLiability(this.state);this.prepareActive();this.repo.save(this.state);this.renderAll();this.ui.toast("Contract ended. Colony remains your responsibility and can still be lost if life support fails.");}
  relocateColony(){const cost=this.colony.relocationCost(this.state);if(this.state.portfolio.colonies.length<=1){this.ui.toast("Open another colony before disposing of your final colony.");return false;}if(this.state.company.cash<cost){this.ui.toast(`Relocation requires £${Math.round(cost).toLocaleString()}.`);return false;}this.state.company.cash-=cost;const result=this.portfolio.removeActive(this.state);if(!result.ok){this.state.company.cash+=cost;this.ui.toast(result.reason);return false;}this.prepareActive();this.renderAll();this.repo.save(this.state);this.ui.toast("Population relocated and colony closed.");this.ui.coloniesPanel();return true;}
  hardReset(){if(!confirm("Erase all MineIT saves on this browser?"))return;this.repo.clearAll();const fresh=createGameState(this.contracts.first());Object.keys(this.state).forEach(k=>delete this.state[k]);Object.assign(this.state,fresh);this.land.ensure(this.state);this.development.sync(this.state);this.portfolio.ensure(this.state);this.portfolio.captureActive(this.state,true);this.prepareActive();this.ui.modal.classList.add("hidden");this.ui.tilePanel.classList.add("hidden");this.renderAll();this.repo.save(this.state);this.ui.landSelection();}
  advanceColony(local,active=false){if(!this.contracts.isOperating(local))return{discoveries:[],shipArrived:false,deadline:null,died:false};this.land.ensure(local);this.development.sync(local);const tickResult=this.engine.tick(local);this.engine.recalculate(local);if(tickResult.colonyDied)return{discoveries:[],shipArrived:false,deadline:null,died:true,deaths:tickResult.deaths};const discoveries=local.contract.ended?[]:this.survey.tick(local);this.engine.recalculate(local);let shipArrived=false;if(active&&this.trade.shouldArrive(local)){shipArrived=this.trade.arrive(local);this.engine.recalculate(local);}return{discoveries,shipArrived,deadline:this.contracts.deadlineState(local),died:false,deaths:tickResult.deaths};}
  resolveBackgroundDeadline(local,kind){if(kind==="complete"){this.contracts.awardCompletion(local);local.speed=1;}else if(kind==="renewal-ended"){this.contracts.enterHoldover(local);local.speed=1;}else if(kind==="extension"){local.status="deadline-missed";local.speed=0;}else if(kind==="failed"){local.contract.ended=true;local.status="liability";local.speed=1;}}
  tick(){this.diagnostics.ticks++;this.diagnostics.lastTick=Date.now();let result,backgroundDeaths=[];try{result=this.advanceColony(this.state,true);this.portfolio.captureActive(this.state,true);this.portfolio.simulateInactive(this.state,(temp,entry)=>{const background=this.advanceColony(temp,false);if(background.deadline)this.resolveBackgroundDeadline(temp,background.deadline);if(background.died)backgroundDeaths.push(temp.contract?.colonyName||entry.name||"Colony")});this.portfolio.captureActive(this.state,true);this.state.company.gameOver=!this.state.portfolio.colonies.some(entry=>entry?.data?.status!=="dead")}catch(error){this.diagnostics.error("simulation core crashed",error);this.state.speed=0;this.ui.syncSpeed();return}if(this.state.company.gameOver&&backgroundDeaths.length){this.repo.save(this.state);this.ui.gameOver?.()}else if(result.died){this.repo.save(this.state);if(this.state.company.gameOver)this.ui.gameOver?.();else this.ui.colonyLost?.()}else if(result.deadline){this.ui.deadline(result.deadline)}else if(result.shipArrived){try{this.tradeUI.open()}catch(e){this.diagnostics.error("trade ship UI failed",e)}}else if(result.discoveries.length){try{const found=result.discoveries.filter(t=>t.resourceId),rare=found.filter(t=>t.quality>=CONFIG.RARE_QUALITY).sort((a,b)=>b.quality-a.quality);if(rare.length)this.ui.rare(rare[0]);else if(result.discoveries.length===1){const t=result.discoveries[0];this.ui.toast(t.resourceId?`${t.name} discovered • Q${Math.round(t.quality)}`:`${this.land.terrainLabel(t.terrain)} surveyed • no exploitable surface resource.`)}else this.ui.toast(`${result.discoveries.length} surveys completed • ${found.length} resource${found.length===1?"":"s"} found.`)}catch(e){this.diagnostics.error("discovery UI failed",e)}}else if(backgroundDeaths.length)this.ui.toast(`${backgroundDeaths.join(", ")} lost. Review your colony portfolio.`);try{this.ui.render();this.tradeUI.render()}catch(e){this.diagnostics.error("HUD render failed",e)}this.view.safeDraw();const absoluteDay=(this.state.year-1)*CONFIG.DAYS_PER_YEAR+this.state.day;if(absoluteDay%30===0)this.repo.save(this.state);}
  loop(now){this.diagnostics.heartbeat++;try{const delta=Math.min(120,now-this.lastFrame);this.lastFrame=now;const backgroundOnly=this.state.status==="dead"&&!this.state.company.gameOver&&this.state.portfolio?.colonies?.some(entry=>entry?.data?.status!=="dead"),effectiveSpeed=backgroundOnly?1:this.state.speed;if(effectiveSpeed>0&&(this.contracts.isOperating(this.state)||backgroundOnly)){this.accumulator+=delta*effectiveSpeed;while(this.accumulator>=CONFIG.DAY_MS){this.accumulator-=CONFIG.DAY_MS;this.tick()}}this.ui.render();this.tradeUI.render()}catch(e){this.diagnostics.error("animation loop failed",e)}requestAnimationFrame(next=>this.loop(next));}
}
addEventListener("DOMContentLoaded",()=>{try{const app=new MineITApp();window.mineIT=app;window.mineITBoot=app}catch(error){console.error(error);const app=window.mineITBoot;app?.diagnostics?.error("startup failed",error);const badge=document.querySelector("#errorBadge");if(badge){badge.textContent="STARTUP ERROR • TAP FOR DETAILS";badge.classList.remove("hidden");if(app?.ui)badge.onclick=()=>app.ui.diagnosticsPanel();}}});
