export const CONFIG = Object.freeze({
  DAYS_PER_YEAR: 360,
  DAY_MS: 360,
  GRID_SIZE: 8,
  SAVE_KEY: "mineit.save.v1",
  SAVE_PREFIX: "mineit.",
  START_CASH: 32000,
  START_POPULATION: 120,
  RARE_QUALITY: 2500,
  MAX_EXTENSIONS: 3,
  TRADE_INTERVAL_DAYS: 180,
  FIRST_TRADE_DAY: 181,
  CORPORATE_BUY_MARKUP: 1.5
});
