export class Diagnostics {
  constructor(limit=120,interactionLimit=240){this.limit=limit;this.interactionLimit=interactionLimit;this.entries=[];this.interactions=[];this.interactionSequence=0;this.errors=0;this.heartbeat=0;this.ticks=0;this.lastTick=0;this.listeners=new Set();}
  subscribe(listener){this.listeners.add(listener);return()=>this.listeners.delete(listener);}
  emit(){for(const listener of this.listeners)listener(this);}
  add(level,message,data){const stamp=new Date().toISOString().slice(11,19);let suffix="";if(data!==undefined){try{suffix=" "+(typeof data==="string"?data:JSON.stringify(data));}catch{suffix=" [unserializable]";}}this.entries.push(`[${stamp}] ${level.toUpperCase()} ${message}${suffix}`);if(this.entries.length>this.limit)this.entries.shift();if(level==="error")this.errors++;this.emit();}
  interaction(stage,data={}){const entry={seq:++this.interactionSequence,time:new Date().toISOString(),stage,...data};this.interactions.push(entry);if(this.interactions.length>this.interactionLimit)this.interactions.shift();return entry;}
  clearInteractions(){this.interactions.length=0;}
  info(message,data){this.add("info",message,data);}warn(message,data){this.add("warn",message,data);}error(message,error){const detail=error instanceof Error?`${error.name}: ${error.message}${error.stack?`\n${error.stack}`:""}`:String(error??"Unknown error");this.add("error",message,detail);}
  colonySnapshots(state){
    if(!state?.portfolio?.colonies)return[];
    return state.portfolio.colonies.map(entry=>{
      const d=entry.id===state.portfolio.activeColonyId?state:entry.data||{},trade=d.trade||{},contract=d.contract||{};
      return{id:entry.id,name:contract.colonyName||entry.name,status:d.status,contractCompleted:!!contract.completed,contractEnded:!!contract.ended,pendingContractDecision:contract.pendingDecision||null,tradeActive:!!trade.active,nextTradeArrivalDay:trade.nextArrivalDay??null,tradeVisits:trade.visits??0,population:d.pop??0};
    });
  }
  snapshot(state){return{version:"5.8.1-multi-colony-lifecycle",saveVersion:state?.version,corporationDate:state?`Y${state.year} D${state.day}`:"no state",colony:state?.contract?.colonyName,colonies:state?.portfolio?.colonies?.length??0,landingSite:state?.colony?.land?.selectedIndex??null,mapView:"unified",mapFocus:state?.colony?.land?.focusMode||"all",pendingEvents:state?.company?.pendingEvents?.length??0,eventQueue:(state?.company?.pendingEvents||[]).map(e=>({type:e.type,colonyId:e.colonyId,colonyName:e.colonyName,kind:e.kind||null,recovered:!!e.recovered,sequence:e.sequence??null})),eventReturnColonyId:state?.company?.eventReturnColonyId??null,eventResumeSpeed:state?.company?.eventResumeSpeed??null,colonyStates:this.colonySnapshots(state),gameOver:!!state?.company?.gameOver,speed:state?.speed,status:state?.status,emergencyMode:!!state?.colony?.emergencyMode,housingCapacity:state?.colony?.housingCapacity,powerCapacity:state?.metrics?.powerCapacity,industryInstalled:state?.metrics?.industryInstalled,industryEffective:state?.metrics?.industry,tech:state?.company?.tech,survivalSupply:state?.metrics?.survivalSupply,foodDays:state?.metrics?.foodDays,fuelDays:state?.metrics?.fuelDays,oreDays:state?.metrics?.oreDays,industryCapacity:state?.metrics?.industryCapacity,industryLoad:state?.metrics?.industryLoad,industryCommercialFactor:state?.metrics?.industryCommercialFactor,workforceAvailable:state?.metrics?.workforceAvailable,workforceRequired:state?.metrics?.workforceRequired,workforceFree:state?.metrics?.workforceFree,processingBonus:state?.metrics?.processingBonus,lastAccidentDeaths:state?.metrics?.lastAccidentDeaths??0,pendingTransports:state?.colony?.transportOrders?.length??0,gameLogEvents:state?.gameLog?.events?.length??0,telemetrySnapshots:state?.gameLog?.telemetry?.length??0,heartbeat:this.heartbeat,ticks:this.ticks,msSinceLastTick:this.lastTick?Date.now()-this.lastTick:null,activeScans:state?.scans?.length??0,queuedScans:state?.scanQueue?.length??0,interactionEvents:this.interactions.length};}
  text(state){return["MINEIT DIAGNOSTICS",JSON.stringify(this.snapshot(state),null,2),"",...this.entries,"",`INTERACTION TRACE (${this.interactions.length})`,...this.interactions.map(entry=>JSON.stringify(entry))].join("\n");}
}
