import assert from "node:assert/strict";
import { ContractService } from "../js/domain/contract-service.js";
import { createGameState,normalizeState } from "../js/domain/game-state-runtime.js";
import { BuyerService } from "../js/domain/buyer-service.js";
import { InventoryService } from "../js/domain/inventory-service.js";
import { ResourceService } from "../js/domain/resource-service.js";

const contracts=new ContractService(),resources=new ResourceService(),inventory=new InventoryService(resources),buyers=new BuyerService(resources,inventory);
const state=createGameState(contracts.first());buyers.ensure(state);const offer=state.company.buyers.offers.find(o=>o.minRep===0),entered=buyers.enterContract(state,offer.id);assert.equal(entered.ok,true);const relationship=buyers.relationship(state,offer.buyerId),contract=entered.contract;
state.company.rep=-12.34;relationship.happiness=62;relationship.misses=1;relationship.consecutiveRed=1;relationship.history.push({absoluteDay:50,result:"major-partial",quantity:500,contracted:1000,revenue:123.45,daysLate:10,happinessChange:-4});relationship.totalUnits=500;relationship.totalRevenue=123.45;contract.ship={status:"orbital-holding",dueAbsoluteDay:70,attemptIndex:2,nextEventAbsoluteDay:80,eventPending:true};contract.nextDueAbsoluteDay=70;state.company.pendingEvents.push({type:"buyer",colonyId:state.colonyId,colonyName:state.contract.colonyName,contractId:contract.id,offerId:offer.id,buyerId:offer.buyerId,attemptIndex:2,dueAbsoluteDay:70,sequence:1,recovered:false});
const expectedOffer=JSON.parse(JSON.stringify(offer)),expectedContract=JSON.parse(JSON.stringify(contract)),expectedRelationship=JSON.parse(JSON.stringify(relationship));const loaded=normalizeState(JSON.parse(JSON.stringify(state)));buyers.ensure(loaded);
assert.equal(loaded.version,15);assert.equal(loaded.company.rep,-12.34);assert.deepEqual(loaded.company.buyers.offers.find(o=>o.id===offer.id),expectedOffer,"seeded offer terms must not reroll on load");assert.deepEqual(loaded.company.buyers.contracts[contract.id],expectedContract,"active buyer obligation and collection ship state must survive load");assert.deepEqual(loaded.company.buyers.relationships[offer.buyerId],expectedRelationship,"buyer happiness/history/totals must survive load");assert.equal(loaded.company.pendingEvents.some(e=>e.type==="buyer"&&e.contractId===contract.id),true,"pending buyer attention event must survive load");assert.equal(loaded.company.buyers.contracts[contract.id].portraitKey,offer.portraitKey);assert.equal(loaded.company.buyers.contracts[contract.id].shipImageKey,offer.shipImageKey);
const loadedAgain=normalizeState(JSON.parse(JSON.stringify(loaded)));buyers.ensure(loadedAgain);assert.equal(loadedAgain.company.rep,-12.34);assert.deepEqual(loadedAgain.company.buyers.contracts[contract.id],expectedContract);assert.equal(loadedAgain.company.buyers.relationships[offer.buyerId].history.length,1);
console.log("MineIT Stage 8 buyer save round-trip preserves fractional reputation, offers, obligations and history");
