import assert from "node:assert/strict";
import { BUYER_IDENTITIES,BUYER_SHIP_CLASSES,buyerShipClass } from "../js/data/buyer-content.js";
import { rangeFor,marketPhase } from "../js/data/buyer-market-balance.js";
import { BuyerService } from "../js/domain/buyer-service.js";
import { ContractService } from "../js/domain/contract-service.js";
import { InventoryService } from "../js/domain/inventory-service.js";
import { ResourceService } from "../js/domain/resource-service.js";
import { TradeService } from "../js/domain/trade-service.js";
import { REPUTATION_LEVELS,changeReputation,reputationLevel } from "../js/domain/reputation-service.js";

const resources=new ResourceService(),inventory=new InventoryService(resources),buyers=new BuyerService(resources,inventory),trade=new TradeService(resources,inventory);
const qualityValue={common:1,good:51,excellent:201,exceptional:751,rare:2501,extraordinary:7501};
const approx=(actual,expected,epsilon=.000001)=>assert.ok(Math.abs(actual-expected)<=epsilon,`${actual} != ${expected}`);
const state=(seed=12345)=>({year:2,day:40,seed,status:"playing",pop:120,company:{rep:0,cash:0,earn:0,wins:0,expansion:{seed},buyers:null},contract:{localRevenue:0,localCosts:0,ended:false},inventory:{},trade:{active:false,cargoUsed:0,exportUsed:0,passengersUsed:0},colonyId:"colony-a",colony:{spaceport:{level:1,berthCapacity:2,providedBy:"conglomerate",tile:{x:0,y:0}},engineeringDeployments:[]},metrics:{}});
const stock=(s,offer,amount)=>inventory.store(s,offer.resourceType,offer.resourceId,offer.resourceName,amount,qualityValue[offer.minQuality]);
const enterFirst=(s)=>{buyers.ensure(s);const offer=s.company.buyers.offers.find(o=>o.minRep<=s.company.rep);assert.ok(offer);const result=buyers.enterContract(s,offer.id);assert.equal(result.ok,true);return{offer,contract:result.contract};};
const finalMiss=(s,contract)=>{const now=buyers.absoluteDay(s);contract.ship={status:"docked",dueAbsoluteDay:now-15,attemptIndex:3,nextEventAbsoluteDay:now,eventPending:true};return buyers.resolveMiss(s,contract.id);};

assert.equal(BUYER_IDENTITIES.length,1000);assert.equal(BUYER_SHIP_CLASSES.length,30);assert.equal(new Set(BUYER_IDENTITIES.map(x=>x.name)).size,1000);assert.equal(new Set(BUYER_IDENTITIES.map(x=>x.company)).size,1000);assert.equal(new Set(BUYER_IDENTITIES.map(x=>x.shipName)).size,1000);
assert.deepEqual(REPUTATION_LEVELS.map(x=>x.name),["Disgraced","Distrusted","Questionable","Unknown","Emerging","Recognised","Established","Trusted","Preferred","Elite"]);for(const [value,name] of [[-100,"Disgraced"],[-24.99,"Distrusted"],[-.01,"Questionable"],[0,"Unknown"],[5,"Emerging"],[15,"Recognised"],[30,"Established"],[50,"Trusted"],[70,"Preferred"],[90,"Elite"],[100,"Elite"]])assert.equal(reputationLevel(value).name,name);const clampState={company:{rep:99.99}};changeReputation(clampState,.1);assert.equal(clampState.company.rep,100);changeReputation(clampState,-250);assert.equal(clampState.company.rep,-100);
assert.equal(buyers.resolvedHappinessChange(0,1),1,"full on-time shipment gets the +1 timing bonus");assert.equal(buyers.resolvedHappinessChange(0,.8),-1,"on-time minor partial gets only its partial penalty");assert.equal(buyers.resolvedHappinessChange(0,.6),-2,"on-time major partial gets only its partial penalty");assert.equal(buyers.resolvedHappinessChange(10,.8),-3,"late partial stacks lateness and partial penalties");assert.equal(buyers.partialChange(.49),null);assert.equal(buyers.timingChange(5),-1);assert.equal(buyers.timingChange(10),-2);assert.equal(buyers.timingChange(15),-3);

const a=state(8302026),b=state(8302026),c=state(8302027);buyers.ensure(a);buyers.ensure(b);buyers.ensure(c);assert.equal(a.company.buyers.offers.length,1000);assert.deepEqual(a.company.buyers.offers,b.company.buyers.offers);assert.notDeepEqual(a.company.buyers.offers.slice(0,10),c.company.buyers.offers.slice(0,10));
for(const offer of a.company.buyers.offers){const identity=BUYER_IDENTITIES.find(x=>x.id===offer.buyerId),ship=buyerShipClass(identity.shipClassId),direct=resources.sellPrice(offer.resourceType,offer.resourceId,offer.minQuality),range=rangeFor(offer.resourceName,marketPhase(offer.minRep));assert.ok(offer.unitRate<direct,`${offer.id} must stay below direct price`);assert.ok(offer.quantity<=ship.capacity,`${offer.id} exceeds ${ship.name}`);assert.ok(range&&offer.quantity>=range[0]&&offer.quantity<=range[1],`${offer.id} quantity outside approved range`);}
const locked=a.company.buyers.offers.find(o=>o.minRep>0);assert.ok(locked);assert.equal(buyers.catalog(a).some(o=>o.id===locked.id),true);assert.equal(buyers.canEnter(a,locked.id).ok,false);const first=a.company.buyers.offers.find(o=>o.minRep===0);const entered=buyers.enterContract(a,first.id);assert.equal(entered.ok,true);assert.equal(entered.contract.colonyId,"colony-a");assert.equal(entered.contract.quantity,first.quantity);assert.equal(entered.contract.unitRate,first.unitRate);assert.equal(buyers.canEnter(a,first.id,"colony-b").ok,false);
inventory.store(a,first.resourceType,first.resourceId,first.resourceName,100,60);inventory.store(a,first.resourceType,first.resourceId,first.resourceName,100,300);const removed=inventory.removeWeighted(a,first.resourceType,first.resourceId,150,{minimumQualityKey:"good",lowestFirst:true});assert.equal(removed.removed,150);assert.equal(removed.bands.good?.amount,100);assert.equal(removed.bands.excellent?.amount,50);

// Corporate Ship exports award +0.01 once per visit even when the player splits sales.
const corp=state(9);corp.trade.active=true;corp.trade.exportReputationAwarded=false;inventory.store(corp,"ore","iron","Iron Ore",100,60);let sale=trade.sellBand(corp,"ore:iron","good",10);assert.equal(sale.ok,true);approx(corp.company.rep,.01);sale=trade.sellBand(corp,"ore:iron","good",10);assert.equal(sale.ok,true);approx(corp.company.rep,.01);trade.arrive({...corp,trade:{...corp.trade,active:false,nextArrivalDay:1},company:corp.company});

// A successful 10-year colony contract gives +0.10 regardless of medal band.
const contractService=new ContractService(),completion={company:{rep:0,wins:0},status:"playing",contract:{goals:{food:1,industry:1,pop:1},bands:{silver:10,gold:20,plat:30},localRevenue:0,localCosts:0,completionAwarded:false,completed:false},metrics:{food:1,industry:1},pop:1};const awarded=contractService.awardCompletion(completion);assert.equal(awarded.ok,true);approx(completion.company.rep,.10);assert.equal(completion.company.wins,1);contractService.awardCompletion(completion);approx(completion.company.rep,.10);

// Full on-time buyer transfer resolves, pays actual units, and gives only +0.01 global reputation.
const full=state(10),fullEntry=enterFirst(full);stock(full,fullEntry.offer,fullEntry.offer.quantity);fullEntry.contract.ship={status:"docked",dueAbsoluteDay:buyers.absoluteDay(full),attemptIndex:0,nextEventAbsoluteDay:buyers.absoluteDay(full),eventPending:true};const exportBefore=full.trade.exportUsed,fullResult=buyers.transfer(full,fullEntry.contract.id);assert.equal(fullResult.ok,true);assert.equal(fullResult.record.result,"full");assert.equal(fullResult.record.happinessChange,1);assert.equal(buyers.relationship(full,fullEntry.offer.buyerId).happiness,76);approx(full.company.rep,.01);assert.equal(full.trade.exportUsed,exportBefore,"buyer collection must not consume Corporate Ship export capacity");assert.equal(fullResult.revenue,fullEntry.offer.fullValue);

// 80% at +10 is accepted, pays proportionally, applies -3 buyer and -0.29 net global reputation.
const partial=state(11);partial.company.rep=100;const partialEntry=enterFirst(partial),partialQty=partialEntry.offer.quantity*.8;stock(partial,partialEntry.offer,partialQty);partialEntry.contract.ship={status:"docked",dueAbsoluteDay:buyers.absoluteDay(partial)-10,attemptIndex:2,nextEventAbsoluteDay:buyers.absoluteDay(partial),eventPending:true};const partialResult=buyers.transfer(partial,partialEntry.contract.id);assert.equal(partialResult.ok,true);assert.equal(partialResult.record.result,"minor-partial");assert.equal(partialResult.record.happinessChange,-3);approx(partialResult.revenue,partialQty*partialEntry.offer.unitRate,.01);approx(partial.company.rep,99.71,.0001);

// Under 50% cannot transfer; no berth keeps a fully stocked ship in orbit and blocks transfer.
const orbit=state(12),orbitEntry=enterFirst(orbit);stock(orbit,orbitEntry.offer,orbitEntry.offer.quantity);orbit.colony.spaceport.berthCapacity=1;orbit.trade.active=true;orbitEntry.contract.nextDueAbsoluteDay=buyers.absoluteDay(orbit);const dueEvents=buyers.processDay(orbit);assert.equal(dueEvents.length,1);assert.equal(orbitEntry.contract.ship.status,"orbital-holding");assert.equal(buyers.projection(orbit,orbitEntry.contract.id).canTransfer,false);orbit.trade.active=false;assert.equal(buyers.tryDock(orbit,orbitEntry.contract),true);assert.equal(orbitEntry.contract.ship.status,"docked");assert.equal(buyers.projection(orbit,orbitEntry.contract.id).canTransfer,true);
const short=state(13),shortEntry=enterFirst(short);stock(short,shortEntry.offer,shortEntry.offer.quantity*.4);shortEntry.contract.ship={status:"docked",dueAbsoluteDay:buyers.absoluteDay(short),attemptIndex:0,nextEventAbsoluteDay:buyers.absoluteDay(short),eventPending:true};assert.equal(buyers.projection(short,shortEntry.contract.id).canTransfer,false);assert.equal(buyers.transfer(short,shortEntry.contract.id).ok,false);

// Wait attempts advance due/+5/+10/+15 exactly and final miss escalates -10/-20/-30.
const waits=state(14),waitEntry=enterFirst(waits);waitEntry.contract.nextDueAbsoluteDay=buyers.absoluteDay(waits);buyers.processDay(waits);let waitResult=buyers.continueWaiting(waits,waitEntry.contract.id);assert.equal(waitResult.nextAttemptAbsoluteDay,waitEntry.contract.ship.dueAbsoluteDay+5);waits.day+=5;buyers.processDay(waits);waitResult=buyers.continueWaiting(waits,waitEntry.contract.id);assert.equal(waitResult.nextAttemptAbsoluteDay,waitEntry.contract.ship.dueAbsoluteDay+10);waits.day+=5;buyers.processDay(waits);waitResult=buyers.continueWaiting(waits,waitEntry.contract.id);assert.equal(waitResult.nextAttemptAbsoluteDay,waitEntry.contract.ship.dueAbsoluteDay+15);waits.day+=5;buyers.processDay(waits);assert.equal(buyers.continueWaiting(waits,waitEntry.contract.id).ok,false);
const misses=state(15);misses.company.rep=100;const missEntry=enterFirst(misses);buyers.relationship(misses,missEntry.offer.buyerId).happiness=100;let miss=finalMiss(misses,missEntry.contract);assert.equal(miss.record.happinessChange,-10);assert.equal(miss.terminated,false);miss=finalMiss(misses,missEntry.contract);assert.equal(miss.record.happinessChange,-20);assert.equal(miss.terminated,false);miss=finalMiss(misses,missEntry.contract);assert.equal(miss.record.happinessChange,-30);assert.equal(miss.terminated,true);assert.match(miss.reason,/Third missed shipment/);

// Two consecutive resolved Red cycles terminate even before a third miss.
const red=state(16);red.company.rep=100;const redEntry=enterFirst(red),redRelationship=buyers.relationship(red,redEntry.offer.buyerId);redRelationship.happiness=40;let redMiss=finalMiss(red,redEntry.contract);assert.equal(redRelationship.happiness,30);assert.equal(redRelationship.consecutiveRed,1);redMiss=finalMiss(red,redEntry.contract);assert.equal(redMiss.terminated,true);assert.match(redMiss.reason,/consecutive resolved shipment cycles/);

// Player cancellation uses the normal -5/-0.5 coupling, persists happiness, applies cooldown and is blocked while a ship waits.
const cancelled=state(17),cancelEntry=enterFirst(cancelled),cancelResult=buyers.cancelContract(cancelled,cancelEntry.contract.id);assert.equal(cancelResult.ok,true);assert.equal(cancelResult.relationship.happiness,70);approx(cancelled.company.rep,-.5);assert.equal(cancelResult.cooldownUntilAbsoluteDay,buyers.absoluteDay(cancelled)+cancelEntry.contract.intervalDays);assert.equal(buyers.canEnter(cancelled,cancelEntry.offer.id).ok,false);
const blocked=state(18),blockedEntry=enterFirst(blocked);blockedEntry.contract.ship={status:"docked",dueAbsoluteDay:buyers.absoluteDay(blocked),attemptIndex:0,nextEventAbsoluteDay:buyers.absoluteDay(blocked),eventPending:true};assert.equal(buyers.cancelContract(blocked,blockedEntry.contract.id).ok,false);

console.log("MineIT Stage 8 conglomerate buyer catalogue, reputation, lifecycle, berth and fulfilment regression passed");
