import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { CONFIG } from "../js/core/config.js";
import { ContractService } from "../js/domain/contract-service.js";
import { createGameState, normalizeState } from "../js/domain/game-state-runtime.js";
import { ResourceService } from "../js/domain/resource-service.js";
import { InventoryService } from "../js/domain/inventory-service.js";
import { TechnologyService } from "../js/domain/technology-service.js";
import { ColonyService } from "../js/domain/colony-service.js";
import { SiteService } from "../js/domain/site-service.js";
import { TradeService } from "../js/domain/trade-service.js";
import { TransportService } from "../js/domain/transport-service.js";
import { PortfolioService } from "../js/domain/portfolio-service.js";

const contracts=new ContractService(),resources=new ResourceService(),inventory=new InventoryService(resources),tech=new TechnologyService(),colony=new ColonyService(inventory,tech),trade=new TradeService(resources,inventory),transport=new TransportService(),portfolio=new PortfolioService(),sites=new SiteService(contracts,tech,inventory,colony,resources);
const fresh=()=>{const state=createGameState(contracts.first());state.company.cash=1e9;tech.recompute(state);return state;};
const finite=(quality,size="Large",level=1,requiredMiningLevel=1)=>({x:1,y:1,revealed:true,developed:true,depleted:false,level,type:"ore",resourceId:"surface-iron",name:"Surface Iron Nodules",quality,requiredMiningLevel,sustainability:"finite",depositScale:size,reserve:1e6,initialReserve:1e6});

const low=finite(20),high=finite(9000);assert.equal(resources.sitePotentialRate(low),resources.sitePotentialRate(high),"Quality must not change extraction throughput");assert.ok(trade.sellPrice("ore","gold","extraordinary")>trade.sellPrice("ore","gold","common")*3,"Quality must remain economically valuable");assert.ok(resources.sitePotentialRate(finite(100,"Colossal"))>resources.sitePotentialRate(finite(100,"Small")));assert.ok(resources.sitePotentialRate(finite(100,"Colossal"))/resources.sitePotentialRate(finite(100,"Small"))<2,"Deposit size bias should be material but modest");

const workers=fresh();assert.equal(colony.workforceAvailable(workers),60,"Half of the starting population should be operational workforce");const m1=finite(100,"Large",1,1),m6=finite(100,"Large",1,6);assert.ok(colony.siteWorkforce(workers,m6)>colony.siteWorkforce(workers,m1),"Advanced extraction must need more workers");workers.tiles={};for(let i=0;i<5;i++)workers.tiles[`s${i}`]={...finite(100,"Large",1,1),x:i+1,type:"build",resourceId:"stone",name:"Stone"};assert.equal(colony.freeWorkforce(workers),0);const candidate={...finite(100,"Large",0,1),developed:false,x:9};assert.equal(sites.developRequirements(workers,candidate).ok,false);assert.match(sites.developRequirements(workers,candidate).reason,/free operational workers/);

const renewable={x:2,y:2,revealed:true,developed:true,depleted:false,level:1,type:"food",resourceId:"fungal",name:"Fungal Shelf",quality:500,requiredMiningLevel:1,sustainability:"renewable",abundanceLabel:"Vast",renewableOriginalRank:3,renewableHealth:4,harvestIntensity:2};for(let i=0;i<260;i++)resources.updateRenewable(renewable);assert.equal(renewable.abundanceLabel,"Large","Sustained over-farming must downgrade renewable size");renewable.harvestIntensity=.25;const damaged=renewable.renewableHealth;for(let i=0;i<100;i++)resources.updateRenewable(renewable);assert.ok(renewable.renewableHealth>damaged,"Under-harvesting should recover a damaged renewable");const fragile={...renewable,abundanceLabel:"Limited",renewableOriginalRank:0,renewableHealth:1,harvestIntensity:2,renewableWiped:false,depleted:false,developed:true};for(let i=0;i<260;i++)resources.updateRenewable(fragile);assert.equal(fragile.renewableWiped,true,"A Limited resource can be wiped out by sustained severe over-farming");assert.equal(fragile.developed,false);

// Dedicated transports reserve capacity from physical housing.
const transportState=fresh();transportState.company.tech.housing=3;transportState.tiles.house={x:8,y:8,revealed:true,development:{kind:"housing",level:3}};tech.recompute(transportState);assert.equal(transportState.colony.housingCapacity,830);const order=transport.request(transportState,500);assert.equal(order.ok,true);assert.equal(order.arrivalDay,91);assert.equal(transport.pendingPopulation(transportState),500);assert.equal(trade.colonistCapacity(transportState),210,"Pending dedicated transports must reserve physical supported housing from regular ship passengers");transportState.day=91;const arrivals=transport.processArrivals(transportState);assert.equal(arrivals.length,1);assert.equal(Math.round(transportState.pop),620);

// Advanced extraction uses deployed Mining capability plus installed physical Industry/Power capacity.
const advanced=fresh();advanced.colony.tech.mining=6;advanced.pop=500;advanced.tiles.factory={x:7,y:7,revealed:true,development:{kind:"industry",level:1}};advanced.tiles.generator={x:8,y:7,revealed:true,development:{kind:"power",level:1}};tech.recompute(advanced);const platinum={x:4,y:4,revealed:true,developed:true,depleted:false,level:1,type:"ore",resourceId:"platinum",name:"Platinum",quality:9000,requiredMiningLevel:6,sustainability:"finite",depositScale:"Huge",reserve:1e6,initialReserve:1e6};let req=sites.upgradeRequirements(advanced,platinum);assert.equal(req.ok,true,"Advanced mine L2 should unlock when deployed Mining L6 and 150 Industry / 60 Power are installed");advanced.colony.tech.mining=5;tech.recompute(advanced);req=sites.upgradeRequirements(advanced,platinum);assert.equal(req.ok,false);assert.match(req.reason,/Mining L6/);

const exportState=fresh();exportState.inventory={};exportState.trade.active=true;exportState.trade.exportUsed=0;inventory.store(exportState,"ore","surface-iron","Surface Iron Nodules",150000,500);inventory.store(exportState,"ore","gold","Gold",10,9000);const all=trade.sellAll(exportState);assert.equal(all.qty,CONFIG.TRADE_BASE_EXPORT_CARGO);assert.equal(exportState.inventory["ore:gold"].qualityBands.extraordinary.amount,0,"SELL ALL must prioritize the highest-value stock when export capacity is reached");assert.ok(exportState.inventory["ore:surface-iron"].amount>0,"The generous export ceiling should cap only unusually large stockpiles");

const global=fresh();portfolio.ensure(global);global.year=4;global.day=100;portfolio.captureActive(global,true);const firstId=global.colonyId,second=contracts.options(2)[0];portfolio.addColony(global,second);assert.equal(global.contract.startAbsoluteDay,(4-1)*CONFIG.DAYS_PER_YEAR+100,"New contracts start on the current corporation day");assert.equal(global.year,4);assert.equal(global.day,100);assert.equal(portfolio.switchTo(global,firstId),true);assert.equal(global.year,4,"Switching colony must never change corporation time");assert.equal(global.day,100);

const legacy=fresh();legacy.version=7;legacy.year=6;legacy.day=20;legacy.portfolio.colonies[0].data.year=6;legacy.portfolio.colonies[0].data.day=20;normalizeState(legacy);assert.equal(legacy.version,10);assert.equal(legacy.year,6);assert.equal(legacy.day,20);assert.equal("year" in legacy.portfolio.colonies[0].data,false,"Colony snapshots must no longer own independent clocks");assert.ok(Number.isFinite(legacy.contract.startAbsoluteDay));

const worldSource=readFileSync(new URL("../js/ui/world-view.js",import.meta.url),"utf8"),tradeUI=readFileSync(new URL("../js/ui/quick-trade-ui.js",import.meta.url),"utf8"),sellView=readFileSync(new URL("../views/quick-trade-sell.html",import.meta.url),"utf8"),ui=readFileSync(new URL("../js/ui/v55-ui.js",import.meta.url),"utf8"),transportView=readFileSync(new URL("../views/dedicated-colony-transport.html",import.meta.url),"utf8"),renewableView=readFileSync(new URL("../views/renewable-harvest.html",import.meta.url),"utf8"),gameLogView=readFileSync(new URL("../views/game-log.html",import.meta.url),"utf8"),app=readFileSync(new URL("../js/app.js",import.meta.url),"utf8");for(const marker of["FOOD","BUILD","FUEL","ORE","data-map-bulk","mapFilterHost"])assert.ok(worldSource.includes(marker));assert.match(tradeUI,/sellableStock/);assert.match(sellView,/Colony reserves are protected/);assert.match(tradeUI,/sellAllQuote/);assert.match(gameLogView,/DOWNLOAD FULL JSON LOG/);assert.match(transportView,/DEDICATED COLONY TRANSPORT/);assert.match(renewableView,/RENEWABLE HARVEST/);assert.match(ui,/dedicated-colony-transport\.html/);assert.match(ui,/renewable-harvest\.html/);assert.match(app,/advanceGlobalDate/);assert.match(app,/processPendingShipEvent/);assert.match(app,/simulateInactive/);
console.log("MineIT canonical synchronized expansion/sustainability regression test passed");
