import assert from "node:assert/strict";
import { ContractService } from "../js/domain/contract-service.js";
import { ResourceService } from "../js/domain/resource-service.js";
import { InventoryService } from "../js/domain/inventory-service.js";
import { ColonyService } from "../js/domain/colony-service.js";
import { DevelopmentService } from "../js/domain/development-service.js";
import { LandService } from "../js/domain/land-service.js";
import { ExpansionService } from "../js/domain/expansion-service.js";
import { createGameState,normalizeState } from "../js/domain/game-state-runtime.js";

const contracts=new ContractService();
const resources=new ResourceService();
const inventory=new InventoryService(resources);
const colonyService=new ColonyService(inventory,{});
const land=new LandService();
const development=new DevelopmentService(inventory,land,colonyService);
const expansion=new ExpansionService(inventory,resources,contracts);
expansion.colonyService=colonyService;

const state=createGameState(contracts.first());
expansion.ensure(state);
state.metrics.fuelIntensity=.1;
for(const type of ["build","ore","fuel","food"])inventory.store(state,type,type==="build"?"fiber":type==="ore"?"surface-iron":type==="fuel"?"biomass":"fungal","Test",100000,500);
const ship=expansion.ship(state);
ship.crew=ship.minimumCrew;
ship.targetSystemId=state.company.expansion.systems.find(system=>!system.home&&system.id!==state.contract.systemId).id;
const route=expansion.travelProfile(state,ship.targetSystemId,null,ship.id);
expansion.loadFuel(state,"fuel:biomass",route.fuelRequired+100);
expansion.loadFood(state,"food:fungal",route.foodRequired+100);
let gate=expansion.canLaunch(state,ship.id);
assert.equal(gate.ok,false);
assert.equal(gate.launchEnabled,true);
assert.match(gate.reason,/Primary Headquarters/);

const hqTile={x:1,y:1,terrain:"plain",revealed:true,developed:false,resourceId:null};
const powerTile={x:2,y:1,terrain:"plain",revealed:true,developed:false,resourceId:null};
state.tiles["1,1"]=hqTile;
state.tiles["2,1"]=powerTile;
assert.equal(development.place(state,hqTile,"headquarters").ok,true);
assert.equal(development.place(state,powerTile,"power").ok,true);
colonyService.totals(state);
const network=colonyService.headquartersNetwork(state,{fuelStock:inventory.amount(state,"fuel")});
assert.equal(network.primaryId,"1,1");
assert.equal(network.rows.find(row=>row.id==="1,1").staffed,true);
gate=expansion.canLaunch(state,ship.id);
assert.equal(gate.ok,true);
assert.equal(expansion.launch(state,ship.id).ok,true);
assert.equal(state.colony.commandHandoverComplete,true);

const legacy=JSON.parse(JSON.stringify(state));
legacy.version=14;
legacy.colony.commandHandoverComplete=false;
const migrated=normalizeState(legacy);
assert.equal(migrated.version,15);
assert.equal(migrated.colony.commandHandoverComplete,true,"pre-A08a colonies migrate complete");
assert.equal(typeof migrated.colony.primaryHeadquartersId,"string");

const powerState=createGameState(contracts.first());
const powerInventory=new InventoryService(resources);
const powerColony=new ColonyService(powerInventory,{});
const powerLand=new LandService();
const powerDevelopment=new DevelopmentService(powerInventory,powerLand,powerColony);
for(const type of ["build","ore","fuel"])powerInventory.store(powerState,type,type==="build"?"fiber":type==="ore"?"surface-iron":"biomass","Test",100000,500);
powerState.tiles["3,3"]={x:3,y:3,terrain:"plain",revealed:true,resourceId:null,developed:false};
assert.equal(powerDevelopment.place(powerState,powerState.tiles["3,3"],"power").ok,true);
powerColony.totals(powerState);
const full=powerColony.powerNetwork(powerState,{fuelStock:100000});
const empty=powerColony.powerNetwork(powerState,{fuelStock:0});
assert.ok(full.onlineCapacity>0);
assert.equal(empty.fuelLimitedGeneration,0);
assert.equal(full.fullFuelBurn,full.onlineCapacity*.1);
console.log("A08a Headquarters gate, migration and Power timing regression coverage passed");