import assert from "node:assert/strict";
import fs from "node:fs";
const read=path=>fs.readFileSync(new URL(`../${path}`,import.meta.url),"utf8");

const pkg=JSON.parse(read("package.json")),index=read("index.html"),legacy=read("js/ui/ui-controller-v564.js"),help570=read("js/ui/ui-controller-v570.js"),help580=read("js/ui/ui-controller-v580.js"),help581=read("js/ui/ui-controller-v581.js"),help582=read("js/ui/ui-controller-v582.js"),help590=read("js/ui/ui-controller-v590.js"),ui592=read("js/ui/ui-controller-v592.js"),ui598=read("js/ui/ui-controller-v598.js"),ui599=read("js/ui/ui-controller-v599.js"),ui5100=read("js/ui/ui-controller-v5100.js");
assert.equal(pkg.version,"5.9.0");assert.match(index,/ui-controller-v5100\.js\?v=5\.10\.0/);assert.match(ui5100,/extends V599UIController/);assert.match(ui599,/extends V598UIController/);assert.match(ui598,/extends V592UIController/);assert.match(ui592,/extends V590UIController/);assert.match(legacy,/SurvivalUIMixin\.prototype\.help\.call\(this\)/);assert.match(help570,/super\.help\(\)/);assert.match(help580,/super\.help\(\)/);assert.match(help581,/super\.help\(\)/);assert.match(help582,/super\.help\(\)/);assert.match(help590,/super\.help\(\)/);
for(const rule of["Housing, Power and Industry are individual L1–L5 map buildings","five corporation technology families","Mining is the exception","technology limits sophistication, not quantity","Local construction uses physical colony resources, not corporation cash","PUSHED uses 125% staff for 115% output","Every 30 accumulated risk-days triggers a 25% accident check"])assert.ok(help570.includes(rule),`missing retained v5.7 rule: ${rule}`);
for(const rule of["There is one colony map","Tap selects","persistent action bar","main HUD always shows Housing, Power, effective/installed Industry, free workforce, resource stocks and supply days"])assert.ok(help580.includes(rule),`missing v5.8 map-first rule: ${rule}`);
for(const rule of["renewable harvest controls","direct Normal/Pushed/Hard extraction changes"])assert.ok(help581.includes(rule),`missing v5.8 direct-flow rule: ${rule}`);
for(const rule of["Ship arrivals and contract decisions from any colony pause the shared corporation clock","switch you to the affected colony","remain visible until resolved"])assert.ok(help582.includes(rule),`missing v5.8.1 lifecycle rule: ${rule}`);
for(const rule of["no-scroll Sell / Buy / Colonists workflow","Set persistent stock reserves from a surveyed resource on the colony map","ship exports protect those reserves automatically"])assert.ok(help590.includes(rule),`missing v5.9 quick-trade rule: ${rule}`);
for(const retained of["Quality affects economic value, not the basic collection rate","Surveying costs <strong>time, not cash</strong>","Renewable does <strong>not</strong> mean impossible to destroy"])assert.ok(legacy.includes(retained),`missing retained rule: ${retained}`);
console.log("v5.10.0 How to Play rules test passed");
