import assert from "node:assert/strict";
import fs from "node:fs";
const read=path=>fs.readFileSync(new URL(`../${path}`,import.meta.url),"utf8");

const pkg=JSON.parse(read("package.json")),index=read("index.html"),legacy=read("js/ui/ui-controller-v564.js"),help570=read("js/ui/ui-controller-v570.js"),help580=read("js/ui/ui-controller-v580.js"),help581=read("js/ui/operational-controls-ui.js"),help582=read("js/ui/corporate-events-ui.js"),help590=read("js/ui/trade-reserve-ui.js"),buildingUi=read("js/ui/building-details-ui.js"),surveyedResourceUi=read("js/ui/surveyed-resource-ui.js"),resourceDevelopmentUi=read("js/ui/resource-development-ui.js"),ui5100=read("js/ui/ui-controller-v5100.js"),ui511=read("js/ui/ui-controller-v511.js"),playerShipUi=read("js/ui/player-ship-ui.js"),shipNavUi=read("js/ui/ship-navigation-ui.js"),ui5113=read("js/ui/ui-controller-v5113.js");
assert.equal(pkg.version,"5.11.3");assert.match(index,/ui-controller-v5113\.js\?v=5\.11\.3/);for(const semantic of[/operational-controls-ui\.js/,/corporate-events-ui\.js/,/trade-reserve-ui\.js/,/building-details-ui\.js/,/surveyed-resource-ui\.js/,/resource-development-ui\.js/,/player-ship-ui\.js/,/ship-navigation-ui\.js/])assert.match(index,semantic);assert.match(ui5113,/extends V5112UIController/);assert.match(shipNavUi,/from "\.\/player-ship-ui\.js"/);assert.match(ui511,/extends V5100UIController/);assert.match(playerShipUi,/from "\.\/ui-controller-v511\.js\?v=5\.11\.0&legacy=1"/);assert.match(ui5100,/extends V599UIController/);assert.match(resourceDevelopmentUi,/from "\.\/surveyed-resource-ui\.js"/);assert.match(surveyedResourceUi,/from "\.\/building-details-ui\.js"/);assert.match(buildingUi,/from "\.\/trade-reserve-ui\.js"/);assert.match(legacy,/SurvivalUIMixin\.prototype\.help\.call\(this\)/);assert.match(help570,/super\.help\(\)/);assert.match(help580,/super\.help\(\)/);assert.match(help581,/super\.help\(\)/);assert.match(help582,/super\.help\(\)/);assert.match(help590,/super\.help\(\)/);
for(const rule of["Housing, Power and Industry are individual L1–L5 map buildings","five corporation technology families","Mining is the exception","technology limits sophistication, not quantity","Local construction uses physical colony resources, not corporation cash","PUSHED uses 125% staff for 115% output","Every 30 accumulated risk-days triggers a 25% accident check"])assert.ok(help570.includes(rule),`missing retained v5.7 rule: ${rule}`);
for(const rule of["There is one colony map","Tap selects","persistent action bar","main HUD always shows Housing, Power, effective/installed Industry, free workforce, resource stocks and supply days"])assert.ok(help580.includes(rule),`missing v5.8 map-first rule: ${rule}`);
for(const rule of["renewable harvest controls","direct Normal/Pushed/Hard extraction changes"])assert.ok(help581.includes(rule),`missing v5.8 direct-flow rule: ${rule}`);
for(const rule of["Ship arrivals and contract decisions from any colony pause the shared corporation clock","switch you to the affected colony","remain visible until resolved"])assert.ok(help582.includes(rule),`missing v5.8.1 lifecycle rule: ${rule}`);
for(const rule of["no-scroll Sell / Buy / Colonists workflow","Set persistent stock reserves from a surveyed resource on the colony map","ship exports protect those reserves automatically"])assert.ok(help590.includes(rule),`missing v5.9 quick-trade rule: ${rule}`);
for(const rule of["starMapCanvas","BUILD + LAUNCH SURVEY PROBE","SHIP FUEL TANK","Koplin Corporate Home"])assert.ok(ui511.includes(rule),`missing v5.11 expansion UI marker: ${rule}`);
for(const rule of["TECHNOLOGY","STAR MAP","COLONIES","CARGO BAY","COLONY SUMMARY","CORPORATION"])assert.ok(playerShipUi.includes(rule),`missing landed-player-ship action: ${rule}`);
for(const rule of["starSystemDetailMarkup","exp-planet-table","full-screen-panel","demolitionPanel","ship-panel-back"])assert.ok(shipNavUi.includes(rule),`missing ship navigation workflow marker: ${rule}`);
for(const rule of["planetSortHeader","availableCargoCategories","SHIP LOAD","TRANSIT FUEL","TRANSIT FOOD","CARGO FOOD"])assert.ok(ui5113.includes(rule),`missing v5.11.3 preparation marker: ${rule}`);
for(const retained of["Quality affects economic value, not the basic collection rate","Surveying costs <strong>time, not cash</strong>","Renewable does <strong>not</strong> mean impossible to destroy"])assert.ok(legacy.includes(retained),`missing retained rule: ${retained}`);
console.log("v5.11.3 How to Play / expansion presentation rules test passed");
