import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { ContractService } from "../js/domain/contract-service.js";
import { createGameState } from "../js/domain/game-state-runtime.js";
import { ResourceService } from "../js/domain/resource-service.js";
import { InventoryService } from "../js/domain/inventory-service.js";
import { TechnologyService } from "../js/domain/technology-service.js";
import { CollectionService } from "../js/domain/collection-service.js";
import { ColonyService } from "../js/domain/colony-service.js";
import { TradeService } from "../js/domain/trade-service.js";
import { SiteService } from "../js/domain/site-service.js";
import { SimulationEngine } from "../js/domain/simulation-engine.js";

const contracts=new ContractService(),resources=new ResourceService(),inventory=new InventoryService(resources),technology=new TechnologyService(),collection=new CollectionService(resources,inventory,technology),colony=new ColonyService(inventory,technology),trade=new TradeService(resources,inventory),sites=new SiteService(contracts,technology,inventory,colony,resources),engine=new SimulationEngine(resources,technology,collection,trade,inventory,colony);
const state=createGameState(contracts.first());state.pop=1000;state.colony.shipAccommodation={};technology.recompute(state);state.company.cash=1e9;
const tile=(x,type,resourceId,name)=>({x,y:1,revealed:true,developed:true,depleted:false,level:1,type,resourceId,name,quality:100,requiredMiningLevel:1,sustainability:type==="food"||resourceId==="biomass"||resourceId==="fiber"?"renewable":"finite",abundanceLabel:"Established",harvestIntensity:1,depositScale:"Large",reserve:100000,initialReserve:100000});
state.tiles={power:{x:0,y:1,revealed:true,developed:true,name:"Power Plant",development:{kind:"power",level:1}},food:tile(1,"food","fungal","Fungal Shelf"),fuel:tile(2,"fuel","biomass","Biomass"),build1:tile(3,"build","fiber","Construction Fibre"),build2:tile(4,"build","fiber","Construction Fibre"),ore1:tile(5,"ore","surface-iron","Surface Iron Nodules"),ore2:tile(6,"ore","surface-iron","Surface Iron Nodules")};
engine.recalculate(state);
assert.equal(Math.round(state.metrics.industryCapacity),50,"landed ship supplies 50 base Industry");assert.equal(state.metrics.industryLoad,120);assert.equal(state.metrics.industrySurvivalLoad,40);assert.equal(state.metrics.industryCommercialLoad,80);assert.equal(state.metrics.industryCommercialFactor,.125);assert.equal(state.metrics.workforceCommercialFactor,1,"The test population should isolate Industry overload rather than worker shortage");const food=state.tiles.food,ore=state.tiles.ore1;const commandFactor=Math.min(1.15,state.metrics.commandEfficiency||1);assert.ok(Math.abs(resources.collectionRate(state,food)-resources.unthrottledCollectionRate(state,food)*commandFactor)<1e-9);assert.ok(Math.abs(resources.collectionRate(state,ore)-resources.unthrottledCollectionRate(state,ore)*.125*commandFactor)<1e-9);

// Constructing one L1 Industry building raises installed capacity from 50 to 150 and removes the bottleneck.
state.tiles.factory={x:7,y:1,revealed:true,development:{kind:"industry",level:1}};technology.recompute(state);engine.recalculate(state);assert.equal(Math.round(state.metrics.industryInstalled),150);assert.equal(Math.round(state.metrics.industryCapacity),150);assert.equal(state.metrics.industryCommercialFactor,1);
assert.equal(colony.processingBonus(100),0);assert.equal(colony.processingBonus(200),.05);assert.equal(colony.processingBonus(300),.10);assert.equal(colony.processingBonus(500),.20);assert.equal(colony.processingBonus(1000),.35);assert.equal(colony.processingBonus(2000),.50);assert.equal(colony.processingBonus(5000),.50);

const baseGold=trade.sellPrice("ore","gold","excellent");state.metrics.processingBonus=.20;assert.equal(trade.exportPrice(state,"ore","gold","excellent"),baseGold*1.2);state.trade.active=true;state.trade.exportUsed=0;inventory.store(state,"ore","gold","Gold",10,500);const cashBefore=state.company.cash,sale=trade.sellBand(state,"ore:gold","excellent",10);assert.equal(sale.ok,true);assert.equal(sale.revenue,baseGold*1.2*10);assert.equal(state.company.cash,cashBefore+sale.revenue);

// Site upgrades depend on physical installed Industry/Power plus the appropriate deployed colony technology.
const upgradeTile={x:1,y:2,revealed:true,developed:true,depleted:false,level:1,type:"food",resourceId:"fungal",name:"Fungal Shelf",quality:100,requiredMiningLevel:1,sustainability:"renewable",abundanceLabel:"Established",harvestIntensity:1};let req=sites.upgradeRequirements(state,upgradeTile);assert.equal(req.ok,false);assert.match(req.reason,/Food Production Tech L2/);state.colony.tech.food=2;state.tiles.generator={x:8,y:1,revealed:true,development:{kind:"power",level:1}};technology.recompute(state);req=sites.upgradeRequirements(state,upgradeTile);console.log("A08A DEBUG UPGRADE",JSON.stringify(req));assert.equal(req.ok,true,"Food site L2 should unlock with deployed Food Tech L2 plus 100 Industry / 45 Power capacity");upgradeTile.level=2;req=sites.upgradeRequirements(state,upgradeTile);assert.equal(req.ok,false);assert.match(req.reason,/Food Production Tech L3/);assert.equal(colony.siteUpgradeIndustryRequirement(4),550);assert.equal(colony.siteUpgradeIndustryRequirement(5),900);assert.equal(sites.upgradeIndustryRequirement(upgradeTile,4),420);assert.ok(colony.siteIndustryLoad({...ore,level:3})>colony.siteIndustryLoad({...ore,level:1}));

const industryUI=readFileSync(new URL("../js/ui/industry-ui.js",import.meta.url),"utf8"),industryView=readFileSync(new URL("../views/industry-capacity-card.html",import.meta.url),"utf8"),quickTradeUI=readFileSync(new URL("../js/ui/quick-trade-ui.js",import.meta.url),"utf8"),v55TradeUI=readFileSync(new URL("../js/ui/v55-trade-ui.js",import.meta.url),"utf8"),app=readFileSync(new URL("../js/app.js",import.meta.url),"utf8");assert.match(industryUI,/INDUSTRY_CAPACITY_VIEW/);assert.match(industryView,/INDUSTRIAL CAPACITY/);assert.match(industryUI,/Food and Fuel/);assert.match(industryView,/Export processing/);assert.match(quickTradeUI,/quoteSell/);assert.match(quickTradeUI,/sellAllQuote/);assert.match(v55TradeUI,/from "\.\/trade-ui\.js"/);assert.match(app,/new SiteService\(this\.contracts,this\.technology,this\.inventory,this\.colony,this\.resources\)/);assert.equal(state.version,15);
console.log("MineIT canonical Industry capacity + processing test passed",{capacity:state.metrics.industryCapacity,load:state.metrics.industryLoad,processing:state.metrics.processingBonus});
