import assert from "node:assert/strict";
import fs from "node:fs";
const read=p=>fs.readFileSync(new URL(`../${p}`,import.meta.url),"utf8");
const index=read("index.html"),hotfix=read("js/ui/world-view-hotfix.js");
assert.match(index,/world-view-hotfix\.js\?v=5\.5\.6/);
assert.ok(index.indexOf("world-view-hotfix.js?v=5.5.6")<index.indexOf("js/app.js?v=5.5.5"),"Hotfix must load before app.js");
assert.match(hotfix,/#worldShell\{grid-template-rows:30px minmax\(0,1fr\)!important/);
assert.match(hotfix,/#mapFilterHost\{display:none!important\}/);
assert.match(hotfix,/WorldView\.prototype\.resize=function/);
assert.match(hotfix,/this\.canvas\.style\.removeProperty\("width"\)/);
assert.match(hotfix,/this\.canvas\.style\.removeProperty\("height"\)/);
assert.doesNotMatch(hotfix,/this\.canvas\.style\.width\s*=/);
assert.doesNotMatch(hotfix,/this\.canvas\.style\.height\s*=/);
assert.match(hotfix,/WorldView\.prototype\.bindFilters=function/);
assert.match(hotfix,/this\.filterBar\?\.classList\.toggle\("hidden",!filtering\)/);
assert.match(hotfix,/filterBack/);
console.log("v5.5.6 map layout/footer hotfix regression test passed");
