import assert from "node:assert/strict";
import fs from "node:fs";
const read=p=>fs.readFileSync(new URL(`../${p}`,import.meta.url),"utf8");

const index=read("index.html"),app=read("js/app.js"),appCss=read("css/app.css"),worldCss=read("css/world.css"),mapFirstCss=read("css/map-first.css"),resourceDetailsCss=read("css/resource-details.css"),adaptiveBuildingCss=read("css/adaptive-building-details.css"),shipExpansionCss=read("css/ship-expansion.css");

// Stable application-shell ownership.
assert.doesNotMatch(index,/world-view-hotfix/);for(const id of["overlayRoot","contextBar","colonyNavStrip","mapViewHost","world","tradeBtn","menuBtn"])assert.match(index,new RegExp(`id="${id}"`));assert.doesNotMatch(index,/mapFilterHost/);
for(const target of["game-state-runtime","portfolio-service","resource-service","collection-service","colony-service","development-service","site-service","technology-service","simulation-engine","trade-service"])assert.match(app,new RegExp(`domain/${target}\\.js`),`composition root must use ${target}`);
assert.doesNotMatch(app,/map-controls-v58/,"map controls must resolve directly to the canonical module");assert.match(app,/ui\/corporate-trade-ui\.js/);assert.doesNotMatch(app,/quick-trade-ui-v511/,"corporate trade must resolve through the semantic adapter");assert.doesNotMatch(index,/ship-expansion-v5113\.css/,"ShipExpansion styles must be consolidated");assert.doesNotMatch(app,/resource-icons-v\d+/,"resource artwork must resolve directly to the canonical atlas service");assert.match(app,/ui\/world-view-runtime\.js/);assert.doesNotMatch(app,/world-view-v\d+/,"active map must resolve through the semantic world runtime");assert.match(app,/ui\/ship-preparation-ui\.js/);
assert.equal(fs.existsSync(new URL("../css/building-details.css",import.meta.url)),false,"obsolete building details CSS must stay absent");assert.ok(!index.includes("./css/building-details.css"),"application shell must not load obsolete building details CSS");

// Layout responsibilities stay in CSS, not runtime-injected style tags.
assert.match(appCss,/grid-template-rows:auto minmax\(0,1fr\) auto/);assert.doesNotMatch(appCss,/minmax\(160px,1fr\)/);assert.match(mapFirstCss,/#app\{grid-template-rows:auto minmax\(0,1fr\) auto auto\}/);assert.match(worldCss,/#worldShell\{[^}]*grid-template-rows:var\(--map-toolbar-height\) minmax\(0,1fr\)/);assert.match(worldCss,/#overlayRoot\{[^}]*pointer-events:none/);assert.match(worldCss,/#overlayRoot>\.panel,#overlayRoot>\.error-badge\{pointer-events:auto\}/);
assert.match(resourceDetailsCss,/\.resource-detail-hero/);assert.match(adaptiveBuildingCss,/\.adaptive-building-hero/);assert.match(adaptiveBuildingCss,/\.adaptive-building-mode-buttons/);assert.match(adaptiveBuildingCss,/\.adaptive-building-requirements/);assert.match(adaptiveBuildingCss,/\.adaptive-building-actions/);for(const marker of[/\.exp-map-wrap/,/\.exp-ship-strip/,/\.exp-planets/,/touch-action:none/,/\.ship-action-grid/,/\.colony-nav-strip/,/\.full-screen-panel/,/\.exp-planet-table/,/\.demolition-confirm/,/\.danger-close/,/\.compact-ship-prep/,/\.exp-load-overview/,/\.exp-load-meter/,/\.exp-planet-sort/])assert.match(shipExpansionCss,marker);

// Active presentation layer still exposes the important current features during the UI cleanup phase.
const activeWorld=read("js/ui/world-view-runtime.js"),activeUi=read("js/ui/ship-preparation-ui.js"),activeTrade=read("js/ui/corporate-trade-ui.js"),controls=read("js/ui/map-controls.js"),resourceIcons=read("js/ui/resource-icons.js"),baseUi=read("js/ui/ui-controller.js");
assert.match(activeWorld,/onPlayerShipClick/);assert.match(activeWorld,/onSelect/);assert.match(activeWorld,/onFocusChange/);assert.match(activeWorld,/stopImmediatePropagation/);assert.match(activeWorld,/dispose\(\)/);assert.doesNotMatch(activeWorld,/mineit:/);assert.match(activeUi,/planetSortHeader/);assert.match(activeUi,/availableCargoCategories/);assert.match(activeUi,/manifestOverview/);assert.match(activeTrade,/CORP SHIP • TRADE!/);assert.match(activeTrade,/extends QuickTradeUI/);assert.match(controls,/replaceChildren/);assert.match(controls,/map-toolbar-main/);assert.match(controls,/onFocusChange/);assert.doesNotMatch(controls,/mineit:/);assert.match(controls,/dispose\(\)/);assert.match(resourceIcons,/resource-atlas-256\.webp/);assert.match(resourceIcons,/ATLAS_INDEX/);assert.match(resourceIcons,/drawImage\(image,sx,sy,FRAME,FRAME/);assert.match(baseUi,/export function mix/);assert.match(baseUi,/Object\.getPrototypeOf/);
assert.match(app,/onMapFocus:mode=>this\.view\?\.setFocus\(mode\)/);assert.match(app,/onSelect:\(x,y\)=>this\.ui\.selectMapTile\(x,y\)/);assert.match(app,/onPlayerShipClick:\(\)=>this\.ui\.playerShipPanel\(\)/);
for(const [name,source] of Object.entries({activeWorld,activeUi,activeTrade,controls,resourceIcons,baseUi})){assert.doesNotMatch(source,/prototype\.[A-Za-z0-9_$]+\s*=/,`${name} must not monkey-patch prototypes`);assert.doesNotMatch(source,/createElement\(["']style["']\)/,`${name} must not inject runtime styles`);}

console.log("presentation architecture ownership invariants passed");
