import assert from "node:assert/strict";
import fs from "node:fs";
const read=p=>fs.readFileSync(new URL(`../${p}`,import.meta.url),"utf8");

const index=read("index.html"),appCss=read("css/app.css"),worldCss=read("css/world.css"),mapFirstCss=read("css/map-first.css"),buildingCss=read("css/building-details.css"),resourceDetailsCss=read("css/resource-details.css"),view=read("js/ui/world-view-v56.js"),view570=read("js/ui/world-view-v570.js"),view580=read("js/ui/world-view-v580.js"),view591=read("js/ui/world-view-v591.js"),view594=read("js/ui/world-view-v594.js"),resourceIcons597=read("js/ui/resource-icons-v597.js"),controls=read("js/ui/map-controls.js"),controls580=read("js/ui/map-controls-v580.js"),controls581=read("js/ui/map-controls-v581.js"),baseUi=read("js/ui/ui-controller.js"),ui=read("js/ui/ui-controller-v56.js"),cashUi=read("js/ui/ui-controller-v563.js"),helpUi=read("js/ui/ui-controller-v564.js"),ui570=read("js/ui/ui-controller-v570.js"),ui580=read("js/ui/ui-controller-v580.js"),ui581=read("js/ui/ui-controller-v581.js"),ui582=read("js/ui/ui-controller-v582.js"),ui590=read("js/ui/ui-controller-v590.js"),ui592=read("js/ui/ui-controller-v592.js"),ui598=read("js/ui/ui-controller-v598.js"),ui599=read("js/ui/ui-controller-v599.js"),tradeAdapter=read("js/ui/v55-trade-ui-v56.js"),quickTrade=read("js/ui/quick-trade-ui.js");

assert.doesNotMatch(index,/world-view-hotfix/);assert.match(index,/id="overlayRoot"/);assert.match(index,/id="contextBar"/);assert.doesNotMatch(index,/mapFilterHost/);assert.match(index,/type="importmap"/);assert.match(index,/resource-icons-v597\.js\?v=5\.9\.7/);assert.match(index,/world-view-v594\.js\?v=5\.9\.7/);assert.match(index,/ui-controller-v599\.js\?v=5\.9\.9/);assert.match(index,/building-details\.css\?v=5\.9\.2/);assert.match(index,/resource-details\.css\?v=5\.9\.9/);assert.match(index,/map-controls-v581\.js\?v=5\.8\.0/);assert.match(index,/quick-trade-ui\.js\?v=5\.9\.0/);assert.match(index,/trade-quick\.css\?v=5\.9\.0/);
assert.match(appCss,/grid-template-rows:auto minmax\(0,1fr\) auto/);assert.doesNotMatch(appCss,/minmax\(160px,1fr\)/);assert.match(mapFirstCss,/#app\{grid-template-rows:auto minmax\(0,1fr\) auto auto\}/);assert.match(worldCss,/#worldShell\{[^}]*grid-template-rows:var\(--map-toolbar-height\) minmax\(0,1fr\)/);assert.match(worldCss,/#overlayRoot\{[^}]*pointer-events:none/);assert.match(worldCss,/#overlayRoot>\.panel,#overlayRoot>\.error-badge\{pointer-events:auto\}/);assert.match(buildingCss,/\.building-detail-hero/);assert.match(buildingCss,/\.building-art-frame img/);assert.match(buildingCss,/\.building-detail-actions/);assert.match(resourceDetailsCss,/\.resource-detail-hero/);assert.match(resourceDetailsCss,/\.resource-detail-facts/);assert.match(resourceDetailsCss,/\.resource-requirements/);assert.match(resourceDetailsCss,/\.resource-detail-actions/);assert.match(resourceDetailsCss,/background-size:800% 500%/);
assert.match(view,/extends CanvasWorldView/);assert.match(view,/new MapControls/);assert.match(view,/world-view\.js\?v=5\.5\.5&legacy=1/);assert.match(view,/canvas\.style\.removeProperty\("width"\)/);assert.match(view,/canvas\.style\.removeProperty\("height"\)/);assert.doesNotMatch(view,/prototype\./);assert.doesNotMatch(view,/createElement\("style"\)/);
assert.match(view570,/extends LegacyWorldView/);assert.match(view580,/extends LegacyWorldView/);assert.match(view580,/mineit:tile-selected/);assert.match(view591,/extends V580WorldView/);assert.match(view591,/world-view-v580\.js\?v=5\.8\.0&legacy=1/);assert.match(view591,/land-art-v591\.js\?v=5\.9\.1/);assert.match(view594,/extends V593WorldView/);assert.match(view594,/drawResourceOverlay/);assert.doesNotMatch(view594,/resourceCutout/);assert.match(resourceIcons597,/extends LegacyResourceIcons/);assert.match(resourceIcons597,/resource-atlas-256\.webp\?v=5\.9\.7/);assert.doesNotMatch(view570,/prototype\.[A-Za-z0-9_$]+\s*=/);assert.doesNotMatch(view580,/prototype\.[A-Za-z0-9_$]+\s*=/);assert.doesNotMatch(view591,/prototype\.[A-Za-z0-9_$]+\s*=/);assert.doesNotMatch(view594,/prototype\.[A-Za-z0-9_$]+\s*=/);assert.doesNotMatch(view580,/createElement\("style"\)/);assert.doesNotMatch(view591,/createElement\("style"\)/);assert.doesNotMatch(view594,/createElement\("style"\)/);
assert.match(controls,/class MapControls/);assert.match(controls,/replaceChildren\(\)/);assert.match(controls,/map-toolbar-main/);assert.match(controls580,/class MapControls/);assert.match(controls580,/replaceChildren\(\)/);assert.match(controls580,/map-toolbar-main/);assert.match(controls580,/mineit:map-focus/);assert.match(controls581,/class MapControls extends V580MapControls/);assert.doesNotMatch(controls581,/prototype\.[A-Za-z0-9_$]+\s*=/);assert.doesNotMatch(controls581,/createElement\("style"\)/);
assert.match(baseUi,/export function mix/);assert.match(baseUi,/Object\.getPrototypeOf/);assert.doesNotMatch(baseUi,/prototype\.[A-Za-z0-9_$]+\s*=/);assert.match(ui,/class UIController extends LegacyUIController/);assert.match(ui,/ui-controller\.js\?v=5\.6\.2&legacy=1/);assert.match(ui,/addEventListener\("click"/);assert.match(ui,/stopImmediatePropagation\(\)/);assert.match(ui,/setSpeed\(next\)/);assert.match(cashUi,/class UIController extends V56UIController/);assert.doesNotMatch(cashUi,/prototype\.[A-Za-z0-9_$]+\s*=/);assert.doesNotMatch(cashUi,/createElement\("style"\)/);assert.match(helpUi,/class UIController extends V563UIController/);assert.match(helpUi,/SurvivalUIMixin\.prototype\.help\.call\(this\)/);assert.doesNotMatch(helpUi,/prototype\.[A-Za-z0-9_$]+\s*=/);assert.doesNotMatch(helpUi,/createElement\("style"\)/);
assert.match(ui570,/class UIController extends LegacyUIController/);assert.match(ui580,/class UIController extends LegacyUIController/);assert.match(ui580,/ui-controller-v570\.js\?v=5\.7\.0&legacy=1/);assert.match(ui581,/class UIController extends V580UIController/);assert.match(ui581,/ui-controller-v580\.js\?v=5\.8\.0&legacy=1/);assert.match(ui582,/class UIController extends V581UIController/);assert.match(ui582,/ui-controller-v581\.js\?v=5\.8\.0&legacy=1/);assert.match(ui590,/class UIController extends V582UIController/);assert.match(ui590,/ui-controller-v582\.js\?v=5\.8\.1&legacy=1/);assert.match(ui592,/class UIController extends V590UIController/);assert.match(ui592,/ui-controller-v590\.js\?v=5\.9\.0&legacy=1/);assert.match(ui592,/developmentOriginalPath/);assert.match(ui598,/class UIController extends V592UIController/);assert.match(ui598,/ui-controller-v592\.js\?v=5\.9\.2&legacy=1/);assert.match(ui598,/resourceDetailHero\(tile\)/);assert.match(ui599,/class UIController extends V598UIController/);assert.match(ui599,/ui-controller-v598\.js\?v=5\.9\.8&legacy=1/);assert.match(ui599,/renderUndevelopedResource\(tile\)/);for(const source of[ui570,ui580,ui581,ui582,ui590,ui592,ui598,ui599]){assert.doesNotMatch(source,/prototype\.[A-Za-z0-9_$]+\s*=/);assert.doesNotMatch(source,/createElement\("style"\)/);}
assert.match(tradeAdapter,/v55-trade-ui\.js\?v=5\.5\.5&legacy=1/);assert.match(tradeAdapter,/button\.onclick=null/);assert.match(tradeAdapter,/bindSpeedInputs/);assert.match(quickTrade,/extends BaseTradeUI/);assert.match(quickTrade,/v55-trade-ui-v56\.js\?v=5\.6\.0/);assert.doesNotMatch(quickTrade,/createElement\("style"\)/);
console.log("presentation architecture ownership test passed");
