import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { CONFIG } from "../js/core/config.js";
import { ContractService } from "../js/domain/contract-service.js";
import { createGameState, normalizeState } from "../js/domain/game-state-runtime.js";
import { ResourceService } from "../js/domain/resource-service.js";
import { InventoryService } from "../js/domain/inventory-service.js";
import { TechnologyService } from "../js/domain/technology-service.js";
import { CollectionService } from "../js/domain/collection-service.js";
import { ColonyService } from "../js/domain/colony-service.js";
import { TradeService } from "../js/domain/trade-service.js";
import { SimulationEngine } from "../js/domain/simulation-engine.js";

const contracts=new ContractService(),resources=new ResourceService(),inventory=new InventoryService(resources),tech=new TechnologyService(),collection=new CollectionService(resources,inventory,tech),colony=new ColonyService(inventory,tech),trade=new TradeService(resources,inventory),engine=new SimulationEngine(resources,tech,collection,trade,inventory,colony);
const fresh=()=>{const state=createGameState(contracts.first());tech.recompute(state);engine.recalculate(state);return state;},near=(actual,expected,tolerance=2)=>assert.ok(Math.abs(actual-expected)<=tolerance,`${actual} should be within ${tolerance} of ${expected}`);
const state=fresh();assert.equal(state.version,9);assert.equal(inventory.amount(state,"food"),CONFIG.START_FOOD);assert.equal(inventory.amount(state,"build"),CONFIG.START_BUILD);assert.equal(inventory.amount(state,"fuel"),CONFIG.START_FUEL);assert.equal(inventory.amount(state,"ore"),CONFIG.START_ORE);assert.equal(resources.baseOutput(100),resources.baseOutput(10000),"Quality no longer controls extraction throughput");assert.ok(state.metrics.foodDays>80&&state.metrics.foodDays<100,"Starter Food should provide roughly three months with no production");assert.equal(state.contract.supportLoad,1);const barren=contracts.make(contracts.archetype({arch:"barren"}),3,0);assert.equal(barren.supportLoad,1.5);

// Industry staffing is derived from installed physical Industry, not an aggregate level counter.
state.tiles.industry={x:8,y:8,revealed:true,development:{kind:"industry",level:2}};tech.recompute(state);const installed=state.metrics.industryInstalled,required=colony.industryPopulationRequirement(state);assert.equal(installed,280);assert.equal(required,224);state.pop=112;assert.equal(colony.industryPopulationFactor(state),.5);state.pop=224;assert.equal(colony.industryPopulationFactor(state),1);

const emergency=fresh();emergency.tiles={food:{x:1,y:1,revealed:true,developed:true,depleted:false,level:1,type:"food",resourceId:"fungal",name:"Fungal Shelf",quality:100,requiredMiningLevel:1,sustainability:"renewable",abundanceLabel:"Established",harvestIntensity:1},fuel:{x:2,y:1,revealed:true,developed:true,depleted:false,level:1,type:"fuel",resourceId:"biomass",name:"Biomass",quality:100,requiredMiningLevel:1,sustainability:"renewable",abundanceLabel:"Established",harvestIntensity:1},ore:{x:3,y:1,revealed:true,developed:true,depleted:false,level:1,type:"ore",resourceId:"surface-iron",name:"Surface Iron Nodules",quality:100,requiredMiningLevel:1,sustainability:"finite",depositScale:"Large",reserve:10000,initialReserve:10000},build:{x:4,y:1,revealed:true,developed:true,depleted:false,level:1,type:"build",resourceId:"fiber",name:"Construction Fibre",quality:100,requiredMiningLevel:1,sustainability:"renewable",abundanceLabel:"Established",harvestIntensity:1}};const normalDemand=colony.demand(emergency);emergency.colony.emergencyMode=true;const emergencySites=collection.activeSites(emergency),emergencyDemand=colony.demand(emergency);assert.deepEqual(emergencySites.map(t=>t.type).sort(),["food","fuel"]);assert.equal(emergencyDemand.oreDemand,0);assert.ok(emergencyDemand.powerDemand<normalDemand.powerDemand);engine.recalculate(emergency);assert.equal(emergency.metrics.industry,0);

// Passenger capacity is constrained by physical housing.
const ship=fresh();ship.company.cash=1e9;ship.company.tech.housing=2;ship.tiles.house={x:7,y:7,revealed:true,development:{kind:"housing",level:2}};tech.recompute(ship);assert.equal(ship.colony.housingCapacity,540);assert.equal(trade.arrive(ship),true);const transfer=trade.transferColonists(ship,250);assert.equal(transfer.ok,true);assert.equal(Math.round(ship.pop),370);assert.equal(trade.passengerRemaining(ship),0);assert.equal(trade.transferColonists(ship,50).ok,false);const gold=trade.catalog().find(x=>x.resourceId==="gold"),importResult=trade.buy(ship,gold.key,5000);assert.equal(importResult.ok,true);assert.equal(importResult.qty,CONFIG.TRADE_BASE_CARGO);assert.equal(trade.cargoRemaining(ship),0);

// Zero Food removes the workforce immediately but Food-driven deaths wait for 30 complete starvation days.
const starving=fresh();starving.inventory={};starving.pop=5;inventory.store(starving,"fuel","biomass","Biomass",10000);engine.recalculate(starving);assert.equal(starving.colony.foodStarvationDays,0);for(let day=1;day<=30;day++){const result=engine.tick(starving);assert.equal(starving.pop,5,`Food starvation must not kill colonists during grace day ${day}`);assert.equal(result.deaths,0);assert.equal(starving.colony.foodStarvationDays,day);assert.equal(colony.workforceAvailable(starving),0,"zero Food must remove operational workforce immediately");}const day31=engine.tick(starving);assert.ok(day31.deaths>0,"Food-driven mortality begins after 30 complete zero-Food days");let days=31;while(starving.status!=="dead"&&days<300){engine.tick(starving);days++;}assert.equal(starving.status,"dead");assert.equal(starving.pop,0);assert.ok(days<240);assert.equal(starving.contract.ended,true);engine.recalculate(starving);assert.equal(starving.metrics.operatingCost,0);assert.equal(collection.activeSites(starving).length,0);

// Population changes only through explicit transfers/events; stable colonies do not grow naturally.
const staticPopulation=fresh();inventory.store(staticPopulation,"food","fungal","Fungal Shelf",100000);inventory.store(staticPopulation,"fuel","biomass","Biomass",100000);const startingPopulation=staticPopulation.pop;for(let day=0;day<400;day++)engine.tick(staticPopulation);assert.equal(staticPopulation.pop,startingPopulation,"natural population growth must remain disabled");

const legacy=fresh();legacy.version=6;legacy.contract.goals.food=620;delete legacy.colony.emergencyMode;delete legacy.trade.cargoUsed;delete legacy.trade.passengersUsed;legacy.tiles["9,9"]={x:9,y:9,revealed:true,developed:false,depleted:false,level:0,type:"ore",resourceId:"iron",name:"Iron Ore",quality:100,resourceMult:1,requiredMiningLevel:3,sustainability:"finite",reserve:50000,initialReserve:100000,depositScale:"Large"};legacy.portfolio.colonies[0].data.tiles={"8,8":{x:8,y:8,revealed:true,developed:false,depleted:false,level:0,type:"ore",resourceId:"iron",name:"Iron Ore",quality:100,resourceMult:1,requiredMiningLevel:3,sustainability:"finite",reserve:100000,initialReserve:200000,depositScale:"Huge"}};const oldOutput=8+7*Math.pow(100,.52),largeScale=(CONFIG.SITE_OUTPUT_LEVELS[0]*1.05)/oldOutput,hugeScale=(CONFIG.SITE_OUTPUT_LEVELS[0]*1.20)/oldOutput;normalizeState(legacy);assert.equal(legacy.version,9);assert.equal(legacy.contract.goals.food,124);assert.equal(legacy.colony.emergencyMode,false);assert.equal(legacy.trade.cargoUsed,0);assert.equal(legacy.trade.exportUsed,0);assert.equal(legacy.trade.passengersUsed,0);near(legacy.tiles["9,9"].initialReserve,Math.round(100000*largeScale));near(legacy.tiles["9,9"].reserve,Math.round(50000*largeScale));near(legacy.portfolio.colonies[0].data.tiles["8,8"].initialReserve,Math.round(200000*hugeScale));
const appSource=readFileSync(new URL("../js/app.js",import.meta.url),"utf8"),tradeUI=readFileSync(new URL("../js/ui/quick-trade-ui.js",import.meta.url),"utf8"),tradeShell=readFileSync(new URL("../views/quick-trade-shell.html",import.meta.url),"utf8"),colonistView=readFileSync(new URL("../views/quick-trade-colonists.html",import.meta.url),"utf8"),landUI=readFileSync(new URL("../js/ui/land-ui.js",import.meta.url),"utf8"),colonyLandView=readFileSync(new URL("../views/colony-land-panel.html",import.meta.url),"utf8"),survivalManual=readFileSync(new URL("../views/survival-manual.html",import.meta.url),"utf8"),simulationSource=readFileSync(new URL("../js/domain/simulation-engine.js",import.meta.url),"utf8");assert.match(appSource,/backgroundDeaths/);assert.match(appSource,/gameOver/);assert.match(colonistView,/COLONIST TRANSFER/);assert.match(tradeShell,/trade-quick-summary/);assert.match(tradeUI,/this\.trade\.cargoRemaining\(this\.state\)/);assert.match(landUI,/emergencyMode/);assert.match(colonyLandView,/data-emergency/);assert.match(colonyLandView,/Commercial staffing/);assert.match(survivalManual,/Survival, shortages &amp; colony death/);assert.doesNotMatch(simulationSource,/GROWTH_RATE|naturalGrowth|growthRate/);
console.log("MineIT canonical colony survival rebalance test passed",{deathDays:days,foodRunway:state.metrics.foodDays,cargo:CONFIG.TRADE_BASE_CARGO,passengers:CONFIG.TRADE_PASSENGER_CAPACITY});
