import { formatMoney,formatNumber } from "../core/utils.js";
import { loadViewTemplate } from "../core/view-template.js";
import { reputationLevel } from "../domain/reputation-service.js";

const CATALOG_VIEW="./views/conglomerate-buyers.html",COLLECTION_VIEW="./views/buyer-collection-event.html",QUALITY_ORDER=["common","good","excellent","exceptional","rare","extraordinary"];
const qualityRank=key=>Math.max(0,QUALITY_ORDER.indexOf(key));
const absoluteDate=value=>{const day=Math.max(1,Math.floor(Number(value)||1));return`Y${Math.floor((day-1)/360)+1} D${(day-1)%360+1}`;};
const initials=name=>String(name||"?").split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]?.toUpperCase()).join("")||"?";
const compact=value=>{const n=Number(value)||0;if(Math.abs(n)>=1e6)return`${(n/1e6).toFixed(n%1e6?1:0)}m`;if(Math.abs(n)>=1e3)return`${(n/1e3).toFixed(n%1e3?1:0)}k`;return Math.round(n).toString();};
const rate=value=>{const n=Number(value)||0;return n>=1?n.toFixed(2):n>=.1?n.toFixed(2):n.toFixed(3);};
const happinessBand=value=>value<=33?{name:"RED",className:"bad"}:value<=66?{name:"AMBER",className:"warn"}:{name:"GREEN",className:"good"};
const historyLabel=result=>({full:"Full shipment","minor-partial":"75–99% partial","major-partial":"50–74% partial",missed:"Missed shipment","player-cancelled":"Player cancelled"}[result]||String(result||"Event"));

/** Approved Stage 8 buyer catalogue/profile and collection-event presentation. Gameplay mutation stays in BuyerService via app callbacks. */
export class BuyerUI{
  constructor({state,buyers,ui,diagnostics,onEnterContract,onCancelContract,onTransfer,onWait,onMiss}){Object.assign(this,{state,buyers,ui,diagnostics,onEnterContract,onCancelContract,onTransfer,onWait,onMiss});this.catalogRevision=0;this.collectionRevision=0;this.filters={status:"all",resource:"",quality:"",load:"",price:"",frequency:"",reputation:"",sort:"rep"};ui.buyerUI=this;}
  dispose(){this.catalogRevision++;this.collectionRevision++;if(this.ui?.buyerUI===this)this.ui.buyerUI=null;}
  fragment(source){return document.createRange().createContextualFragment(source);}
  text(root,selector,value){const node=root?.querySelector(selector);if(node)node.textContent=String(value??"");return node;}
  qualityLabel(key){return this.buyers.resources.qualityBandByKey(key)?.label||String(key||"");}
  profileView(offerId){const offer=this.buyers.offer(this.state,offerId);return offer?this.buyers.offerView(this.state,offer):null;}
  setImage(img,fallback,path,label){if(!img||!fallback)return;fallback.textContent=initials(label);fallback.hidden=true;img.hidden=false;img.src=path;img.onerror=()=>{img.hidden=true;fallback.hidden=false;};img.onload=()=>{fallback.hidden=true;img.hidden=false;};}

  async openCatalog(){
    const revision=++this.catalogRevision;
    try{
      const source=await loadViewTemplate(CATALOG_VIEW);if(revision!==this.catalogRevision)return false;
      this.ui.open("Conglomerate Buyers Service",source);const root=this.ui.modal.querySelector("[data-buyers-screen]");if(!root)return false;
      this.populateResourceFilter(root);this.bindCatalog(root);this.renderCatalog(root);return true;
    }catch(error){if(revision===this.catalogRevision){this.diagnostics?.error?.("buyer catalogue template failed",error);this.ui.toast("Unable to open the Conglomerate Buyers Service.");}return false;}
  }
  closeCatalog(){this.catalogRevision++;this.ui.modal.classList.add("hidden");}
  populateResourceFilter(root){const select=root.querySelector('[data-buyer-filter="resource"]');if(!select||select.options.length>1)return;const names=[...new Set(this.buyers.catalog(this.state).map(row=>row.resourceName))].sort((a,b)=>a.localeCompare(b));for(const name of names){const option=document.createElement("option");option.value=name;option.textContent=name;select.append(option);}}
  bindCatalog(root){
    root.querySelector("[data-buyers-close]").onclick=()=>this.closeCatalog();
    for(const select of root.querySelectorAll("[data-buyer-filter]")){const key=select.dataset.buyerFilter;select.value=this.filters[key]??select.value;select.onchange=()=>{this.filters[key]=select.value;this.renderCatalog(root);};}
    root.querySelector("[data-profile-close]").onclick=()=>root.querySelector("[data-buyer-profile]").classList.add("hidden");
  }
  matches(row){const f=this.filters;if(f.status!=="all"&&row.status!==f.status)return false;if(f.resource&&row.resourceName!==f.resource)return false;if(f.quality&&row.minQuality!==f.quality)return false;if(f.load==="small"&&row.quantity>25000)return false;if(f.load==="mid"&&(row.quantity<=25000||row.quantity>75000))return false;if(f.load==="large"&&row.quantity<=75000)return false;if(f.price==="low"&&row.unitRate>=.25)return false;if(f.price==="mid"&&(row.unitRate<.25||row.unitRate>=1))return false;if(f.price==="high"&&row.unitRate<1)return false;if(f.frequency==="fast"&&row.intervalDays>35)return false;if(f.frequency==="mid"&&(row.intervalDays<=35||row.intervalDays>60))return false;if(f.frequency==="slow"&&row.intervalDays<=60)return false;if(f.reputation==="eligible"&&row.status==="locked")return false;if(f.reputation==="0"&&(row.minRep<0||row.minRep>=10))return false;if(f.reputation==="10"&&(row.minRep<10||row.minRep>=25))return false;if(f.reputation==="25"&&row.minRep<25)return false;return true;}
  sortRows(rows){const key=this.filters.sort;return rows.sort((a,b)=>{if(key==="rep")return a.minRep-b.minRep;if(key==="repDesc")return b.minRep-a.minRep;if(key==="price")return a.unitRate-b.unitRate;if(key==="priceDesc")return b.unitRate-a.unitRate;if(key==="load")return a.quantity-b.quantity;if(key==="loadDesc")return b.quantity-a.quantity;if(key==="freq")return a.intervalDays-b.intervalDays;if(key==="freqDesc")return b.intervalDays-a.intervalDays;if(key==="quality")return qualityRank(a.minQuality)-qualityRank(b.minQuality);if(key==="resource")return a.resourceName.localeCompare(b.resourceName);return 0;});}
  renderCatalog(root=this.ui.modal.querySelector("[data-buyers-screen]")){
    if(!root)return;const rep=Number(this.state.company.rep)||0,level=reputationLevel(rep);this.text(root,"[data-buyers-rep]",rep.toFixed(2));this.text(root,"[data-buyers-rep-level]",level.name.toUpperCase());
    const all=this.buyers.catalog(this.state),rows=this.sortRows(all.filter(row=>this.matches(row))),host=root.querySelector("[data-buyer-rows]"),template=root.querySelector("[data-buyer-row-template]"),fragment=document.createDocumentFragment();
    for(const row of rows){const item=template.content.firstElementChild.cloneNode(true),button=item.querySelector("[data-buyer-action]");item.classList.toggle("current",row.status==="current");item.classList.toggle("locked",row.status==="locked");button.dataset.offerId=row.id;if(row.status==="current"){button.textContent="VIEW";button.classList.add("view");button.onclick=()=>this.openProfile(root,this.profileView(row.id));}else if(row.status==="available"){button.textContent="CONTACT";button.classList.add("contact");button.onclick=()=>this.openProfile(root,this.profileView(row.id));}else{button.textContent="REP LOCKED";button.classList.add("locked");button.disabled=true;}this.text(item,"[data-buyer-name]",row.buyer.name);this.text(item,"[data-buyer-company]",row.buyer.company);this.text(item,"[data-buyer-resource]",row.resourceName);this.text(item,"[data-buyer-quality]",this.qualityLabel(row.minQuality)[0]?.toUpperCase()||"—");this.text(item,"[data-buyer-load]",compact(row.quantity));this.text(item,"[data-buyer-price]",rate(row.unitRate));this.text(item,"[data-buyer-every]",`${row.intervalDays}d`);this.text(item,"[data-buyer-requirement]",row.minRep.toFixed(row.minRep%1?1:0));fragment.append(item);}host.replaceChildren(fragment);this.text(root,"[data-buyer-count]",`SHOWING ${rows.length.toLocaleString()} / ${all.length.toLocaleString()}`);
  }
  openProfile(root,view){if(!view)return;const overlay=root.querySelector("[data-buyer-profile]"),buyer=view.buyer,ship=view.ship,contract=view.contract,relationship=view.relationship,current=!!contract;this.text(overlay,"[data-profile-name]",buyer.name);this.text(overlay,"[data-profile-role]",buyer.role);this.text(overlay,"[data-profile-company]",buyer.company);this.text(overlay,"[data-profile-business]",`${buyer.businessType} • ${buyer.tier} buyer`);this.text(overlay,"[data-profile-ship]",`${buyer.shipName} • ${ship.name}`);this.text(overlay,"[data-profile-ship-description]",`${ship.description} Cargo capacity ${formatNumber(ship.capacity)}.`);this.text(overlay,"[data-profile-resource]",view.resourceName);this.text(overlay,"[data-profile-quality]",this.qualityLabel(view.minQuality));this.text(overlay,"[data-profile-load]",formatNumber(view.quantity));this.text(overlay,"[data-profile-price]",`£${rate(view.unitRate)}`);this.text(overlay,"[data-profile-value]",formatMoney(view.fullValue));this.text(overlay,"[data-profile-every]",`Every ${view.intervalDays}d`);this.text(overlay,"[data-profile-rep]",view.minRep.toFixed(2));this.text(overlay,"[data-profile-home]",buyer.home);this.setImage(overlay.querySelector("[data-profile-portrait]"),overlay.querySelector("[data-profile-portrait-fallback]"),`./assets/art/buyers/${view.portraitKey}`,buyer.name);
    const primary=overlay.querySelector("[data-profile-primary]");primary.onclick=null;if(current){primary.textContent="CURRENT CONTRACT";primary.disabled=true;}else if(view.status==="available"){primary.textContent="ENTER CONTRACT";primary.disabled=false;primary.onclick=()=>{const result=this.onEnterContract?.(view.id);if(!result?.ok){this.ui.toast(result?.reason||"Unable to enter buyer contract.");return;}this.ui.toast(`${buyer.company} contract established.`);this.renderCatalog(root);this.openProfile(root,this.profileView(view.id));};}else{primary.textContent="REP LOCKED";primary.disabled=true;}
    const currentSection=overlay.querySelector("[data-profile-current]");currentSection.classList.toggle("hidden",!current);if(current)this.renderCurrentProfile(currentSection,view);overlay.classList.remove("hidden");
  }
  renderCurrentProfile(section,view){const contract=view.contract,r=view.relationship,band=happinessBand(r.happiness),projection=this.buyers.projection(this.state,contract.id);this.text(section,"[data-profile-happiness]",Math.round(r.happiness));this.text(section,"[data-profile-happiness-band]",`${band.name} • BUYER ${band.name==="GREEN"?"HAPPY":band.name==="AMBER"?"CAUTIOUS":"AT RISK"}`);this.text(section,"[data-profile-next]",`Next collection ${absoluteDate(contract.nextDueAbsoluteDay)} • ${formatMoney(r.totalRevenue)} earned`);this.text(section,"[data-profile-stock]",formatNumber(projection?.stock||0));this.text(section,"[data-profile-counts]",`${r.fullDeliveries} / ${r.partialDeliveries} / ${r.lateDeliveries} / ${r.missedDeliveries}`);this.text(section,"[data-profile-units]",formatNumber(r.totalUnits));this.text(section,"[data-profile-earned]",formatMoney(r.totalRevenue));this.text(section,"[data-profile-started]",absoluteDate(contract.startedAbsoluteDay));this.text(section,"[data-profile-current-ship]",contract.shipName);section.classList.remove("good","warn","bad");section.classList.add(band.className);this.renderHistory(section,r.history);const cancel=section.querySelector("[data-profile-cancel]");cancel.disabled=this.buyers.shipWaiting(contract);cancel.textContent=cancel.disabled?"CANNOT CANCEL • COLLECTION SHIP WAITING":"CANCEL CONTRACT";cancel.onclick=()=>{if(!confirm("Cancel this buyer contract? This applies -5 buyer happiness and -0.5 global reputation."))return;const result=this.onCancelContract?.(contract.id);if(!result?.ok){this.ui.toast(result?.reason||"Unable to cancel buyer contract.");return;}this.ui.toast("Buyer contract cancelled.");this.renderCatalog(this.ui.modal.querySelector("[data-buyers-screen]"));this.ui.modal.querySelector("[data-buyer-profile]")?.classList.add("hidden");};}
  renderHistory(section,history){const host=section.querySelector("[data-profile-history]"),template=section.querySelector("[data-profile-history-template]"),fragment=document.createDocumentFragment();for(const event of[...(history||[])].slice(-10).reverse()){const row=template.content.firstElementChild.cloneNode(true);this.text(row,"[data-history-date]",absoluteDate(event.absoluteDay));this.text(row,"[data-history-result]",historyLabel(event.result));this.text(row,"[data-history-change]",`${event.happinessChange>0?"+":""}${event.happinessChange}`);fragment.append(row);}host.replaceChildren(fragment);}

  async openCollection(contractId){
    const revision=++this.collectionRevision;
    try{const source=await loadViewTemplate(COLLECTION_VIEW);if(revision!==this.collectionRevision)return false;const snapshot=this.buyers.snapshotContract(this.state,contractId);if(!snapshot||snapshot.contract.status!=="active"||!this.buyers.shipWaiting(snapshot.contract))return false;this.ui.open("Buyer Collection Event",source);const root=this.ui.modal.querySelector("[data-buyer-collection-screen]");if(!root)return false;this.bindCollection(root,contractId);this.renderCollection(root,contractId);return true;}
    catch(error){if(revision===this.collectionRevision){this.diagnostics?.error?.("buyer collection template failed",error);this.ui.toast("Unable to open the buyer collection event.");}return false;}
  }
  bindCollection(root,contractId){root.querySelector("[data-collection-dismiss]").onclick=()=>this.ui.toast("A buyer collection decision is required before time can resume.");root.querySelector("[data-collection-wait]").onclick=()=>{const projection=this.buyers.projection(this.state,contractId),final=projection?.daysLate>=15||projection?.contract?.ship?.attemptIndex>=3,result=final?this.onMiss?.(contractId):this.onWait?.(contractId);if(!result?.ok){this.ui.toast(result?.reason||"Unable to resolve collection action.");return;}this.collectionRevision++;this.ui.modal.classList.add("hidden");};root.querySelector("[data-collection-transfer]").onclick=()=>{const result=this.onTransfer?.(contractId);if(!result?.ok){this.ui.toast(result?.reason||"Unable to transfer buyer stock.");return;}this.collectionRevision++;this.ui.modal.classList.add("hidden");};}
  renderCollection(root,contractId){const snapshot=this.buyers.snapshotContract(this.state,contractId);if(!snapshot)return;const {contract,buyer,ship,projection:p}=snapshot,band=happinessBand(p.relationship.happiness),pct=Math.min(100,Math.round(p.ratio*100));this.text(root,"[data-collection-title]",`${buyer.company} — Collection Ship`);this.text(root,"[data-collection-ship-name]",`${contract.shipName} • ${ship.name}`);this.text(root,"[data-collection-ship-description]",ship.description);this.setImage(root.querySelector("[data-collection-ship-image]"),root.querySelector("[data-collection-ship-fallback]"),`./assets/art/buyer-ships/${contract.shipImageKey}`,contract.shipName);this.text(root,"[data-collection-buyer]",buyer.name);this.text(root,"[data-collection-role]",buyer.role);this.text(root,"[data-collection-company]",buyer.company);this.text(root,"[data-collection-business]",buyer.businessType);this.text(root,"[data-collection-capacity]",`${formatNumber(ship.capacity)} CARGO`);this.setImage(root.querySelector("[data-collection-portrait]"),root.querySelector("[data-collection-portrait-fallback]"),`./assets/art/buyers/${contract.portraitKey}`,buyer.name);
    const alert=root.querySelector("[data-collection-alert]"),docked=p.shipStatus==="docked";alert.classList.toggle("orbit",!docked);alert.classList.toggle("good",docked);alert.textContent=docked?"DOCKED • SPACEPORT BERTH • READY FOR CARGO TRANSFER":"WAITING IN ORBIT — NO SPACEPORT BERTH AVAILABLE • TRANSFER IMPOSSIBLE";this.text(root,"[data-collection-resource]",contract.resourceName);this.text(root,"[data-collection-quality]",this.qualityLabel(contract.minQuality));this.text(root,"[data-collection-load]",formatNumber(contract.quantity));this.text(root,"[data-collection-stock]",formatNumber(p.stock));this.text(root,"[data-collection-price]",`£${rate(contract.unitRate)}`);this.text(root,"[data-collection-late]",p.daysLate===0?"ON TIME":p.daysLate);this.text(root,"[data-collection-percent]",`${pct}%`);root.querySelector("[data-collection-bar]").style.width=`${pct}%`;
    for(const el of root.querySelectorAll("[data-collection-band]"))el.classList.remove("active");if(p.ratio>=.999999)root.querySelector('[data-collection-band="full"]')?.classList.add("active");else if(p.ratio>=.75)root.querySelector('[data-collection-band="minor"]')?.classList.add("active");else if(p.ratio>=.5)root.querySelector('[data-collection-band="major"]')?.classList.add("active");
    this.renderImpact(root,p,band);const final=p.daysLate>=15||contract.ship.attemptIndex>=3,wait=root.querySelector("[data-collection-wait]"),transfer=root.querySelector("[data-collection-transfer]");wait.textContent=final?"FINAL ATTEMPT • RESOLVE MISSED SHIPMENT":"NOT READY • CONTINUE WAITING";transfer.disabled=!p.canTransfer;transfer.textContent=!docked?"TRANSFER BLOCKED • NO BERTH":p.ratio<.5?"MINIMUM 50% REQUIRED":`TRANSFER ${formatNumber(p.maxTransfer)} • ${formatMoney(p.payment)}`;this.text(root,"[data-collection-note]",!docked?"The lateness clock continues while the ship waits for a berth. Even with enough stock, transfer is impossible until the vessel docks.":p.ratio>=.5&&p.ratio<1?"Accepted partial shipments resolve this collection cycle. The missing quantity does not carry forward; the next cycle still requires the full contract load.":p.ratio>=1?"The buyer ship departs immediately after an accepted transfer.":"Wait for more qualifying stock or resolve a miss at the final attempt.");}
  renderImpact(root,p,band){let line;if(p.ratio<.5)line=`Only ${Math.round(p.ratio*100)}% available • below 50% minimum accepted shipment`;else if(p.ratio>=.999999&&p.daysLate===0)line="Full shipment on time • +1 buyer happiness";else{const timing=p.daysLate===0?"On time":`+${p.daysLate} day lateness ${p.timingChange}`,partial=p.ratio>=.999999?"full load":`${Math.round(p.ratio*100)}% partial ${p.partialChange}`;line=`${timing} • ${partial}`;}this.text(root,"[data-collection-impact]",line);this.text(root,"[data-collection-payment]",p.ratio>=.5?`Transfer ${formatNumber(p.maxTransfer)} • payment ${formatMoney(p.payment)}`:"No accepted transfer available.");this.text(root,"[data-collection-global]",p.ratio>=.5?`Buyer happiness ${Math.round(p.relationship.happiness)} → ${Math.round(p.projectedHappiness)} • global reputation net ${p.reputationChange>=0?"+":""}${p.reputationChange.toFixed(2)}`:`Current buyer happiness ${Math.round(p.relationship.happiness)} • ${band.name}`);const score=root.querySelector("[data-collection-score]");score.textContent=p.happinessChange===null?"—":`${p.happinessChange>0?"+":""}${p.happinessChange}`;const small=document.createElement("small");small.textContent="BUYER";score.append(small);}
}
