import { clamp, formatMoney, formatNumber } from "../core/utils.js";
import { CONFIG } from "../core/config.js";

export class ContractUIMixin {
  diagnosticsPanel(){const text=this.diagnostics.text(this.state).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;");this.open("Diagnostics / Error Log",`<div class="diag-log">${text}</div>`);}
  rare(tile){this.state.speed=0;this.syncSpeed();const icon=this.icons.svg(tile.resourceId,this.icons.colorFor(tile),38,tile.type),remaining=this.resources.isRenewable(tile)?"Sustainable":`reserve ${formatNumber(tile.reserve)}`;this.open("Exceptional Discovery",`<article class="card"><div class="resource-title">${icon}<h3>${tile.name} • Q${formatNumber(tile.quality)}</h3></div><p>${this.resources.categoryName(tile.type)} • ${tile.resourceRarity} • ${remaining}</p><div class="effect">Mining requirement: L${tile.requiredMiningLevel||1} • ${tile.requiredMiningTech||"Surface Recovery"}</div><button data-view>VIEW SITE</button></article>`);this.modal.querySelector("[data-view]").onclick=()=>{this.modal.classList.add("hidden");this.tile(tile)};}
  completionActions(title,score=null){
    const fee=this.contracts.renewalFee(this.state);
    this.open(title,`${score?`<article class="card"><h3>${score.rating.toUpperCase()} PERFORMANCE</h3><p>Colony contract profit ${formatMoney(score.profit)}</p></article>`:""}<article class="card"><h3>COLONY REMAINS ACTIVE</h3><p>You can renew the mining charter for another ${CONFIG.RENEWAL_YEARS} years, open another colony contract while this world remains in your portfolio, continue on holdover, or attempt to return the colony.</p><div class="effect warn">The corporation remains paused until this contract decision is resolved.</div></article><div class="grid2" style="margin-top:7px"><button data-renew>RENEW ${CONFIG.RENEWAL_YEARS} YEARS<br><span class="tiny">${formatMoney(fee)}</span></button><button data-new>OPEN NEW COLONY</button><button data-hold>CONTINUE ON HOLDOVER</button><button data-end>END / RETURN COLONY</button></div><button class="action" data-colonies>VIEW ALL COLONIES</button>`);
    this.modal.querySelector("[data-renew]").onclick=()=>{const r=this.contracts.renew(this.state);if(r.ok){this.repo.save(this.state);this.modal.classList.add("hidden");this.syncSpeed();if(this.onContractDecisionResolved)this.onContractDecisionResolved("renewed");this.toast(`Contract renewed for ${r.years} years.`);}else this.toast(r.reason)};
    this.modal.querySelector("[data-new]").onclick=()=>{this.state.status="holdover";this.repo.save(this.state);if(this.onContractDecisionResolved)this.onContractDecisionResolved("new-colony");else this.contractBoard();};
    this.modal.querySelector("[data-hold]").onclick=()=>{this.state.status="holdover";this.repo.save(this.state);this.modal.classList.add("hidden");if(this.onContractDecisionResolved)this.onContractDecisionResolved("holdover");else{this.state.speed=1;this.syncSpeed();}};
    this.modal.querySelector("[data-end]").onclick=()=>this.endContractDialog();
    this.modal.querySelector("[data-colonies]").onclick=()=>this.coloniesPanel();
  }
  deadline(kind=null){
    this.state.speed=0;this.syncSpeed();kind||=this.contracts.deadlineState(this.state)||this.state.contract?.pendingDecision;
    if(kind==="complete"){
      const result=this.contracts.awardCompletion(this.state);this.repo.save(this.state);this.completionActions("Initial Contract Complete",result.score);return;
    }
    if(kind==="renewal-ended"){
      this.contracts.enterHoldover(this.state);this.repo.save(this.state);this.completionActions("Renewal Term Complete");return;
    }
    if(kind==="extension"){
      const n=this.state.contract.extUsed+1,fee=this.contracts.extensionFee(this.state);this.state.status="deadline-missed";
      this.open("Contract Deadline Missed",`<article class="card"><h3>Objectives not met</h3><p>Extension ${n} of ${CONFIG.MAX_EXTENSIONS}</p><div class="effect warn">Fee ${formatMoney(fee)}</div><button data-ext>BUY 1-YEAR EXTENSION</button></article><button class="action" data-colonies>VIEW ALL COLONIES</button>`);
      this.modal.querySelector("[data-ext]").onclick=()=>{if(this.contracts.extend(this.state)){this.modal.classList.add("hidden");this.repo.save(this.state);if(this.onContractDecisionResolved)this.onContractDecisionResolved("extended");else{this.state.speed=1;this.syncSpeed();}}else this.toast("Unable to purchase extension.")};
      this.modal.querySelector("[data-colonies]").onclick=()=>this.coloniesPanel();return;
    }
    if(kind==="failed"){
      this.state.contract.ended=true;this.state.status="liability";this.repo.save(this.state);
      this.open("Charter Terminated",`<article class="card"><h3 class="bad">CONTRACT FAILED</h3><p>The permitted deadline extensions are exhausted. Mining rights have ended, but the colony and its population remain your responsibility.</p><div class="effect warn">Extraction stops. Food, Fuel and Power support requirements continue until the population is relocated. The corporation remains paused until this event is acknowledged.</div></article><div class="grid2"><button data-ack>ACKNOWLEDGE</button><button data-colonies>ALL COLONIES</button></div>`);
      this.modal.querySelector("[data-ack]").onclick=()=>{this.modal.classList.add("hidden");if(this.onContractDecisionResolved)this.onContractDecisionResolved("failed");else{this.state.speed=1;this.syncSpeed();}};
      this.modal.querySelector("[data-colonies]").onclick=()=>this.coloniesPanel();
    }
  }
  contractBoard(){if(this.state.company.gameOver){this.open("Corporation Ended",`<article class="card"><h3 class="bad">NO OPERATING COLONIES</h3><p>All colonies were lost. Start a new corporation from the Game menu to continue.</p></article>`);return;}const tier=this.state.company.wins+1,options=this.contracts.options(tier),stars=n=>"★".repeat(n)+"☆".repeat(5-n);this.open(`New Colony Contract — Corporation Tier ${tier}`,`<div class="choice5">${options.map((c,i)=>{const a=this.contracts.archetype(c),ok=this.technology.meetsRequirements(this.state,c.requiredTech),req=`P${c.requiredTech.power} • F${c.requiredTech.food} • M${c.requiredTech.mining}`;return`<article class="card"><h3>${c.name}</h3><p>${c.environment}<br>${c.hazard}<br><strong>${c.supportSystem}</strong></p><div class="tiny">Food <span class="stars">${stars(a.stars.food)}</span></div><div class="tiny">Build <span class="stars">${stars(a.stars.build)}</span></div><div class="tiny">Fuel <span class="stars">${stars(a.stars.fuel)}</span></div><div class="tiny">Ore <span class="stars">${stars(a.stars.ore)}</span></div><div class="effect ${ok?"":"warn"}">Required tech ${req} • ${c.techAccess==="direct"?"Direct tech link":"Trade-ship tech only"}</div><div class="effect">Environmental support load ×${Number(c.supportLoad||1).toFixed(2)} • Advance ${formatMoney(c.advance)}</div><button data-contract="${i}" ${ok?"":"disabled"}>${ok?"ESTABLISH COLONY":"TECH LOCKED"}</button></article>`}).join("")}</div>`);this.modal.querySelectorAll("[data-contract]").forEach(b=>b.onclick=()=>{const c=options[+b.dataset.contract];if(!this.technology.meetsRequirements(this.state,c.requiredTech)){this.toast("Technology requirements not met.");return}this.onNewContract?.(c);});}
  render(){const s=this.state,c=s.contract,g=c.goals,m=s.metrics,deadline=this.contracts.deadline(s),elapsed=(s.year-1)+(s.day-1)/CONFIG.DAYS_PER_YEAR;document.querySelector("#contractName").textContent=`${c.colonyName||"Colony"} • T${c.colonyTier} • ${c.name}`;document.querySelector("#timeBar").style.width=`${clamp(elapsed/deadline*100,0,100)}%`;document.querySelector("#dateText").textContent=s.status==="dead"?"COLONY LOST":s.colony?.emergencyMode?`Y${s.year} • EMERGENCY`:s.status==="liability"?`Y${s.year} • LIABILITY`:s.status==="holdover"?`Y${s.year} • HOLDOVER`:s.status==="contract-decision"?`Y${s.year} • ACTION REQUIRED`:`Y${s.year} • D${s.day} / ${deadline}Y`;const goal=(p,v,t)=>{document.querySelector(`#${p}Val`).textContent=formatNumber(v);document.querySelector(`#${p}Goal`).textContent=`${formatNumber(v)} / ${formatNumber(t)}`;document.querySelector(`#${p}Bar`).style.width=`${clamp(v/t*100,0,100)}%`};goal("food",m.food,g.food);goal("ind",m.industry,g.industry);goal("pop",s.pop,g.pop);document.querySelector("#cash").textContent=formatMoney(s.company.cash);document.querySelector("#foodStock").textContent=formatNumber(this.inventory.amount(s,"food"));document.querySelector("#buildStock").textContent=formatNumber(this.inventory.amount(s,"build"));document.querySelector("#fuelStock").textContent=formatNumber(this.inventory.amount(s,"fuel"));document.querySelector("#oreStock").textContent=formatNumber(this.inventory.amount(s,"ore"));const active=s.scans,queued=s.scanQueue,hud=document.querySelector("#scanHud");hud.classList.toggle("hidden",!(active.length||queued.length));if(active.length||queued.length){document.querySelector("#scanText").textContent=`${active.length}/${this.survey.slots(s)} active • ${queued.length} queued`;const progress=active.length?active.reduce((sum,q)=>sum+(1-q.remaining/q.total),0)/active.length:0;document.querySelector("#scanBar").style.width=`${clamp(progress*100,0,100)}%`;}}
}
