import { clamp, formatMoney, formatNumber } from "../core/utils.js";
import { CONFIG } from "../core/config.js";

export class ContractUIMixin {
  menu(){this.open("Game",`<div class="grid2"><button data-save>Save now</button><button data-diagnostics>Diagnostics</button><button data-help>How to play</button><button data-center>Centre on ship</button><button data-reset class="bad" style="grid-column:1/-1">HARD RESET ALL MINEIT DATA</button></div>`);this.modal.querySelector("[data-save]").onclick=()=>this.toast(this.repo.save(this.state)?"Game saved.":"Save failed.");this.modal.querySelector("[data-diagnostics]").onclick=()=>this.diagnosticsPanel();this.modal.querySelector("[data-center]").onclick=()=>{this.state.camera={x:-4,y:-4};this.modal.classList.add("hidden")};this.modal.querySelector("[data-help]").onclick=()=>this.open("How to Play",`<div class="cards one"><div class="card"><h3>Survey & unlock</h3><p>Survey tiles to identify resources. A resource can be known but still locked until your Mining technology supports its extraction method.</p></div><div class="card"><h3>Four resources</h3><p>Food feeds population. Build constructs sites, housing and industry. Fuel powers the colony. Ore is continuously consumed by industry and includes common metals, precious metals and gemstones.</p></div><div class="card"><h3>Power & colony growth</h3><p>Population and industry raise power demand. Higher Power technologies increase the maximum population and industry the colony can support.</p></div><div class="card"><h3>Technology</h3><p>Power, Food Production and Mining each have ten sequential technologies. Easy claims have a direct corporate link; deep-reach claims can buy technology only while the trade ship is docked.</p></div></div>`);this.modal.querySelector("[data-reset]").onclick=()=>this.onHardReset();}
  diagnosticsPanel(){const text=this.diagnostics.text(this.state).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;");this.open("Diagnostics / Error Log",`<div class="diag-log">${text}</div>`);}
  rare(tile){this.state.speed=0;this.syncSpeed();const icon=this.icons.svg(tile.resourceId,this.icons.colorFor(tile),38,tile.type),remaining=this.resources.isRenewable(tile)?"Sustainable":`reserve ${formatNumber(tile.reserve)}`;this.open("Exceptional Discovery",`<article class="card"><div class="resource-title">${icon}<h3>${tile.name} • Q${formatNumber(tile.quality)}</h3></div><p>${this.resources.categoryName(tile.type)} • ${tile.resourceRarity} • ${remaining}</p><div class="effect">Mining requirement: L${tile.requiredMiningLevel||1} • ${tile.requiredMiningTech||"Surface Recovery"}</div><button data-view>VIEW SITE</button></article>`);this.modal.querySelector("[data-view]").onclick=()=>{this.modal.classList.add("hidden");this.tile(tile)};}

  deadline(){this.state.speed=0;this.syncSpeed();const score=this.contracts.score(this.state);if(score.passed){this.state.status="won";this.state.company.wins++;this.state.company.rep+=({Bronze:1,Silver:2,Gold:4,Platinum:7}[score.rating]||1);this.open("Contract Complete",`<article class="card"><h3>${score.rating.toUpperCase()} PERFORMANCE</h3><p>Contract profit ${formatMoney(score.profit)}</p><button data-next>CHOOSE NEXT CONTRACT</button></article>`);this.modal.querySelector("[data-next]").onclick=()=>this.contractBoard();return;}if(this.state.contract.extUsed<CONFIG.MAX_EXTENSIONS){const n=this.state.contract.extUsed+1,fee=25000*n*this.state.contract.tier;this.open("Contract Deadline Missed",`<article class="card"><h3>Objectives not met</h3><p>Extension ${n} of ${CONFIG.MAX_EXTENSIONS}</p><div class="effect warn">Fee ${formatMoney(fee)}</div><button data-ext>BUY 1-YEAR EXTENSION</button></article>`);this.modal.querySelector("[data-ext]").onclick=()=>{if(this.contracts.extend(this.state)){this.modal.classList.add("hidden");this.state.speed=1;this.syncSpeed()}};}else{this.state.status="failed";this.open("Contract Failed",`<article class="card"><h3 class="bad">CHARTER TERMINATED</h3><p>The objectives were not achieved within the permitted extensions.</p></article>`);}}

  contractBoard(){const tier=this.state.company.wins+1,options=this.contracts.options(tier),stars=n=>"★".repeat(n)+"☆".repeat(5-n);this.open(`Contract Board — Corporation Tier ${tier}`,`<div class="choice5">${options.map((c,i)=>{const a=this.contracts.archetype(c),ok=this.technology.meetsRequirements(this.state,c.requiredTech),req=`P${c.requiredTech.power} • F${c.requiredTech.food} • M${c.requiredTech.mining}`;return`<article class="card"><h3>${c.name}</h3><p>${c.environment}<br>${c.hazard}<br><strong>${c.supportSystem}</strong></p><div class="tiny">Food <span class="stars">${stars(a.stars.food)}</span></div><div class="tiny">Build <span class="stars">${stars(a.stars.build)}</span></div><div class="tiny">Fuel <span class="stars">${stars(a.stars.fuel)}</span></div><div class="tiny">Ore <span class="stars">${stars(a.stars.ore)}</span></div><div class="effect ${ok?"":"warn"}">Required tech ${req} • ${c.techAccess==="direct"?"Direct tech link":"Trade-ship tech only"}</div><div class="effect">Advance ${formatMoney(c.advance)}</div><button data-contract="${i}" ${ok?"":"disabled"}>${ok?"ACCEPT":"TECH LOCKED"}</button></article>`}).join("")}</div>`);this.modal.querySelectorAll("[data-contract]").forEach(b=>b.onclick=()=>{const c=options[+b.dataset.contract];if(!this.technology.meetsRequirements(this.state,c.requiredTech)){this.toast("Technology requirements not met.");return}this.onNewContract(c);this.modal.classList.add("hidden")});}

  render(){const s=this.state,c=s.contract,g=c.goals,m=s.metrics,deadline=c.years+c.ext,elapsed=(s.year-1)+(s.day-1)/CONFIG.DAYS_PER_YEAR;document.querySelector("#contractName").textContent=`T${c.colonyTier} • ${c.name}`;document.querySelector("#timeBar").style.width=`${clamp(elapsed/deadline*100,0,100)}%`;document.querySelector("#dateText").textContent=`Y${s.year} • D${s.day} / ${deadline}Y`;const goal=(p,v,t)=>{document.querySelector(`#${p}Val`).textContent=formatNumber(v);document.querySelector(`#${p}Goal`).textContent=`${formatNumber(v)} / ${formatNumber(t)}`;document.querySelector(`#${p}Bar`).style.width=`${clamp(v/t*100,0,100)}%`};goal("food",m.food,g.food);goal("ind",m.industry,g.industry);goal("pop",s.pop,g.pop);document.querySelector("#cash").textContent=formatMoney(s.company.cash);document.querySelector("#foodStock").textContent=formatNumber(this.inventory.amount(s,"food"));document.querySelector("#buildStock").textContent=formatNumber(this.inventory.amount(s,"build"));document.querySelector("#fuelStock").textContent=formatNumber(this.inventory.amount(s,"fuel"));document.querySelector("#oreStock").textContent=formatNumber(this.inventory.amount(s,"ore"));const active=s.scans,queued=s.scanQueue,hud=document.querySelector("#scanHud");hud.classList.toggle("hidden",!(active.length||queued.length));if(active.length||queued.length){document.querySelector("#scanText").textContent=`${active.length}/${this.survey.slots(s)} active • ${queued.length} queued`;const progress=active.length?active.reduce((sum,q)=>sum+(1-q.remaining/q.total),0)/active.length:0;document.querySelector("#scanBar").style.width=`${clamp(progress*100,0,100)}%`;}}
}
