import { formatNumber } from "../core/utils.js";
import { ColonyTechUIMixin } from "./colony-tech-ui.js";
import { ResourceUIMixin } from "./resource-ui.js";
import { UIEnhancementsMixin } from "./ui-enhancements.js";

export class IndustryUIMixin {
  industryPct(value){return `${Math.round(Math.max(0,Math.min(1,Number(value)||0))*100)}%`;}
  colonyPanel(){ColonyTechUIMixin.prototype.colonyPanel.call(this);if(this.state.status==="dead")return;const m=this.state.metrics,emergency=!!this.state.colony?.emergencyMode,capacity=Math.max(0,Number(m.industryCapacity)||0),load=Math.max(0,Number(m.industryLoad)||0),factor=m.industryCommercialFactor??1,bonus=Math.max(0,Number(m.processingBonus)||0),headroom=Math.max(0,capacity-load),body=this.modal.querySelector(".modal-body"),needs=body?.querySelector(".need-grid");if(!body||!needs)return;const overloaded=!emergency&&load>capacity+.001,status=emergency?`<span class="warn">— EMERGENCY SHUTDOWN</span>`:overloaded?`<span class="bad">— OVERLOADED</span>`:`<span class="good">— AVAILABLE</span>`;needs.insertAdjacentHTML("beforebegin",`<article class="card" style="margin-top:7px"><h3>INDUSTRIAL CAPACITY ${status}</h3><div class="grid2"><div class="metric"><small>Site load / capacity</small><strong>${formatNumber(load)} / ${formatNumber(capacity)}</strong></div><div class="metric"><small>Capacity headroom</small><strong>${overloaded?"0":formatNumber(headroom)}</strong></div><div class="metric"><small>Build/Ore extraction</small><strong>${this.industryPct(factor)}</strong></div><div class="metric"><small>Export processing</small><strong>+${Math.round(bonus*100)}%</strong></div></div><p>${emergency?`Emergency Mode has shut Industry and commercial extraction down. Food and Fuel remain prioritised for life support.`:overloaded?`Food and Fuel sites keep priority. Build and Ore extraction are automatically reduced to ${this.industryPct(factor)} until Industry capacity or staffing increases.`:`Developed sites consume Industrial Capacity. Food and Fuel are automatically prioritised; spare capacity runs Build and Ore operations.`}</p></article>`);}
  currentCollection(){UIEnhancementsMixin.prototype.currentCollection.call(this);if(this.state.colony?.emergencyMode)return;const factor=this.state.metrics.industryCommercialFactor??1;if(factor>=.999)return;const body=this.modal.querySelector(".modal-body");if(body)body.insertAdjacentHTML("afterbegin",`<div class="requirement locked">INDUSTRY OVERLOAD — Build/Ore collection is running at ${this.industryPct(factor)}. Food/Fuel extraction keeps priority.</div>`);}
  tile(tile){ResourceUIMixin.prototype.tile.call(this,tile);if(!tile?.revealed)return;const load=this.colony.siteIndustryLoad(tile),commercial=tile.type==="build"||tile.type==="ore",emergency=!!this.state.colony?.emergencyMode,factor=this.state.metrics.industryCommercialFactor??1,fullRate=this.resources.unthrottledCollectionRate(this.state,tile),effectiveRate=this.resources.collectionRate(this.state,tile),firstReq=this.tilePanel.querySelector(".requirement");if(!firstReq)return;const text=tile.developed?`Industrial load ${formatNumber(load)} capacity${commercial&&!emergency&&factor<.999?` • overload limits this site's rate to ${this.industryPct(factor)} (${formatNumber(effectiveRate)}/d vs ${formatNumber(fullRate)}/d full rate)`:""}`:`Development adds ${formatNumber(load)} Industrial Capacity load.`;firstReq.insertAdjacentHTML("afterend",`<div class="effect ${commercial&&!emergency&&factor<.999?"warn":""}">${text}</div>`);}
}
