import { formatMoney, formatNumber } from "../core/utils.js?v=5.5.0";

export class LandUIMixin{
  landPreview(candidate){return`<div class="land-preview">${candidate.cells.map(cell=>`<i class="terrain-${cell.terrain} v${cell.variant}" title="${this.land.terrainLabel(cell.terrain)}"></i>`).join("")}</div>`;}
  landSelection({abandon=false}={}){
    const land=this.land.ensure(this.state);if(abandon){this.landReturnSpeed=this.state.speed;this.state.speed=0;this.syncSpeed();}
    this.open(abandon?"Choose a New Landing Site":"Choose Colony Landing Site",`<article class="card"><h3>${abandon?"ABANDON CURRENT SITE":"SELECT ONE OF 8 LOCATIONS"}</h3><p>${abandon?"The colony keeps its people, corporate technology and 25% of stored material. Buildings, mines, surveys and the rest of the local stock are left behind. The contract clock does not reset.":"Only the land is known before settlement. Resources remain hidden until each tile is surveyed."}</p></article><div class="landing-choice-grid">${land.candidates.map((candidate,index)=>`<article class="landing-choice ${land.selectedIndex===index?"current":""}">${this.landPreview(candidate)}<button data-land-choice="${index}">${land.selectedIndex===index?"CHOOSE CURRENT SITE":`CHOOSE LOCATION ${index+1}`}</button></article>`).join("")}</div>${abandon?`<button class="action" data-land-cancel>CANCEL</button>`:""}`);
    const close=this.modal.querySelector("[data-close]");if(close&&!abandon)close.style.display="none";
    this.modal.querySelectorAll("[data-land-choice]").forEach(button=>button.onclick=()=>this.onSelectLand?.(+button.dataset.landChoice,{abandon}));
    const cancel=this.modal.querySelector("[data-land-cancel]");if(cancel)cancel.onclick=()=>{this.state.speed=this.landReturnSpeed??1;this.syncSpeed();this.modal.classList.add("hidden")};
  }
  buildChoice(tile){
    if(!tile?.revealed){this.toast("Survey this tile before construction.");return;}
    const housing=this.development.canPlace(this.state,tile,"housing"),industry=this.development.canPlace(this.state,tile,"industry"),covered=!!tile.resourceId;
    this.open(`Develop ${this.land.terrainLabel(tile.terrain)} Tile`,`<article class="card"><h3>${covered?`${tile.name} • Q${formatNumber(tile.quality)}`:"CLEAR SURVEYED LAND"}</h3><p>${covered?(tile.type==="food"?"Building here permanently destroys this natural Food resource.":"Housing or Industry can be built here, but the known resource will become inaccessible until the building is demolished."):"Choose what to construct. Further taps on the completed building upgrade it immediately."}</p></article><div class="grid2"><button data-place="housing" ${housing.ok?"":"disabled"}>HOUSING L1<br><span class="tiny">${Number.isFinite(housing.cash)?`${formatMoney(housing.cash)} + ${formatNumber(housing.build)} Build`:housing.reason}</span></button><button data-place="industry" ${industry.ok?"":"disabled"}>INDUSTRY L1<br><span class="tiny">${Number.isFinite(industry.cash)?`${formatMoney(industry.cash)} + ${formatNumber(industry.build)} Build`:industry.reason}</span></button></div>${housing.ok?"":`<div class="requirement locked">Housing: ${housing.reason}</div>`}${industry.ok?"":`<div class="requirement locked">Industry: ${industry.reason}</div>`}`);
    this.modal.querySelectorAll("[data-place]").forEach(button=>button.onclick=()=>{const kind=button.dataset.place;if(covered&&!confirm(tile.type==="food"?`Build ${kind} over ${tile.name}? This Food resource will be permanently destroyed.`:`Build ${kind} over ${tile.name}? The resource remains underground but cannot be exploited until the building is demolished.`))return;this.onPlaceDevelopment?.(tile,kind)});
  }
  landTile(tile){
    if(this.land.isShipTile(tile.x,tile.y)){this.company();return;}
    const terrain=this.land.terrainLabel(tile.terrain),survey=tile.revealed?"Surveyed":"Unsurveyed",deep=tile.deepResource?"Deep geology signal stored for future deep surveying.":"No deep survey data yet.";
    if(!tile.revealed){this.open(`${terrain} • ${tile.x},${tile.y}`,`<article class="card"><h3>${survey.toUpperCase()}</h3><p>${this.world.hint(this.state,tile.x,tile.y)}</p><div class="effect">Land can only be developed after surveying.</div></article>`);return;}
    const dev=tile.development;
    if(dev?.kind==="housing"||dev?.kind==="industry"){
      const next=this.development.canUpgrade(this.state,tile),covered=tile.resourceId?`${tile.name} • Q${formatNumber(tile.quality)} (covered)`:"No known surface resource";
      this.open(`${this.development.label(dev.kind)} L${dev.level}`,`<div class="grid2"><div class="metric"><small>Terrain</small><strong>${terrain}</strong></div><div class="metric"><small>Surface geology</small><strong>${covered}</strong></div><div class="metric"><small>Development</small><strong>L${dev.level}/5</strong></div><div class="metric"><small>Deep layer</small><strong>${deep}</strong></div></div><div class="effect ${next.ok?"good":"warn"}">${next.ok?`Tap this tile to upgrade to L${next.nextLevel}: ${formatMoney(next.cash)} + ${formatNumber(next.build)} Build.`:next.reason}</div><button class="bad" data-demolish>DEMOLISH • recover 25% of invested Build</button>`);this.modal.querySelector("[data-demolish]").onclick=()=>{if(confirm(`Demolish ${this.development.label(dev.kind)} L${dev.level}?`))this.onDemolishDevelopment?.(tile)};return;
    }
    if(dev?.kind==="extract"||tile.developed){
      const next=this.sites.upgradeRequirements(this.state,tile),remaining=this.resources.isRenewable(tile)?"Sustainable":formatNumber(tile.reserve);
      this.open(`${tile.name} • ${dev?.family||"Extraction"} L${tile.level}`,`<div class="grid2"><div class="metric"><small>Terrain</small><strong>${terrain}</strong></div><div class="metric"><small>Quality</small><strong>${this.quality(tile.quality)}</strong></div><div class="metric"><small>Remaining</small><strong>${remaining}</strong></div><div class="metric"><small>Collection</small><strong>${formatNumber(this.resources.collectionRate(this.state,tile))}/d</strong></div></div><div class="effect ${next.ok?"good":"warn"}">${next.ok?`Tap this tile to upgrade to L${next.nextLevel}: ${formatMoney(next.cash)} + ${formatNumber(next.build)} Build.`:next.reason}</div><button class="bad" data-demolish>DEMOLISH EXTRACTION SITE</button>`);this.modal.querySelector("[data-demolish]").onclick=()=>{if(confirm(`Demolish the ${tile.name} extraction site? The resource remains.`))this.onDemolishDevelopment?.(tile)};return;
    }
    if(tile.resourceId){
      const req=this.sites.developRequirements(this.state,tile),housing=this.development.canPlace(this.state,tile,"housing"),industry=this.development.canPlace(this.state,tile,"industry");
      this.open(`${tile.name} • Q${formatNumber(tile.quality)}`,`<div class="grid2"><div class="metric"><small>Terrain</small><strong>${terrain}</strong></div><div class="metric"><small>Category</small><strong>${this.resources.categoryName(tile.type)}</strong></div><div class="metric"><small>Mining requirement</small><strong>L${tile.requiredMiningLevel||1}</strong></div><div class="metric"><small>Deposit</small><strong>${this.resources.isRenewable(tile)?"Sustainable":formatNumber(tile.reserve)}</strong></div></div><div class="effect ${req.ok?"good":"warn"}">${req.ok?`Tap this tile to develop the resource: ${formatMoney(req.cash)} + ${formatNumber(req.build)} Build.`:req.reason}</div><article class="card"><h3>BUILD OVER RESOURCE</h3><p>${tile.type==="food"?"This natural Food resource will be permanently destroyed.":"The deposit remains, but becomes inaccessible until the building is demolished."}</p><div class="grid2"><button data-cover="housing" ${housing.ok?"":"disabled"}>HOUSING</button><button data-cover="industry" ${industry.ok?"":"disabled"}>INDUSTRY</button></div></article>`);this.modal.querySelectorAll("[data-cover]").forEach(button=>button.onclick=()=>{if(confirm(tile.type==="food"?`Build over ${tile.name}? This Food resource will be destroyed.`:`Cover ${tile.name} with ${button.dataset.cover}?`))this.onPlaceDevelopment?.(tile,button.dataset.cover)});return;
    }
    this.buildChoice(tile);
  }
  landColonyPanel(){
    this.onRecalculate?.();const land=this.land.ensure(this.state),housingTiles=this.development.developments(this.state,"housing").length,industryTiles=this.development.developments(this.state,"industry").length,extractTiles=this.development.developments(this.state,"extract").length;
    this.open(`${this.state.contract.colonyName} — Colony Land`,`<article class="card"><h3>LOCATION ${Number(land.selectedIndex)+1} OF 8</h3><p>${this.state.contract.environment}<br>Housing, Industry and extraction are now developed directly on surveyed map tiles.</p></article><div class="grid2"><div class="metric"><small>Population / Housing</small><strong>${formatNumber(this.state.pop)} / ${formatNumber(this.state.colony.housingCapacity)}</strong></div><div class="metric"><small>Industry</small><strong>L${this.state.colony.industryLevel} • ${formatNumber(this.state.metrics.industry)}</strong></div><div class="metric"><small>Housing tiles</small><strong>${housingTiles}</strong></div><div class="metric"><small>Industry tiles</small><strong>${industryTiles}</strong></div><div class="metric"><small>Extraction sites</small><strong>${extractTiles}</strong></div><div class="metric"><small>Relocations</small><strong>${land.moves||0}</strong></div></div><div class="need-grid"><div class="metric need"><small>Food</small><strong>${formatNumber(this.state.metrics.foodStock||0)}</strong></div><div class="metric need"><small>Fuel</small><strong>${formatNumber(this.state.metrics.fuelStock||0)}</strong></div><div class="metric need"><small>Ore</small><strong>${formatNumber(this.state.metrics.oreStock||0)}</strong></div><div class="metric need"><small>Power</small><strong>${formatNumber(this.state.metrics.powerDemand||0)} / ${formatNumber(this.state.metrics.powerCapacity||0)}</strong></div></div><div class="effect">Tap a surveyed clear tile to place Housing or Industry. Tap an existing development to upgrade it instantly. Hold a tile for 2 seconds for details or demolition.</div><button data-emergency>${this.state.colony.emergencyMode?"EXIT EMERGENCY MODE":"ENTER EMERGENCY MODE"}</button><button class="bad action" data-reselect>ABANDON LAND & CHOOSE ANOTHER SITE</button>`);this.modal.querySelector("[data-emergency]").onclick=()=>{this.state.colony.emergencyMode=!this.state.colony.emergencyMode;this.onRecalculate?.();this.repo.save(this.state);this.toast(this.state.colony.emergencyMode?"Emergency Mode active.":"Emergency Mode ended.");this.landColonyPanel()};this.modal.querySelector("[data-reselect]").onclick=()=>this.landSelection({abandon:true});
  }
}
