import { formatMoney, formatNumber } from "../core/utils.js";
import { SHIP_INFRASTRUCTURE,builtCapacity } from "../domain/building-model.js";

/** Canonical corporation portfolio presentation. */
export class PortfolioUIMixin {
  colonyStatus(summary){
    if(summary?.status==="contract-decision")return{label:"ACTION REQUIRED",cls:"warn"};
    if(summary.status==="dead")return{label:"DEAD",cls:"bad"};if(summary.emergencyMode)return{label:"EMERGENCY",cls:"warn"};if(summary.survivalSupply<.4)return{label:"COLLAPSE",cls:"bad"};if(summary.survivalSupply<.9)return{label:"STRAINED",cls:"warn"};if(summary.status==="liability")return{label:"LIABILITY",cls:"bad"};if(summary.status==="holdover")return{label:"HOLDOVER",cls:"warn"};if(summary.status==="deadline-missed")return{label:"ACTION REQUIRED",cls:"warn"};if(summary.status==="failed")return{label:"FAILED",cls:"bad"};if(summary.completed)return{label:"RENEWED",cls:"good"};return{label:`CONTRACT Y${summary.year}`,cls:"good"};
  }
  colonyDays(days){return days===null||days===undefined?"∞":days<=0?"0d":`${Math.max(1,Math.ceil(days))}d`;}
  coloniesPanel(){
    const entries=this.portfolio.entries(this.state),active=this.state.portfolio.activeColonyId;
    const cards=entries.map(entry=>{
      const s=this.portfolio.summary(entry,this.state),st=this.colonyStatus(s),wf=s.workforceRequired?Math.min(100,Math.round(s.workforceAvailable/s.workforceRequired*100)):100,data=entry.id===active?this.state:entry.data;
      const installed=SHIP_INFRASTRUCTURE.industry+builtCapacity(entry.data,"industry"),effective=Math.max(0,Number(entry.data?.metrics?.industry)||0),rawStaff=Number(entry.data?.metrics?.industryStaffFactor),staff=Math.round(Math.max(0,Math.min(1,Number.isFinite(rawStaff)?rawStaff:1))*100),shipWaiting=!!data?.trade?.active;
      return `<button class="colony-card ${entry.id===active?"active":""}" data-colony-id="${entry.id}"><div class="colony-card-top"><strong>${s.name}</strong><span class="${st.cls}">${st.label}</span></div><div class="colony-card-env">T${s.tier} • ${s.environment} • support ×${Number(s.supportLoad||1).toFixed(2)}</div><div class="colony-card-grid"><span>POP<strong>${formatNumber(s.pop)}</strong></span><span>IND<strong>${formatNumber(effective)} / ${formatNumber(installed)} • ${staff}%</strong></span><span>WORK<strong>${wf}%</strong></span><span>AGE<strong>Y${s.year} D${s.day}</strong></span></div><div class="colony-card-stock"><span>F ${s.status==="dead"?formatNumber(s.foodStock):this.colonyDays(s.foodDays)}</span><span>FU ${s.status==="dead"?formatNumber(s.fuelStock):this.colonyDays(s.fuelDays)}</span><span>O ${s.status==="dead"?formatNumber(s.oreStock):this.colonyDays(s.oreDays)}</span>${s.pendingTransport?`<span>⇢ +${formatNumber(s.pendingTransport)}</span>`:""}</div>${entry.id===active?`<div class="colony-active-tag">CURRENTLY VIEWING</div>`:""}${shipWaiting?`<div class="colony-active-tag warn" data-ship-waiting>CORPORATE SHIP DOCKED</div>`:""}</button>`;
    }).join("");
    const canNew=this.contracts.canOpenAdditional(this.state),living=entries.filter(entry=>entry.data?.status!=="dead").length;
    this.open(`Colonies — ${entries.length} (${living} active)`,`<article class="card"><p>Corporation date <strong>Y${this.state.year} D${this.state.day}</strong>. All colonies advance together at the same simulation speed.</p></article><div class="colony-grid">${cards}</div><button class="action" data-new-colony ${canNew?"":"disabled"}>OPEN NEW COLONY CONTRACT</button>${canNew?"":`<div class="requirement locked">${this.state.company.gameOver?"Corporation operations have ended because all colonies were lost.":"Complete the first 10-year contract to unlock additional colonies."}</div>`}`);
    this.modal.querySelectorAll("[data-colony-id]").forEach(button=>button.onclick=()=>{const id=button.dataset.colonyId;if(id===active){this.modal.classList.add("hidden");return;}this.onSwitchColony?.(id);});const newButton=this.modal.querySelector("[data-new-colony]");if(newButton)newButton.onclick=()=>this.contractBoard();
  }
  endContractDialog(){
    if(this.state.status==="dead"){this.colonyPanel();return;}if(!this.state.contract.completed&&!this.state.contract.ended){this.open("End Contract",`<article class="card"><h3>CONTRACT STILL ACTIVE</h3><p>The colony can be returned or disposed of after its initial contract has completed.</p></article>`);return;}
    const health=this.contracts.resourceHealth(this.state),ratio=`${Math.round(health.ratio*100)}%`,remaining=this.state.portfolio.colonies.length>1;
    if(health.accepted&&!this.state.contract.ended){this.open("Return Colony",`<article class="card"><h3>CORPORATION WILL ACCEPT RETURN</h3><p>Known finite deposits retain ${ratio} of their surveyed reserves${health.renewable?` and ${health.renewable} renewable resource site${health.renewable===1?"":"s"} remain`:""}. The corporation is willing to take the colony back.</p><div class="effect">Population and infrastructure transfer with the colony.</div></article><button class="action" data-return ${remaining?"":"disabled"}>RETURN COLONY TO CORPORATION</button>${remaining?"":`<div class="requirement locked">Open another colony before returning your final colony.</div>`}`);const button=this.modal.querySelector("[data-return]");if(button)button.onclick=()=>this.onRemoveColony?.("corporate-return");return;}
    const relocation=this.colony.relocationCost(this.state),canRelocate=remaining&&this.state.company.cash>=relocation;
    this.open("Corporation Refuses Colony",`<article class="card"><h3 class="bad">RETURN REFUSED</h3><p>The known resource base is too depleted for the corporation to accept the colony. Finite reserve health is ${ratio} and no sufficient renewable resource base remains.</p><div class="effect warn">Ending the mining contract makes this a support-only liability colony. Extraction stops, but population still requires Food, Fuel and Power until relocation. There is no generic daily corporate cash charge.</div></article><div class="grid2" style="margin-top:7px"><button data-liability>END CONTRACT<br><span class="tiny">KEEP COLONY RUNNING</span></button><button data-relocate ${canRelocate?"":"disabled"}>RELOCATE POPULATION<br><span class="tiny">${formatMoney(relocation)}</span></button></div>${remaining?"":`<div class="requirement locked">Open another colony before disposing of your final colony.</div>`}${this.state.company.cash<relocation?`<div class="requirement locked">Relocation requires ${formatMoney(relocation)}.</div>`:""}`);
    this.modal.querySelector("[data-liability]").onclick=()=>{this.onMakeLiability?.();this.colonyPanel();};const relocate=this.modal.querySelector("[data-relocate]");if(relocate)relocate.onclick=()=>this.onRelocateColony?.();
  }
}
