import { formatMoney, formatNumber } from "../core/utils.js";
import { OPERATING_MODES,operatingMode,riskExposure,accidentDetails,isAccidentShutdown,OVERDRIVE_RISK_PERIOD } from "../domain/extraction-overdrive.js";

export class ResourceUIMixin {
  tile(tile){
    if(!tile.revealed){const days=this.survey.days(this.state,tile.x,tile.y),active=this.survey.isActive(this.state,tile.x,tile.y),queued=this.survey.isQueued(this.state,tile.x,tile.y);this.tilePanel.innerHTML=`${this.panelTitle(`Unsurveyed sector ${tile.x},${tile.y}`)}<div class="grid3"><div class="metric"><small>Scanner hint</small><strong class="survey">${this.world.hint(this.state,tile.x,tile.y)}</strong></div><div class="metric"><small>Survey time</small><strong>${days} days</strong></div><div class="metric"><small>Survey slots</small><strong>${this.state.scans.length}/${this.survey.slots(this.state)}</strong></div></div><button class="action" data-scan ${active||queued||this.state.contract.ended?"disabled":""}>${this.state.contract.ended?"CONTRACT ENDED":active?"SURVEY ACTIVE":queued?"QUEUED":"QUEUE SURVEY"}</button>`;this.tilePanel.classList.remove("hidden");this.tilePanel.querySelector("[data-close]").onclick=()=>this.tilePanel.classList.add("hidden");const scan=this.tilePanel.querySelector("[data-scan]");if(scan)scan.onclick=()=>{const r=this.survey.enqueue(this.state,tile.x,tile.y);if(r.ok){this.tilePanel.classList.add("hidden");this.toast(r.active?"Survey started.":"Added to survey queue.")}};return;}
    const nominalRate=this.resources.collectionRate(this.state,tile),paused=!!this.state.colony?.emergencyMode&&tile.developed&&!tile.depleted&&tile.type!=="food"&&tile.type!=="fuel",rate=paused?0:nominalRate,category=this.resources.categoryName(tile.type),cls=tile.type,renewable=this.resources.isRenewable(tile),life=tile.developed?this.resources.estimatedLifeYears(this.state,tile):null,remaining=renewable?"Sustainable":formatNumber(tile.reserve),lifeText=paused?"Paused":life===null?"—":renewable?"Permanent":life>=100?`${Math.round(life)}y`:`${life.toFixed(1)}y`,scale=renewable?(tile.abundanceLabel||"Sustainable"):(tile.depositScale||"Finite"),icon=this.icons.svg(tile.resourceId,this.icons.colorFor(tile),30,tile.type),required=tile.requiredMiningLevel||1,techOk=this.technology.canExploit(this.state,tile),stock=this.stockFor(tile);
    this.tilePanel.innerHTML=`${this.panelTitle(tile.depleted?`${tile.name} — DEPLETED`:tile.name,icon)}<div class="grid3"><div class="metric"><small>Category</small><strong class="${cls}">${category}</strong></div><div class="metric"><small>Rarity</small><strong>${tile.resourceRarity}</strong></div><div class="metric"><small>Quality</small><strong>${this.quality(tile.quality)}</strong></div><div class="metric"><small>Collection rate</small><strong class="${cls}">${paused?"PAUSED":`${formatNumber(rate)}/day`}</strong></div><div class="metric"><small>In stock</small><strong>${formatNumber(stock)}</strong></div><div class="metric"><small>Remaining</small><strong>${remaining}</strong></div><div class="metric"><small>${renewable?"Capacity":"Deposit"}</small><strong>${scale}</strong></div><div class="metric"><small>Est. life</small><strong>${lifeText}</strong></div><div class="metric"><small>Site level</small><strong>${tile.developed?`L${tile.level}`:"Undeveloped"}</strong></div></div><div class="requirement ${techOk?"":"locked"}">Mining requirement: L${required} • ${tile.requiredMiningTech||this.resources.unlockName(tile)} ${techOk?"✓":"LOCKED"}</div>${paused?`<div class="requirement locked">Emergency Mode: Build/Ore extraction is paused. Normal rate would be ${formatNumber(nominalRate)}/day.</div>`:""}${this.state.status==="dead"?`<div class="requirement locked">This colony has been lost. Extraction is permanently disabled.</div>`:this.state.contract.ended?`<div class="requirement locked">This colony's mining contract has ended. Extraction is disabled.</div>`:""}`;
    if(!tile.depleted&&!tile.developed){const req=this.sites.developRequirements(this.state,tile);this.tilePanel.innerHTML+=`<button class="action" data-develop ${req.ok?"":"disabled"}>DEVELOP • ${formatMoney(req.cash)} + ${formatNumber(req.build)} BUILD</button>${req.ok?"":`<div class="requirement locked">${req.reason}</div>`}`;}else if(tile.developed){const req=this.sites.upgradeRequirements(this.state,tile);this.tilePanel.innerHTML+=`<button class="action" data-upgrade ${req.ok?"":"disabled"}>UPGRADE TO L${tile.level+1} • ${formatMoney(req.cash)} + ${formatNumber(req.build)} BUILD</button>${req.ok?"":`<div class="requirement locked">${req.reason}</div>`}`;}
    this.tilePanel.classList.remove("hidden");this.tilePanel.querySelector("[data-close]").onclick=()=>this.tilePanel.classList.add("hidden");const d=this.tilePanel.querySelector("[data-develop]");if(d)d.onclick=()=>{const r=this.sites.develop(this.state,tile);if(r.ok){this.onRecalculate?.();this.repo.save(this.state);this.toast("Site developed and collection started.");this.tile(tile)}else this.toast(r.reason)};const u=this.tilePanel.querySelector("[data-upgrade]");if(u)u.onclick=()=>{const r=this.sites.upgrade(this.state,tile);if(r.ok){this.onRecalculate?.();this.repo.save(this.state);this.toast(`Collection upgraded to L${tile.level}.`);this.tile(tile)}else this.toast(r.reason)};
    this.appendOverdriveCard(tile);
  }

  appendOverdriveCard(tile){
    if(!tile?.developed||!this.collection.supportsOverdrive(tile)||!this.tilePanel||this.tilePanel.classList.contains("hidden"))return;
    const panel=this.tilePanel,mode=operatingMode(tile),profile=OPERATING_MODES[mode],exposure=riskExposure(tile),shutdown=isAccidentShutdown(tile),accident=accidentDetails(tile),workers=this.colony.siteWorkforce(this.state,tile),last=tile.lastAccident;
    const card=document.createElement("article");card.className="card site-overdrive";
    if(shutdown){
      const days=Math.max(1,Math.ceil(Number(tile.accidentShutdownDays)||0)),outcome=last?.outcome==="fatalities"?`${last.deaths} colonist${last.deaths===1?"":"s"} killed`:`machinery damaged`;
      card.innerHTML=`<h3 class="bad">${last?.name||accident?.name||"Extraction Accident"}</h3><div class="grid2"><div class="metric"><small>Facility status</small><strong class="bad">SHUT DOWN</strong></div><div class="metric"><small>Reopens in</small><strong>${days} day${days===1?"":"s"}</strong></div></div><div class="requirement locked">${outcome}. The facility is automatically reset to NORMAL operation and cannot restart until the three-day safety shutdown is complete.</div>`;
    }else{
      card.innerHTML=`<h3>OPERATING LOAD</h3><div class="grid3"><div class="metric"><small>Mode</small><strong>${profile.label}</strong></div><div class="metric"><small>Workers</small><strong>${workers}</strong></div><div class="metric"><small>Risk exposure</small><strong>${exposure.toFixed(1)} / ${OVERDRIVE_RISK_PERIOD}</strong></div></div><div class="grid3 site-mode-buttons">${Object.values(OPERATING_MODES).map(p=>`<button data-site-mode="${p.key}" class="${p.key===mode?"active":""}">${p.label}<br><span class="tiny">${Math.round(p.workforce*100)}% staff • ${Math.round(p.output*100)}% output${p.key==="normal"?"":` • ${p.risk} risk`}</span></button>`).join("")}</div><div class="effect ${mode==="hard"?"warn":mode==="pushed"?"":"good"}">${mode==="normal"?"Normal operation reduces accumulated risk exposure by 1 day per operating day.":mode==="pushed"?"Pushed operation adds 0.3 risk-days per operating day, reaching a 25% accident check after about 100 continuous operating days.":"Hard operation adds 1 risk-day per operating day. Each 30 risk-days triggers a 25% accident check."}</div>${last?`<div class="effect">Last accident: ${last.name} • ${last.outcome==="fatalities"?`${last.deaths} fatalities`:"machinery damage"} • Y${last.year} D${last.day}</div>`:""}`;
    }
    panel.appendChild(card);
    if(!shutdown)card.querySelectorAll("[data-site-mode]").forEach(button=>button.onclick=()=>{const r=this.collection.setOperatingMode(this.state,tile,button.dataset.siteMode);if(!r.ok){this.toast(r.reason);return;}this.onRecalculate?.();this.repo.save(this.state);this.toast(`${tile.name}: ${r.profile.label} operation selected.`);this.tile(tile);});
  }

  currentCollection(){const rows=this.collection.current(this.state);if(!rows.length){this.open("Current Collection",`<article class="card"><h3>No active collection sites</h3><p>${this.state.status==="dead"?"This colony has been lost.":this.state.colony?.emergencyMode?"Emergency Mode has paused all non-essential extraction. Food and Fuel sites continue if available.":this.state.contract.ended?"This colony's mining contract has ended.":"Survey a resource tile and develop it to begin collection."}</p></article>`);return;}this.open("Current Collection",`<div class="collection-table"><div class="collection-row collection-head"><span>Resource</span><span>Category</span><span>Rate</span><span>Stock</span><span>Remaining</span></div>${rows.map(r=>`<div class="collection-row"><strong>${r.name}${r.sites>1?` ×${r.sites}`:""}</strong><span>${r.category}</span><span>${formatNumber(r.rate)}/d</span><span>${formatNumber(r.stock)}</span><span>${r.renewable?"Sustainable":formatNumber(r.remaining)}</span></div>`).join("")}</div>`);}
  company(){const c=this.state.company,t=c.tech,colonies=this.portfolio.entries(this.state),living=colonies.filter(e=>e.data?.status!=="dead").length,daily=colonies.reduce((sum,e)=>sum+(e.data?.metrics?.operatingCost||0),0);this.open("Mining Corporation",`<div class="grid2"><div class="metric"><small>Cash</small><strong>${formatMoney(c.cash)}</strong></div><div class="metric"><small>Lifetime trade earnings</small><strong>${formatMoney(c.earn)}</strong></div><div class="metric"><small>Completed contracts</small><strong>${c.wins}</strong></div><div class="metric"><small>Reputation</small><strong>${c.rep}</strong></div><div class="metric"><small>Colonies</small><strong>${living} operating / ${colonies.length} records</strong></div><div class="metric"><small>Portfolio operating cost</small><strong>${formatMoney(daily)}/d</strong></div><div class="metric"><small>Power technology</small><strong>L${t.power}</strong></div><div class="metric"><small>Food technology</small><strong>L${t.food}</strong></div><div class="metric"><small>Mining technology</small><strong>L${t.mining}</strong></div><div class="metric"><small>Current colony</small><strong>${this.state.contract.colonyName}</strong></div></div><button class="action" data-colonies>VIEW ALL COLONIES</button>`);this.modal.querySelector("[data-colonies]").onclick=()=>this.coloniesPanel();}
}
