import { formatMoney, formatNumber } from "../core/utils.js?v=5.0.0";

export class ResourceUIMixin {
  tile(tile){
    if(!tile.revealed){const days=this.survey.days(this.state,tile.x,tile.y),active=this.survey.isActive(this.state,tile.x,tile.y),queued=this.survey.isQueued(this.state,tile.x,tile.y);this.tilePanel.innerHTML=`${this.panelTitle(`Unsurveyed sector ${tile.x},${tile.y}`)}<div class="grid3"><div class="metric"><small>Scanner hint</small><strong class="survey">${this.world.hint(this.state,tile.x,tile.y)}</strong></div><div class="metric"><small>Survey time</small><strong>${days} days</strong></div><div class="metric"><small>Survey slots</small><strong>${this.state.scans.length}/${this.survey.slots(this.state)}</strong></div></div><button class="action" data-scan ${active||queued||this.state.contract.ended?"disabled":""}>${this.state.contract.ended?"CONTRACT ENDED":active?"SURVEY ACTIVE":queued?"QUEUED":"QUEUE SURVEY"}</button>`;this.tilePanel.classList.remove("hidden");this.tilePanel.querySelector("[data-close]").onclick=()=>this.tilePanel.classList.add("hidden");const scan=this.tilePanel.querySelector("[data-scan]");if(scan)scan.onclick=()=>{const r=this.survey.enqueue(this.state,tile.x,tile.y);if(r.ok){this.tilePanel.classList.add("hidden");this.toast(r.active?"Survey started.":"Added to survey queue.")}};return;}
    const rate=this.resources.collectionRate(this.state,tile),category=this.resources.categoryName(tile.type),cls=tile.type,renewable=this.resources.isRenewable(tile),life=tile.developed?this.resources.estimatedLifeYears(this.state,tile):null,remaining=renewable?"Sustainable":formatNumber(tile.reserve),lifeText=life===null?"—":renewable?"Permanent":life>=100?`${Math.round(life)}y`:`${life.toFixed(1)}y`,scale=renewable?(tile.abundanceLabel||"Sustainable"):(tile.depositScale||"Finite"),icon=this.icons.svg(tile.resourceId,this.icons.colorFor(tile),30,tile.type),required=tile.requiredMiningLevel||1,techOk=this.technology.canExploit(this.state,tile),stock=this.stockFor(tile);
    this.tilePanel.innerHTML=`${this.panelTitle(tile.depleted?`${tile.name} — DEPLETED`:tile.name,icon)}<div class="grid3"><div class="metric"><small>Category</small><strong class="${cls}">${category}</strong></div><div class="metric"><small>Rarity</small><strong>${tile.resourceRarity}</strong></div><div class="metric"><small>Quality</small><strong>${this.quality(tile.quality)}</strong></div><div class="metric"><small>Collection rate</small><strong class="${cls}">${formatNumber(rate)}/day</strong></div><div class="metric"><small>In stock</small><strong>${formatNumber(stock)}</strong></div><div class="metric"><small>Remaining</small><strong>${remaining}</strong></div><div class="metric"><small>${renewable?"Capacity":"Deposit"}</small><strong>${scale}</strong></div><div class="metric"><small>Est. life</small><strong>${lifeText}</strong></div><div class="metric"><small>Site level</small><strong>${tile.developed?`L${tile.level}`:"Undeveloped"}</strong></div></div><div class="requirement ${techOk?"":"locked"}">Mining requirement: L${required} • ${tile.requiredMiningTech||this.resources.unlockName(tile)} ${techOk?"✓":"LOCKED"}</div>${this.state.contract.ended?`<div class="requirement locked">This colony's mining contract has ended. Extraction is disabled.</div>`:""}`;
    if(!tile.depleted&&!tile.developed){const req=this.sites.developRequirements(this.state,tile);this.tilePanel.innerHTML+=`<button class="action" data-develop ${req.ok?"":"disabled"}>DEVELOP • ${formatMoney(req.cash)} + ${formatNumber(req.build)} BUILD</button>${req.ok?"":`<div class="requirement locked">${req.reason}</div>`}`;}else if(tile.developed){const req=this.sites.upgradeRequirements(this.state,tile);this.tilePanel.innerHTML+=`<button class="action" data-upgrade ${req.ok?"":"disabled"}>UPGRADE TO L${tile.level+1} • ${formatMoney(req.cash)} + ${formatNumber(req.build)} BUILD</button>${req.ok?"":`<div class="requirement locked">${req.reason}</div>`}`;}
    this.tilePanel.classList.remove("hidden");this.tilePanel.querySelector("[data-close]").onclick=()=>this.tilePanel.classList.add("hidden");const d=this.tilePanel.querySelector("[data-develop]");if(d)d.onclick=()=>{const r=this.sites.develop(this.state,tile);if(r.ok){this.onRecalculate?.();this.repo.save(this.state);this.toast("Site developed and collection started.");this.tile(tile)}else this.toast(r.reason)};const u=this.tilePanel.querySelector("[data-upgrade]");if(u)u.onclick=()=>{const r=this.sites.upgrade(this.state,tile);if(r.ok){this.onRecalculate?.();this.repo.save(this.state);this.toast(`Collection upgraded to L${tile.level}.`);this.tile(tile)}else this.toast(r.reason)};
  }
  currentCollection(){const rows=this.collection.current(this.state);if(!rows.length){this.open("Current Collection",`<article class="card"><h3>No active collection sites</h3><p>${this.state.contract.ended?"This colony's mining contract has ended.":"Survey a resource tile and develop it to begin collection."}</p></article>`);return;}this.open("Current Collection",`<div class="collection-table"><div class="collection-row collection-head"><span>Resource</span><span>Category</span><span>Rate</span><span>Stock</span><span>Remaining</span></div>${rows.map(r=>`<div class="collection-row"><strong>${r.name}${r.sites>1?` ×${r.sites}`:""}</strong><span>${r.category}</span><span>${formatNumber(r.rate)}/d</span><span>${formatNumber(r.stock)}</span><span>${r.renewable?"Sustainable":formatNumber(r.remaining)}</span></div>`).join("")}</div>`);}
  company(){const c=this.state.company,t=c.tech,colonies=this.portfolio.entries(this.state),daily=colonies.reduce((sum,e)=>sum+(e.data?.metrics?.operatingCost||0),0);this.open("Mining Corporation",`<div class="grid2"><div class="metric"><small>Cash</small><strong>${formatMoney(c.cash)}</strong></div><div class="metric"><small>Lifetime trade earnings</small><strong>${formatMoney(c.earn)}</strong></div><div class="metric"><small>Completed contracts</small><strong>${c.wins}</strong></div><div class="metric"><small>Reputation</small><strong>${c.rep}</strong></div><div class="metric"><small>Owned colonies</small><strong>${colonies.length}</strong></div><div class="metric"><small>Portfolio operating cost</small><strong>${formatMoney(daily)}/d</strong></div><div class="metric"><small>Power technology</small><strong>L${t.power}</strong></div><div class="metric"><small>Food technology</small><strong>L${t.food}</strong></div><div class="metric"><small>Mining technology</small><strong>L${t.mining}</strong></div><div class="metric"><small>Current colony</small><strong>${this.state.contract.colonyName}</strong></div></div><button class="action" data-colonies>VIEW ALL COLONIES</button>`);this.modal.querySelector("[data-colonies]").onclick=()=>this.coloniesPanel();}
}
