import { formatMoney, formatNumber } from "../core/utils.js?v=5.3.0";
import { CONFIG } from "../core/config.js?v=5.3.0";

const TECH_LABELS={power:"POWER",food:"FOOD PRODUCTION",mining:"MINING"};
const CATEGORY_HELP={
  Food:"Food is the primary survival resource. Every colonist consumes Food every day. A sustained shortage eventually kills population.",
  Build:"Build material is construction stock. It is spent on sites, housing and Industry rather than consumed every day.",
  Fuel:"Fuel turns Power technology into usable colony power. A Fuel shortage becomes a Power shortage and can therefore kill a colony.",
  Ore:"Ore feeds Industry. Ore shortages reduce economic output but do not directly kill colonists."
};

export class SurvivalUIMixin {
  colonyLost(){const living=this.state.portfolio.colonies.filter(entry=>entry.data?.status!=="dead").length;this.open("Colony Lost",`<article class="card"><h3 class="bad">${this.state.contract.colonyName} HAS BEEN LOST</h3><p>The population reached zero after life-support failure. Extraction, Industry and the mining charter are permanently ended on this world.</p><div class="effect warn">${living?`${living} other operating colon${living===1?"y":"ies"} remain. Switch to one of them to continue the corporation.`:"No operating colonies remain."}</div></article>${living?`<button class="action" data-lost-colonies>VIEW SURVIVING COLONIES</button>`:""}`);const button=this.modal.querySelector("[data-lost-colonies]");if(button)button.onclick=()=>this.coloniesPanel();}
  gameOver(){this.state.company.gameOver=true;this.repo.save(this.state);this.open("Corporation Failed",`<article class="card"><h3 class="bad">ALL COLONIES LOST</h3><p>Your corporation has no surviving population on any world. Mining operations have ended.</p><div class="effect warn">A new corporation starts again with Contract 01. The old dead-colony records remain only until the reset is confirmed.</div></article><div class="grid2"><button data-gameover-colonies>VIEW COLONIES</button><button data-gameover-reset class="bad">START NEW CORPORATION</button></div>`);this.modal.querySelector("[data-gameover-colonies]").onclick=()=>this.coloniesPanel();this.modal.querySelector("[data-gameover-reset]").onclick=()=>this.onHardReset();}
  help(){
    const bands=this.resources.qualityBands(),catalog=this.resources.catalog(),price=v=>v<10?`£${Number(v).toFixed(2)}`:formatMoney(v),section=(id,title,body)=>`<section class="help-section" id="help-${id}"><div class="help-section-title"><h3>${title}</h3><button data-help-target="help-index">↑ INDEX</button></div>${body}</section>`;
    const resources=["Food","Build","Fuel","Ore"].map(category=>{const items=catalog.filter(r=>r.category===category);return`<div class="help-resource-category"><h4 class="${category.toLowerCase()}">${category}</h4><p>${CATEGORY_HELP[category]}</p><div class="help-resource-table">${items.map(r=>`<div class="help-resource-row"><strong>${r.name}</strong><span>${r.rarity}</span><span>${r.manufactured?"Manufactured":r.renewable?"Renewable":"Finite"}</span><span>M${r.miningLevel||1}</span><span>${price(this.resources.baseSellPrice(r.type,r.id))}/u</span><small>${r.unlock||"Surface Recovery"}</small></div>`).join("")}</div></div>`;}).join("");
    const qualityRows=bands.map(b=>`<div class="help-data-row"><strong class="${b.className}">${b.label}</strong><span>Q${formatNumber(b.min)}–${formatNumber(b.max)}</span><span>×${b.multiplier.toFixed(2)} sale value</span></div>`).join("");
    const techRows=["power","food","mining"].map(cat=>`<div class="help-tech-block"><h4>${TECH_LABELS[cat]}</h4>${this.technology.tree(cat).map(t=>`<div class="help-tech-row"><strong>L${t.level} ${t.name}</strong><span>${t.level===1?"Starting technology":formatMoney(t.cost)}</span><small>${this.techEffect(cat,t)}</small></div>`).join("")}</div>`).join("");
    const indexItems=[["overview","Objective"],["survival","Survival & death"],["expansion","Population expansion"],["industry","Industry staffing"],["controls","Screen & controls"],["survey","Surveying"],["map","Map & filters"],["resources","All resources"],["quality","Quality & value"],["deposits","Deposit size"],["sites","Sites & upgrades"],["emergency","Emergency Mode"],["environment","World support load"],["tech","Technology"],["trade","Trade ship & cargo"],["contracts","Contracts & scoring"],["portfolio","Multiple colonies"],["liability","Liability colonies"],["save","Saving & diagnostics"]];
    const body=`<div class="help-manual"><div class="help-index" id="help-index"><article class="card"><h3>MINEIT FIELD MANUAL</h3><p>MineIT is a survival-focused mining-corporation game. Expansion creates risk: larger populations and Industry increase Food, Fuel, Ore, Power and cash pressure. A badly managed colony can now die permanently.</p></article><div class="help-index-grid">${indexItems.map(([id,label])=>`<button data-help-target="help-${id}">${label}</button>`).join("")}</div></div>
    ${section("overview","1. Objective & game loop",`<p>Accept a colony charter, survey the world, develop local Food/Fuel/Ore/Build production, keep life support stable, deliberately expand population, grow Industry and trade valuable surplus stock for corporation cash.</p><p>Cash and Power/Food/Mining technology belong to the corporation and are shared by every colony. Population, inventory, map, sites, contract age, support load and survival risk are local to each colony.</p><p>The first 10-year contract is only the beginning. After a successful charter you can retain that colony and establish additional worlds. The long-term challenge is keeping a growing portfolio alive and profitable.</p>`)}
    ${section("survival","2. Survival, shortages & colony death",`<p><strong>Food and Power are lethal needs.</strong> A colony at roughly 90%+ effective Food/Power supply is stable. Below 90% it becomes strained and meaningful natural population growth stops. Below 70% deaths begin. Below 40% mortality accelerates sharply.</p><p>Shortages do not kill instantly. Stored resources provide reaction time, and the Colony screen shows estimated net days remaining. At zero Food or viable Power a population can collapse over months if the problem is not solved.</p><p>Population can reach <strong>zero</strong>. At zero the colony is permanently lost: the charter fails, extraction and Industry stop, corporate trade service ends and the colony no longer consumes resources or operating cash. Corporation reputation also takes a penalty.</p><p>If other colonies survive, the corporation continues. If every colony dies, the corporation reaches GAME OVER and must be reset.</p>`)}
    ${section("expansion","3. Population expansion & colonist transfers",`<p>Housing no longer fills itself quickly. Natural growth is intentionally very slow. Meaningful expansion comes from <strong>Colonist Transfer</strong> when the corporate ship docks.</p><p>Each ship visit has ${CONFIG.TRADE_PASSENGER_CAPACITY} passenger berths. Transfers are offered in +50, +100 and +250 groups. You must have supported housing capacity and enough corporation cash.</p><p>Transfer cost starts at ${formatMoney(CONFIG.COLONIST_TRANSFER_COST)} per colonist and is multiplied by the world's environmental support load, so sending people to Frozen, Barren, Volcanic or Deep Reach worlds costs more.</p><p>The strategic question is not merely whether housing exists: check Food/Fuel runway and Power capacity before accepting more people. Expansion raises demand immediately.</p>`)}
    ${section("industry","4. Industry & population staffing",`<p>Industry now needs population to operate effectively. Every Industry level has a population requirement for 100% staffing. The Colony screen shows the current staffing percentage and population required.</p><p>You may build Industry ahead of population, but output is multiplied by staffing. An understaffed L6 complex might perform like a much smaller industrial base until more colonists arrive.</p><p>Industry also needs Power and Ore. Effective Industry is therefore limited by the weakest of staffing, Power availability and Ore supply. In Emergency Mode Industry falls to zero.</p><p>Population loss is consequently an economic problem as well as a survival problem: deaths can pull a mature colony below the staffing needed for its infrastructure.</p>`)}
    ${section("controls","5. Screen, time & controls",`<div class="help-bullets"><p><strong>Top:</strong> current contract Food Production, Industry and Population goals.</p><p><strong>Map:</strong> drag to pan, tap an unsurveyed tile to survey, tap a revealed tile for details, or hold + drag to queue several surveys.</p><p><strong>Footer:</strong> corporation Cash and quality-adjusted Stock Value, followed by the current colony's Food, Build, Fuel and Ore stocks.</p><p><strong>COLLECT:</strong> currently operating extraction. <strong>SHIP:</strong> trade/import/colonist transfer. <strong>COLONY:</strong> survival, runway, infrastructure and Emergency Mode. <strong>COLONIES:</strong> switch worlds. <strong>TECH:</strong> permanent corporate licences.</p></div>`)}
    ${section("survey","6. Surveying & discovery",`<p>Surveys reveal resource type, rarity, exact quality, deposit/abundance size and Mining technology requirement. Distance and world scan difficulty increase survey time.</p><p>Mining technology gradually reduces scan time, improves scanner hints and increases concurrent survey slots from one up to five. Survey queues fill automatically when a slot becomes free.</p><p>Surveying is disabled after mining rights end and on dead colonies.</p>`)}
    ${section("map","7. Map tiles & filters",`<p>Revealed tiles show the resource icon, exact Q value and deposit size or renewable abundance. Developed finite sites also show depletion. Mining-tech-locked discoveries are ghosted but remain tappable.</p><p>Map visibility uses three independent multi-select groups: <strong>State</strong> (Developed / Not Developed / Locked), <strong>Size</strong> and the six <strong>Quality</strong> bands. A tile must pass all selected groups to appear. Unsurveyed sectors and the ship remain visible regardless.</p>`)}
    ${section("resources","8. Resource catalogue",`<p>The four categories have intentionally different consequences: Food keeps population alive; Fuel keeps Power alive; Ore keeps Industry productive; Build pays for expansion. Base sale price below is before quality multiplier.</p>${resources}`)}
    ${section("quality","9. Quality, production & sale value",`<p>Natural resources have Q1–Q10,000. Base extraction is now approximately <strong>2 + 2 × Q^0.42</strong> before resource, abundance, site-level and technology multipliers. This makes poor sites genuinely limited while preserving strong advantages for exceptional discoveries.</p><div class="help-data-table">${qualityRows}</div><p>Harvested inventory is grouped into these six quality-price bands. The ship sells each band at its own multiplier. Colony Food/Fuel/Ore consumption uses the cheapest grades first where possible.</p>`)}
    ${section("deposits","10. Deposit size, renewables & depletion",`<p>Finite deposits are Small, Modest, Large, Huge or Colossal. Their class describes original size; extraction reduces reserve until the site is depleted and stops producing.</p><p>Renewable resources are Limited, Established, Large or Vast and display ∞. They never deplete, but abundance directly changes throughput. A Limited low-Q Food source may no longer be enough for a growing colony.</p>`)}
    ${section("sites","11. Developing & upgrading sites",`<p>Surveying discovers a resource; development requires the correct Mining technology plus corporation cash and Build material. Costs still rise with quality, distance and world difficulty.</p><p>Developed sites collect automatically each day. Site upgrades increase output by roughly 22% per level after L1, making upgrades an alternative to spreading across many mediocre deposits.</p><p>Food technology multiplies Food extraction. Mining technology multiplies Build, Fuel and Ore extraction. During Emergency Mode only Food and Fuel sites remain operational.</p>`)}
    ${section("emergency","12. Emergency Mode",`<p>Emergency Mode is the colony's simple crisis control. It shuts down Industry plus Build/Ore extraction, keeps Food and Fuel extraction running, and reduces life-support power demand and operating cost.</p><p>Use it when Fuel or Food runway is collapsing, when a sudden population increase was too aggressive, or while waiting for a corporate ship. The trade-off is severe: Industry output becomes zero and non-essential resources stop accumulating.</p><p>Exit Emergency Mode once the survival position is secure. Leaving it on permanently sacrifices contract Industry progress and economic growth.</p>`)}
    ${section("environment","13. Environmental support load",`<p>World type now has an ongoing support multiplier rather than being only flavour text. Typical load ranges from about ×0.90 on Verdant worlds to ×2.00 in Deep Reach vacuum.</p><p>Support load increases life-support Power demand, daily operating cost and colonist transfer cost. A Frozen or Barren colony therefore needs more Fuel and cash to support the same population than a Temperate colony.</p>`)}
    ${section("tech","14. Corporation technology",`<p>Power, Food and Mining licences are permanent corporation assets shared by every colony. Technology remains intentionally expensive at higher levels.</p><p>Power raises generation capacity, population cap and Industry cap while reducing Fuel intensity. Food raises natural Food output and unlocks increasing synthetic Food. Mining unlocks deposits, increases extraction and improves surveys.</p><p>Hide Future Tech always keeps NEXT visible; Hide Old Tech removes already-purchased levels below CURRENT.</p>${techRows}`)}
    ${section("trade","15. Corporate trade ship, cargo & imports",`<p>The ship normally arrives every ${CONFIG.TRADE_INTERVAL_DAYS} days and pauses time while docked. Sell quality-banded resources, buy emergency supplies, purchase ship-only technology and transfer colonists before departure.</p><p>Imports are no longer unlimited. Base import cargo is <strong>${formatNumber(CONFIG.TRADE_BASE_CARGO)} units per visit</strong>, increasing by ${formatNumber(CONFIG.TRADE_CARGO_PER_REP)} per reputation point up to ${formatNumber(CONFIG.TRADE_MAX_CARGO)}. Every imported resource unit consumes one cargo unit.</p><p>Imports are therefore a rescue and balancing tool, not a permanent replacement for local production. Bought resources enter as Excellent/base-grade stock and do not count toward local production goals.</p>`)}
    ${section("contracts","16. Contracts, goals & scoring",`<p>The initial charter lasts 10 years. Goals measure current local Food production, effective Industry and population; contract profit is local trade revenue minus tracked colony costs.</p><p>Bronze requires all objectives. Silver, Gold and Platinum add increasing profit and over-performance thresholds. Missing the deadline permits up to ${CONFIG.MAX_EXTENSIONS} paid one-year extensions; exhausting them ends mining rights and turns the colony into a liability.</p><p>After successful completion you may renew in ${CONFIG.RENEWAL_YEARS}-year blocks, operate temporarily on more expensive holdover terms, open another colony, or attempt a return.</p>`)}
    ${section("portfolio","17. Multiple colonies & background simulation",`<p>Every colony has independent population, inventory, sites, support load, contract clock and survival position. Switching maps does not freeze other worlds: operating colonies continue producing, consuming and paying costs in the background.</p><p>The COLONIES panel shows status plus Food/Fuel/Ore runway. DEAD colonies remain visible as failed records until abandoned. A background colony can die while you are managing another world, so yellow/red portfolio warnings matter.</p>`)}
    ${section("liability","18. Returns, liability colonies & death",`<p>After a completed contract the corporation may accept a colony back if enough surveyed resource value remains. A heavily depleted world may be refused.</p><p>If you end a refused contract, the colony becomes a support-only liability. Extraction stops but population still consumes Food, Fuel and Ore and operating costs are higher. Emergency Mode still works.</p><p>A liability colony is no longer immortal: if Food or Power fails, its population can reach zero. Alternatively, if another colony exists, you can pay the expensive relocation cost and close the liability safely.</p>`)}
    ${section("save","19. Saving, reset & diagnostics",`<p>The game saves to browser storage and periodically auto-saves. Save Now forces an immediate save. The portfolio, dead-colony records, emergency state, ship cargo/passenger use and survival stocks persist.</p><p>Diagnostics records startup/runtime errors and simulation information. Hard Reset permanently erases all MineIT data on this browser and creates a fresh Contract 01 corporation.</p>`)}
    </div>`;
    this.open("How to Play",body);this.modal.querySelectorAll("[data-help-target]").forEach(button=>button.onclick=()=>{const target=this.modal.querySelector(`#${button.dataset.helpTarget}`);target?.scrollIntoView({behavior:"smooth",block:"start"});});
  }
}
