import { CONFIG } from "../core/config.js";
import { formatMoney, formatNumber } from "../core/utils.js";
export class TradeUI{
  constructor({state,trade,repo,ui}){Object.assign(this,{state,trade,repo,ui});this.button=document.querySelector("#tradeBtn");this.button.onclick=()=>state.trade.active?this.open():this.status();document.querySelectorAll("[data-speed]").forEach(button=>{button.onclick=()=>{if(state.trade.active&&+button.dataset.speed>0){ui.toast("Corporate ship is docked. Depart before resuming time.");return}state.speed=+button.dataset.speed;ui.syncSpeed();this.render()}});}
  price(v){return v<10?`£${v.toFixed(2)}`:formatMoney(v);}
  qualityRange(band){return `${formatNumber(band.min)}–${formatNumber(band.max)}`;}
  render(){const stockValue=document.querySelector("#income");if(stockValue)stockValue.textContent=formatMoney(this.trade.stockValue(this.state));this.button.classList.toggle("trade-live",this.state.trade.active);this.button.textContent=this.state.trade.active?"TRADE!":`SHIP ${formatNumber(this.trade.daysUntilArrival(this.state))}d`;document.querySelectorAll("[data-speed]").forEach(button=>button.disabled=this.state.trade.active&&+button.dataset.speed>0);}
  status(){this.ui.open("Corporate Trade Ship",`<article class="card"><h3>NEXT VISIT IN ${formatNumber(this.trade.daysUntilArrival(this.state))} DAYS</h3><p>A corporate vessel arrives every ${CONFIG.TRADE_INTERVAL_DAYS} days. Food, Build, Fuel and Ore remain in colony storage until used or sold. Harvested stock keeps its quality band, which changes its sale value.</p><div class="grid2"><div class="metric"><small>Stored stock value</small><strong>${formatMoney(this.trade.stockValue(this.state))}</strong></div><div class="metric"><small>Completed visits</small><strong>${this.state.trade.visits}</strong></div></div></article>`);}
  sellMarkup(stock){return stock.map(e=>`<article class="trade-resource-group"><div class="trade-resource-head"><strong>${e.name}</strong><span>${formatNumber(e.amount)}</span></div><div class="trade-quality-list">${this.trade.qualityRows(e).map(b=>`<div class="trade-quality-row"><span class="trade-quality-name ${b.className}"><strong>${b.label}</strong><small>Q${this.qualityRange(b)} • ×${b.multiplier.toFixed(2)}</small></span><span class="trade-quality-qty">${formatNumber(b.amount)}</span><span class="trade-quality-price">${this.price(b.unitPrice)}/u</span><span class="trade-actions"><button data-band-sell="25" data-stock-key="${e.key}" data-band-key="${b.key}">25%</button><button data-band-sell="100" data-stock-key="${e.key}" data-band-key="${b.key}">ALL</button></span></div>`).join("")}</div></article>`).join("");}
  open(selectedKey=null){
    if(!this.state.trade.active){this.status();return}const stock=this.trade.stock(this.state),catalog=this.trade.catalog(),selected=catalog.find(x=>x.key===selectedKey)||catalog[0],buyPrice=this.trade.buyPrice(selected);
    this.ui.open("Corporate Trade Ship — DOCKED",`<div class="trade-summary"><div class="metric"><small>Cash</small><strong>${formatMoney(this.state.company.cash)}</strong></div><div class="metric"><small>Stock value</small><strong>${formatMoney(this.trade.stockValue(this.state))}</strong></div><div class="metric"><small>Technology link</small><strong>ONLINE</strong></div></div><section class="trade-section"><h3>SELL COLONY STOCK</h3>${stock.length?`<div class="trade-quality-table">${this.sellMarkup(stock)}</div>`:`<div class="card"><p>No stored resources available to sell.</p></div>`}</section><section class="trade-section"><h3>BUY FROM CORPORATION</h3><div class="trade-buy"><button class="trade-resource-select" data-resource-picker><span><small>Selected resource</small><strong>${selected.name}</strong><em>${selected.category} • ${selected.rarity}</em></span><span class="trade-resource-price">${this.price(buyPrice)}/u <b>▾</b></span></button><div class="trade-buy-buttons"><button data-buy="100" ${this.state.company.cash<buyPrice*100?"disabled":""}>BUY 100</button><button data-buy="1000" ${this.state.company.cash<buyPrice*1000?"disabled":""}>BUY 1K</button><button data-buy="10000" ${this.state.company.cash<buyPrice*10000?"disabled":""}>BUY 10K</button></div><div class="trade-note">Purchased resources enter colony storage immediately as Excellent/base-grade stock (×1.00). They can feed the population, provide Build material, power the colony or supply industry, but they do not count as local production.</div></div></section><div class="trade-footer"><button data-all ${stock.length?"":"disabled"}>SELL ALL</button><button data-tech-link>TECH LICENSES</button><button data-depart class="warn">SHIP DEPARTS</button></div>`);
    const modal=this.ui.modal;modal.querySelector("[data-resource-picker]").onclick=()=>this.openResourcePicker(selected.key);modal.querySelectorAll("[data-band-sell]").forEach(b=>b.onclick=()=>{const entry=this.state.inventory[b.dataset.stockKey],band=entry?.qualityBands?.[b.dataset.bandKey],pct=+b.dataset.bandSell/100,r=this.trade.sellBand(this.state,b.dataset.stockKey,b.dataset.bandKey,(band?.amount||0)*pct);if(r.ok){this.ui.toast(`Sold ${formatNumber(r.qty)} ${band?.label||"stock"} for ${formatMoney(r.revenue)}.`);this.open(selected.key)}else this.ui.toast(r.reason)});modal.querySelectorAll("[data-buy]").forEach(b=>b.onclick=()=>{const r=this.trade.buy(this.state,selected.key,+b.dataset.buy);if(r.ok){this.ui.toast(`Bought ${formatNumber(r.qty)} ${r.entry.name}.`);this.open(selected.key)}else this.ui.toast(r.reason)});modal.querySelector("[data-all]").onclick=()=>{const r=this.trade.sellAll(this.state);if(r.ok){this.ui.toast(`Sold all stock for ${formatMoney(r.revenue)}.`);this.open(selected.key)}};modal.querySelector("[data-tech-link]").onclick=()=>this.ui.tech();modal.querySelector("[data-depart]").onclick=()=>{this.trade.depart(this.state);modal.classList.add("hidden");this.ui.syncSpeed();this.render();this.repo.save(this.state);this.ui.toast(`Trade ship departed • next visit in ${CONFIG.TRADE_INTERVAL_DAYS} days.`)};
  }
  openResourcePicker(selectedKey){const catalog=this.trade.catalog(),categories=["Food","Build","Fuel","Ore"],layer=document.createElement("div");layer.className="resource-picker-backdrop";layer.innerHTML=`<section class="resource-picker" role="dialog" aria-modal="true"><div class="resource-picker-header"><div><small>CORPORATE INVENTORY</small><strong>Select Resource</strong></div><button class="close" data-picker-close>✕</button></div><div class="resource-picker-list">${categories.map(category=>{const items=catalog.filter(i=>i.category===category);return`<div class="resource-picker-category">${category}</div>${items.map(item=>`<button class="resource-picker-row ${item.key===selectedKey?"selected":""}" data-resource-key="${item.key}"><span class="resource-picker-name"><strong>${item.name}</strong><small>${item.rarity}</small></span><span class="resource-picker-buy"><small>BUY</small><strong>${this.price(this.trade.buyPrice(item))}/u</strong></span></button>`).join("")}`}).join("")}</div></section>`;this.ui.modal.appendChild(layer);layer.querySelector("[data-picker-close]").onclick=()=>layer.remove();layer.onclick=e=>{if(e.target===layer)layer.remove()};layer.querySelectorAll("[data-resource-key]").forEach(b=>b.onclick=()=>this.open(b.dataset.resourceKey));}
}
