import { CONFIG } from "../core/config.js";
import { clamp, formatMoney, formatNumber } from "../core/utils.js";
import { renderViewTemplate } from "../core/view-template.js";
import { ContractUIMixin } from "./contract-ui.js";
import { IndustryUIMixin } from "./industry-ui.js";
import { UIEnhancementsMixin } from "./ui-enhancements.js";

const TECH_LABELS={power:"POWER",food:"FOOD PRODUCTION",mining:"MINING"};
export class V55UIMixin {
  logEvent(type,message,data={}){return this.gameLog?.event(this.state,type,message,data);}
  render(){ContractUIMixin.prototype.render.call(this);const elapsed=this.contracts.contractAgeDays(this.state),deadline=this.contracts.deadlineDays(this.state);document.querySelector("#timeBar").style.width=`${clamp(elapsed/Math.max(1,deadline)*100,0,100)}%`;document.querySelector("#dateText").textContent=`CORP Y${this.state.year} D${this.state.day}`;}
  colonyPanel(){
    IndustryUIMixin.prototype.colonyPanel.call(this);if(this.state.status==="dead")return;const body=this.modal.querySelector(".modal-body");if(!body)return;const m=this.state.metrics,available=Math.max(0,Number(m.workforceAvailable)||0),required=Math.max(0,Number(m.workforceRequired)||0),free=Math.max(0,Number(m.workforceFree)||0),shortfall=Math.max(0,Number(m.workforceShortfall)||0),orders=this.transport?.ensure(this.state)||[],ageY=this.contracts.contractYear(this.state),ageD=this.contracts.contractDay(this.state),supported=this.transport?.availableCapacity(this.state)||0;
    const industrial=body.querySelector(".need-grid")?.previousElementSibling;industrial?.insertAdjacentHTML("afterend",`<article class="card" style="margin-top:7px"><h3>OPERATIONAL WORKFORCE ${shortfall>0?`<span class="bad">— SHORTFALL</span>`:""}</h3><div class="grid2"><div class="metric"><small>Available workforce</small><strong>${formatNumber(available)}</strong></div><div class="metric"><small>Required by sites</small><strong>${formatNumber(required)}</strong></div><div class="metric"><small>Free for expansion</small><strong>${formatNumber(free)}</strong></div><div class="metric"><small>Contract age</small><strong>Y${ageY} D${ageD}</strong></div></div><p>About ${Math.round(CONFIG.WORKFORCE_SHARE*100)}% of population is available for resource operations. Food and Fuel are staffed first; Build and Ore are automatically throttled if workers become scarce.</p></article>`);
    const management=body.querySelector(".colony-management");if(management){const pending=orders.length?`<div class="help-data-table">${orders.map(o=>`<div class="help-data-row"><strong>+${formatNumber(o.amount)} colonists</strong><span>${formatNumber(this.transport.daysRemaining(this.state,o))}d ETA</span><span>${formatMoney(o.cost)}</span></div>`).join("")}</div>`:`<p>No dedicated colony transports are currently inbound.</p>`,blocked=this.state.contract.ended||this.state.status==="liability";management.insertAdjacentHTML("beforebegin",`<article class="card" style="margin-top:7px"><h3>DEDICATED COLONY TRANSPORT</h3><p>Request any supported population increase without waiting for the regular trade ship. Transport takes ${CONFIG.DEDICATED_TRANSPORT_DAYS} days and the cost is paid when ordered.</p><div class="grid2"><div class="metric"><small>Supported places available</small><strong>${formatNumber(supported)}</strong></div><div class="metric"><small>Pending colonists</small><strong>${formatNumber(this.transport.pendingPopulation(this.state))}</strong></div></div>${pending}${blocked?`<div class="requirement locked">This colony cannot receive new colonists.</div>`:`<div class="trade-buy-buttons" style="margin-top:6px"><button data-transport="100" ${supported<100?"disabled":""}>+100</button><button data-transport="500" ${supported<500?"disabled":""}>+500</button><button data-transport="1000" ${supported<1000?"disabled":""}>+1,000</button><button data-transport="max" ${supported<1?"disabled":""}>MAX</button></div><div style="display:grid;grid-template-columns:1fr auto;gap:4px;margin-top:5px"><input data-transport-custom type="number" min="1" max="${Math.max(1,supported)}" step="1" inputmode="numeric" placeholder="Custom colonists" style="min-width:0;background:#0b1116;color:var(--text);border:1px solid var(--line);border-radius:7px;padding:5px"><button data-transport-request>REQUEST</button></div>`}</article>`);}
    body.querySelectorAll("[data-transport]").forEach(button=>button.onclick=()=>{const qty=button.dataset.transport==="max"?this.transport.availableCapacity(this.state):+button.dataset.transport;this.requestTransport(qty)});const custom=body.querySelector("[data-transport-request]");if(custom)custom.onclick=()=>this.requestTransport(+body.querySelector("[data-transport-custom]").value);
    for(const selector of["[data-housing]","[data-industry]","[data-emergency]"]){const button=body.querySelector(selector);if(!button||button.dataset.logged55)return;button.dataset.logged55="1";const original=button.onclick;button.onclick=e=>{const before={housing:this.state.colony.housingLevel,industry:this.state.colony.industryLevel,emergency:this.state.colony.emergencyMode};original?.call(button,e);if(this.state.colony.housingLevel!==before.housing)this.logEvent("housing-expanded",`Housing expanded to level ${this.state.colony.housingLevel}.`,{housingLevel:this.state.colony.housingLevel,housingCapacity:this.state.colony.housingCapacity});if(this.state.colony.industryLevel!==before.industry)this.logEvent("industry-expanded",`Industry expanded to L${this.state.colony.industryLevel}.`,{industryLevel:this.state.colony.industryLevel});if(this.state.colony.emergencyMode!==before.emergency)this.logEvent("emergency-mode",`Emergency Mode ${this.state.colony.emergencyMode?"enabled":"disabled"}.`,{enabled:this.state.colony.emergencyMode});this.repo.save(this.state);};}
  }
  requestTransport(amount){const r=this.transport.request(this.state,amount);if(!r.ok){this.toast(r.reason);return}this.logEvent("transport-ordered",`Dedicated transport ordered for ${formatNumber(r.amount)} colonists; ETA ${CONFIG.DEDICATED_TRANSPORT_DAYS} days.`,{quantity:r.amount,cost:r.cost,arrivalDay:r.arrivalDay});this.repo.save(this.state);this.toast(`${formatNumber(r.amount)} colonists ordered • ETA ${CONFIG.DEDICATED_TRANSPORT_DAYS}d • ${formatMoney(r.cost)}`);this.colonyPanel();}
  currentCollection(){IndustryUIMixin.prototype.currentCollection.call(this);const body=this.modal.querySelector(".modal-body"),m=this.state.metrics;if(!body)return;const wf=Math.min(m.workforceSurvivalFactor??1,m.workforceCommercialFactor??1);if(wf<.999)body.insertAdjacentHTML("afterbegin",`<div class="requirement locked">WORKFORCE SHORTAGE — resource operations are automatically prioritising Food/Fuel. Commercial extraction may be reduced.</div>`);}
  tile(tile){
    IndustryUIMixin.prototype.tile.call(this,tile);if(!tile?.revealed)return;const firstReq=this.tilePanel.querySelector(".requirement");if(!firstReq)return;const developed=!!tile.developed,workers=this.colony.siteWorkforce(this.state,{...tile,level:Math.max(1,tile.level||1)}),nextWorkers=developed?this.colony.siteWorkforce(this.state,{...tile,level:(tile.level||1)+1}):workers,free=this.colony.freeWorkforce(this.state),fullRate=this.resources.sitePotentialRate({...tile,level:Math.max(1,tile.level||1)});firstReq.insertAdjacentHTML("afterend",`<div class="effect">Operational workforce: ${formatNumber(workers)}${developed?` • next level ${formatNumber(nextWorkers)} (${formatNumber(Math.max(0,nextWorkers-workers))} additional)`:""} • ${formatNumber(free)} currently free</div><div class="effect">Site-driven throughput: ${formatNumber(fullRate)}/day before workforce / Industry throttling. Quality affects sale value, not extraction speed.</div>`);
    if(this.resources.isRenewable(tile)&&developed&&!tile.renewableWiped){this.resources.ensureRenewable(tile);const sustainable=this.resources.sustainableRate(tile),intensity=Math.round((tile.harvestIntensity||1)*100),condition=this.resources.renewableCondition(tile),over=intensity>100;firstReq.insertAdjacentHTML("afterend",`<article class="card" style="margin-top:5px"><h3>RENEWABLE HARVEST ${over?`<span class="warn">— OVER-FARMING</span>`:""}</h3><div class="grid2"><div class="metric"><small>Harvest intensity</small><strong>${intensity}%</strong></div><div class="metric"><small>Sustainable yield</small><strong>${formatNumber(sustainable)}/d</strong></div><div class="metric"><small>Ecological size</small><strong>${condition.label}</strong></div><div class="metric"><small>Current potential</small><strong>${formatNumber(this.resources.sitePotentialRate(tile))}/d</strong></div></div><p>${over?"Harvest above 100% degrades this resource over time. Continued pressure can reduce its size and eventually wipe it out permanently.":intensity<100?"Harvesting below sustainable yield allows a previously damaged resource to recover slowly, up to its original surveyed size.":"At 100% this site is harvesting at its sustainable yield."}</p><div class="grid2"><button data-harvest-down ${intensity<=25?"disabled":""}>−25%</button><button data-harvest-up ${intensity>=200?"disabled":""}>+25%</button></div></article>`);const adjust=delta=>{const before=Math.round((tile.harvestIntensity||1)*100),after=clamp(before+delta,25,200);tile.harvestIntensity=after/100;this.onRecalculate?.();this.logEvent("harvest-intensity",`${tile.name} harvest changed from ${before}% to ${after}%.`,{x:tile.x,y:tile.y,resource:tile.name,before,after,sustainableRate:this.resources.sustainableRate(tile)});this.repo.save(this.state);this.tile(tile)};this.tilePanel.querySelector("[data-harvest-down]").onclick=()=>adjust(-25);this.tilePanel.querySelector("[data-harvest-up]").onclick=()=>adjust(25);}
    for(const selector of["[data-develop]","[data-upgrade]"]){const button=this.tilePanel.querySelector(selector);if(!button||button.dataset.logged55)return;button.dataset.logged55="1";const original=button.onclick;button.onclick=e=>{const wasDeveloped=tile.developed,beforeLevel=tile.level,beforeCash=this.state.company.cash;original?.call(button,e);if(!wasDeveloped&&tile.developed)this.logEvent("site-developed",`${tile.name} site developed at ${tile.x},${tile.y}.`,{x:tile.x,y:tile.y,resource:tile.name,type:tile.type,quality:tile.quality,size:tile.depositScale||tile.abundanceLabel,workers:this.colony.siteWorkforce(this.state,tile),cashCost:beforeCash-this.state.company.cash});else if(tile.level>beforeLevel)this.logEvent("site-upgraded",`${tile.name} upgraded to L${tile.level}.`,{x:tile.x,y:tile.y,resource:tile.name,level:tile.level,workers:this.colony.siteWorkforce(this.state,tile),cashCost:beforeCash-this.state.company.cash});this.repo.save(this.state);};}
  }
  techEffect(category,tech){if(category==="power")return`Power ${formatNumber(tech.powerCapacity)} • Population cap ${formatNumber(tech.populationCap)} • Industry L${tech.industryCap} • Fuel intensity ${tech.fuelIntensity.toFixed(3)}×`;if(category==="food"){const efficiency=Math.max(.70,1-(tech.level-1)*.035);return`Natural Food workforce requirement ×${efficiency.toFixed(2)}${tech.syntheticFood?` • Synthetic food ${formatNumber(tech.syntheticFood)}/day`:""}`;}const efficiency=Math.max(.65,1-(tech.level-1)*.04),slots=clamp(1+Math.floor((tech.level-1)/2),1,5),unlocks=this.resources.catalog().filter(r=>r.miningLevel===tech.level&&!r.manufactured).map(r=>r.name);return`Extraction workforce ×${efficiency.toFixed(2)} • Survey slots ${slots}${unlocks.length?` • Unlocks: ${unlocks.join(", ")}`:""}`;}
  tech(){UIEnhancementsMixin.prototype.tech.call(this);this.modal.querySelectorAll("[data-tech-cat]").forEach(button=>{if(button.dataset.logged55)return;button.dataset.logged55="1";const original=button.onclick;button.onclick=e=>{const category=button.dataset.techCat,before=this.technology.level(this.state,category),cash=this.state.company.cash;original?.call(button,e);const after=this.technology.level(this.state,category);if(after>before){const tech=this.technology.current(this.state,category);this.logEvent("technology-purchased",`${TECH_LABELS[category]} technology advanced to L${after}: ${tech.name}.`,{category,level:after,name:tech.name,cost:cash-this.state.company.cash});this.repo.save(this.state);}};});}
  menu(){UIEnhancementsMixin.prototype.menu.call(this);const grid=this.modal.querySelector(".grid2");if(!grid)return;const button=document.createElement("button");button.textContent="GAME LOG";button.dataset.gameLog="1";grid.insertBefore(button,grid.querySelector("[data-reset]"));button.onclick=()=>this.gameLogPanel();}
  async gameLogPanel(){
    const events=[...(this.gameLog?.ensure(this.state).events||[])].slice(-250).reverse(),esc=v=>String(v??"").replace(/[&<>]/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;"}[ch]));
    const eventRows=events.length?events.map(e=>`<div class="help-section"><div class="help-section-title"><h3>Y${e.year} D${e.day} • ${esc(e.type).toUpperCase()}</h3><span class="tiny">${esc(e.colonyName||"Corporation")}</span></div><p>${esc(e.message)}</p></div>`).join(""):`<article class="card"><p>No events have been recorded yet.</p></article>`;
    try{
      const body=await renderViewTemplate("./views/game-log.html",{TELEMETRY_DAYS:CONFIG.LOG_TELEMETRY_INTERVAL_DAYS,EVENT_COUNT:formatNumber(this.state.gameLog?.events?.length||0),TELEMETRY_COUNT:formatNumber(this.state.gameLog?.telemetry?.length||0),EVENT_ROWS:eventRows});
      this.open("Game Log",body);this.modal.querySelector("[data-download-log]").onclick=()=>this.downloadGameLog();
    }catch(error){this.diagnostics.error("game log template failed",error);this.toast("Unable to open the game log.");}
  }
  downloadGameLog(){try{this.onCapturePortfolio?.();const payload=this.gameLog.exportData(this.state,this.state.portfolio),blob=new Blob([JSON.stringify(payload,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`mineit-game-log-Y${this.state.year}-D${this.state.day}.json`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),0);this.toast("Game log download started.");}catch(error){this.diagnostics.error("game log download failed",error);this.toast("Game log download failed.");}}
}
