import { hashString,seededRandom } from "../core/utils.js";
import { BUYER_IDENTITIES,buyerIdentity,buyerShipClass,businessType } from "../data/buyer-content.js";
import { BUYER_MARKET_VERSION,PRICE_ENVELOPES,QUALITY_LABEL_TO_KEY,QUALITY_ORDER,TIER_INTERVALS,marketPhase,rangeFor } from "../data/buyer-market-balance.js";
import { applyBuyerLoss,awardBuyerShipment,normalizeReputation } from "./reputation-service.js";
import { hasFreeBerth } from "./spaceport-model.js";

const clamp=(v,min,max)=>Math.max(min,Math.min(max,Number(v)||0));
const roundMoney=v=>Number((Number(v)||0).toFixed(4));
const absDay=state=>(Math.max(1,Number(state.year)||1)-1)*360+Math.max(1,Number(state.day)||1);
const qualityRank=key=>Math.max(0,QUALITY_ORDER.indexOf(key));
const clone=value=>JSON.parse(JSON.stringify(value));
const WAITING_STATUSES=new Set(["orbital-holding","docked"]);
const ATTEMPT_OFFSETS=Object.freeze([0,5,10,15]);

export class BuyerService{
  constructor(resourceService,inventoryService){this.resources=resourceService;this.inventory=inventoryService;}
  absoluteDay(state){return absDay(state);}
  marketSeed(state){return Math.abs(Number(state.company?.expansion?.seed)||Number(state.seed)||hashString("MineIT buyers"));}
  ensure(state){
    state.company||={};state.company.rep=normalizeReputation(state.company.rep);
    const seed=this.marketSeed(state),previous=state.company.buyers;
    if(!previous||previous.version!==BUYER_MARKET_VERSION||previous.seed!==seed){
      const relationships=previous?.relationships&&typeof previous.relationships==="object"?previous.relationships:{},contracts=previous?.contracts&&typeof previous.contracts==="object"?previous.contracts:{};
      state.company.buyers={version:BUYER_MARKET_VERSION,seed,offers:this.generateOffers(seed),relationships,contracts,nextContractSequence:Math.max(1,Number(previous?.nextContractSequence)||1)};
    }
    const market=state.company.buyers;
    market.offers=Array.isArray(market.offers)&&market.offers.length===BUYER_IDENTITIES.length?market.offers:this.generateOffers(seed);
    market.relationships=market.relationships&&typeof market.relationships==="object"?market.relationships:{};
    market.contracts=market.contracts&&typeof market.contracts==="object"?market.contracts:{};
    market.nextContractSequence=Math.max(1,Number(market.nextContractSequence)||1);
    for(const [id,relationship] of Object.entries(market.relationships))this.normalizeRelationship(relationship,id);
    for(const [id,contract] of Object.entries(market.contracts))this.normalizeContract(contract,id);
    return market;
  }
  generateOffers(seed){
    const catalog=this.resources.catalog(),byName=new Map(catalog.map(def=>[def.name,def]));
    return BUYER_IDENTITIES.map(buyer=>{
      const random=seededRandom(hashString(`${seed}|buyer-offer-v${BUYER_MARKET_VERSION}|${buyer.id}`)),phase=marketPhase(buyer.minRep),ship=buyerShipClass(buyer.shipClassId),business=businessType(buyer.businessType),allNames=business?.resources||buyer.resourceInterests;
      let candidates=allNames.map(name=>({name,range:rangeFor(name,phase),def:byName.get(name)})).filter(x=>x.range&&x.def&&x.range[0]<=ship.capacity);
      if(!candidates.length)candidates=catalog.map(def=>({name:def.name,range:rangeFor(def.name,phase),def})).filter(x=>x.range&&x.range[0]<=ship.capacity);
      const selected=candidates[Math.floor(random()*candidates.length)]||{name:"Structural Mineral",range:[1,Math.max(1,ship.capacity)],def:byName.get("Structural Mineral")};
      const minQuality=QUALITY_LABEL_TO_KEY[buyer.typicalQuality]||"good",intervalRange=TIER_INTERVALS[buyer.tier]||TIER_INTERVALS.Entry,envelope=PRICE_ENVELOPES[phase],quantityMin=Math.max(1,Math.floor(selected.range[0])),quantityMax=Math.max(quantityMin,Math.min(Math.floor(selected.range[1]),ship.capacity)),quantity=Math.round(quantityMin+random()*(quantityMax-quantityMin)),intervalDays=Math.round(intervalRange[0]+random()*(intervalRange[1]-intervalRange[0])),priceFactor=envelope[0]+random()*(envelope[1]-envelope[0]),directRate=this.resources.sellPrice(selected.def.type,selected.def.id,minQuality),unitRate=roundMoney(directRate*Math.min(.999,priceFactor)),sortKey=random();
      return Object.freeze({id:`offer-${buyer.id}`,buyerId:buyer.id,resourceType:selected.def.type,resourceId:selected.def.id,resourceName:selected.def.name,minQuality,quantity,unitRate,fullValue:roundMoney(quantity*unitRate),intervalDays,minRep:buyer.minRep,portraitKey:buyer.portraitKey,shipImageKey:buyer.shipImageKey,sortKey});
    });
  }
  normalizeRelationship(r,buyerId){r.buyerId=buyerId;r.happiness=clamp(Number(r.happiness)||75,1,100);r.misses=Math.max(0,Math.floor(Number(r.misses)||0));r.consecutiveRed=Math.max(0,Math.floor(Number(r.consecutiveRed)||0));r.cooldownUntilAbsoluteDay=Math.max(0,Number(r.cooldownUntilAbsoluteDay)||0);r.terminated=!!r.terminated;r.history=Array.isArray(r.history)?r.history:[];r.fullDeliveries=Math.max(0,Number(r.fullDeliveries)||0);r.partialDeliveries=Math.max(0,Number(r.partialDeliveries)||0);r.lateDeliveries=Math.max(0,Number(r.lateDeliveries)||0);r.missedDeliveries=Math.max(0,Number(r.missedDeliveries)||0);r.totalUnits=Math.max(0,Number(r.totalUnits)||0);r.totalRevenue=Math.max(0,Number(r.totalRevenue)||0);return r;}
  relationship(state,buyerId){const market=this.ensure(state);market.relationships[buyerId]||={buyerId,happiness:75,misses:0,consecutiveRed:0,cooldownUntilAbsoluteDay:0,terminated:false,history:[],fullDeliveries:0,partialDeliveries:0,lateDeliveries:0,missedDeliveries:0,totalUnits:0,totalRevenue:0};return this.normalizeRelationship(market.relationships[buyerId],buyerId);}
  normalizeContract(c,id){c.id=id;c.status=c.status||"active";c.startedAbsoluteDay=Math.max(1,Number(c.startedAbsoluteDay)||1);c.nextDueAbsoluteDay=Math.max(1,Number(c.nextDueAbsoluteDay)||c.startedAbsoluteDay+Math.max(1,Number(c.intervalDays)||45));c.ship=c.ship&&typeof c.ship==="object"?c.ship:{};c.ship.status=c.ship.status||"idle";c.ship.dueAbsoluteDay=Number.isFinite(Number(c.ship.dueAbsoluteDay))?Number(c.ship.dueAbsoluteDay):null;c.ship.attemptIndex=Math.max(0,Math.min(3,Math.floor(Number(c.ship.attemptIndex)||0)));c.ship.nextEventAbsoluteDay=Number.isFinite(Number(c.ship.nextEventAbsoluteDay))?Number(c.ship.nextEventAbsoluteDay):null;c.ship.eventPending=!!c.ship.eventPending;return c;}
  offer(state,offerId){return this.ensure(state).offers.find(o=>o.id===offerId)||null;}
  identityForOffer(state,offerId){const offer=this.offer(state,offerId);return offer?buyerIdentity(offer.buyerId):null;}
  shipForOffer(state,offerId){const identity=this.identityForOffer(state,offerId);return identity?buyerShipClass(identity.shipClassId):null;}
  contract(state,contractId){return this.ensure(state).contracts[contractId]||null;}
  contractForOffer(state,offerId){return Object.values(this.ensure(state).contracts).find(c=>c.offerId===offerId&&c.status==="active")||null;}
  contractForBuyer(state,buyerId){return Object.values(this.ensure(state).contracts).find(c=>c.buyerId===buyerId&&c.status==="active")||null;}
  offerStatus(state,offer){const contract=this.contractForOffer(state,offer.id),relationship=this.relationship(state,offer.buyerId),now=this.absoluteDay(state);if(contract)return"current";if(relationship.terminated||relationship.cooldownUntilAbsoluteDay>now)return"locked";return normalizeReputation(state.company.rep)>=offer.minRep?"available":"locked";}
  offerView(state,offer){const buyer=buyerIdentity(offer.buyerId),ship=buyerShipClass(buyer?.shipClassId),relationship=this.relationship(state,offer.buyerId),contract=this.contractForOffer(state,offer.id),status=this.offerStatus(state,offer),now=this.absoluteDay(state);return{...offer,buyer,ship,relationship,contract,status,eligible:status==="available",cooldownDays:Math.max(0,relationship.cooldownUntilAbsoluteDay-now),lockedReason:relationship.terminated?"Buyer terminated the relationship.":relationship.cooldownUntilAbsoluteDay>now?`Cooling down for ${relationship.cooldownUntilAbsoluteDay-now} day(s).`:normalizeReputation(state.company.rep)<offer.minRep?`Requires ${offer.minRep.toFixed(2)} reputation.`:null};}
  catalog(state){return this.ensure(state).offers.map(o=>this.offerView(state,o)).sort((a,b)=>a.sortKey-b.sortKey||a.buyer.index-b.buyer.index);}
  canEnter(state,offerId,colonyId=state.colonyId){const offer=this.offer(state,offerId);if(!offer)return{ok:false,reason:"Unknown buyer offer."};const view=this.offerView(state,offer);if(view.contract)return{ok:false,reason:"That buyer offer already has an active colony contract."};if(view.relationship.terminated)return{ok:false,reason:"This buyer terminated the commercial relationship."};if(view.cooldownDays>0)return{ok:false,reason:`This buyer is unavailable for ${view.cooldownDays} more day(s).`};if(normalizeReputation(state.company.rep)<offer.minRep)return{ok:false,reason:`Requires ${offer.minRep.toFixed(2)} global reputation.`};if(!colonyId)return{ok:false,reason:"No colony is selected."};return{ok:true,offer,view};}
  enterContract(state,offerId,colonyId=state.colonyId){const check=this.canEnter(state,offerId,colonyId);if(!check.ok)return check;const market=this.ensure(state),offer=check.offer,buyer=buyerIdentity(offer.buyerId),ship=buyerShipClass(buyer.shipClassId),now=this.absoluteDay(state),id=`buyer-contract-${market.nextContractSequence++}`;this.relationship(state,buyer.id);const contract={id,offerId:offer.id,buyerId:buyer.id,colonyId,status:"active",startedAbsoluteDay:now,resourceType:offer.resourceType,resourceId:offer.resourceId,resourceName:offer.resourceName,minQuality:offer.minQuality,quantity:offer.quantity,unitRate:offer.unitRate,intervalDays:offer.intervalDays,minRep:offer.minRep,portraitKey:offer.portraitKey,shipImageKey:offer.shipImageKey,shipName:buyer.shipName,shipClassId:ship.id,shipCapacity:ship.capacity,nextDueAbsoluteDay:now+offer.intervalDays,ship:{status:"idle",dueAbsoluteDay:null,attemptIndex:0,nextEventAbsoluteDay:null,eventPending:false}};market.contracts[id]=contract;return{ok:true,contract,offer,buyer,ship};}
  activeContractsForColony(state,colonyId=state.colonyId){return Object.values(this.ensure(state).contracts).filter(c=>c.status==="active"&&c.colonyId===colonyId);}
  shipWaiting(contract){return !!contract&&WAITING_STATUSES.has(contract.ship?.status);}
  waitingShipsForColony(state,colonyId=state.colonyId){return this.activeContractsForColony(state,colonyId).filter(c=>this.shipWaiting(c));}
  startCollection(state,contract,now=this.absoluteDay(state)){contract.ship={status:"orbital-holding",dueAbsoluteDay:contract.nextDueAbsoluteDay,attemptIndex:0,nextEventAbsoluteDay:contract.nextDueAbsoluteDay,eventPending:false};if(hasFreeBerth(state))contract.ship.status="docked";return contract.ship;}
  tryDock(state,contract){if(contract.ship?.status!=="orbital-holding")return false;if(!hasFreeBerth(state))return false;contract.ship.status="docked";return true;}
  eventFor(contract){return{type:"buyer",colonyId:contract.colonyId,contractId:contract.id,offerId:contract.offerId,buyerId:contract.buyerId,attemptIndex:contract.ship.attemptIndex,dueAbsoluteDay:contract.ship.dueAbsoluteDay};}
  processDay(state){const now=this.absoluteDay(state),events=[];for(const contract of this.activeContractsForColony(state)){if(contract.ship.status==="idle"&&now>=contract.nextDueAbsoluteDay)this.startCollection(state,contract,now);if(contract.ship.status==="orbital-holding")this.tryDock(state,contract);if(this.shipWaiting(contract)&&!contract.ship.eventPending&&now>=contract.ship.nextEventAbsoluteDay){contract.ship.eventPending=true;events.push(this.eventFor(contract));}}return events;}
  recoverEvents(state){const now=this.absoluteDay(state),events=[];for(const contract of this.activeContractsForColony(state)){if(contract.ship?.status==="orbital-holding")this.tryDock(state,contract);if(this.shipWaiting(contract)&&now>=Number(contract.ship.nextEventAbsoluteDay||contract.ship.dueAbsoluteDay||now)){contract.ship.eventPending=true;events.push(this.eventFor(contract));}}return events;}
  qualityAvailable(state,contract){const entry=state.inventory?.[`${contract.resourceType}:${contract.resourceId}`];if(!entry)return 0;this.inventory.syncEntry(entry);const minRank=qualityRank(contract.minQuality);return this.inventory.bands(entry).filter(b=>qualityRank(b.key)>=minRank).reduce((sum,b)=>sum+b.amount,0);}
  timingChange(daysLate){if(daysLate<=0)return 1;if(daysLate<=5)return-1;if(daysLate<=10)return-2;return-3;}
  partialChange(ratio){if(ratio>=.999999)return 0;if(ratio>=.75)return-1;if(ratio>=.5)return-2;return null;}
  fulfilmentLabel(ratio){return ratio>=.999999?"full":ratio>=.75?"minor-partial":ratio>=.5?"major-partial":"not-accepted";}
  projection(state,contractId){const contract=this.contract(state,contractId);if(!contract)return null;const relationship=this.relationship(state,contract.buyerId),stock=this.qualityAvailable(state,contract),maxTransfer=Math.min(contract.quantity,stock),ratio=contract.quantity>0?maxTransfer/contract.quantity:0,daysLate=Math.max(0,this.absoluteDay(state)-Number(contract.ship.dueAbsoluteDay||contract.nextDueAbsoluteDay)),partial=this.partialChange(ratio),timing=this.timingChange(daysLate),happinessChange=partial===null?null:timing+partial,repChange=happinessChange===null?0:(happinessChange<0?happinessChange*.10:0)+.01;return{contract,relationship,stock,maxTransfer,ratio,fulfilment:this.fulfilmentLabel(ratio),daysLate,timingChange:timing,partialChange:partial,happinessChange,projectedHappiness:happinessChange===null?relationship.happiness:clamp(relationship.happiness+happinessChange,1,100),projectedReputation:normalizeReputation(state.company.rep+repChange),reputationChange:Number(repChange.toFixed(2)),payment:roundMoney(maxTransfer*contract.unitRate),stockRemaining:Math.max(0,stock-maxTransfer),canTransfer:contract.ship.status==="docked"&&ratio>=.5,canWait:daysLate<15,shipStatus:contract.ship.status};}
  recordCycle(relationship,record){relationship.history.push(record);if(relationship.history.length>100)relationship.history.splice(0,relationship.history.length-100);}
  applyRelationshipChange(state,relationship,delta){const before=relationship.happiness;relationship.happiness=clamp(before+(Number(delta)||0),1,100);const actual=relationship.happiness-before;if(actual<0)applyBuyerLoss(state,actual);return actual;}
  updateRedTermination(relationship){if(relationship.happiness<=33)relationship.consecutiveRed++;else relationship.consecutiveRed=0;return relationship.consecutiveRed>=2;}
  finishCycle(contract,now){contract.ship={status:"idle",dueAbsoluteDay:null,attemptIndex:0,nextEventAbsoluteDay:null,eventPending:false};contract.nextDueAbsoluteDay=now+contract.intervalDays;}
  terminate(state,contract,reason){const relationship=this.relationship(state,contract.buyerId);contract.status="terminated";contract.terminatedAbsoluteDay=this.absoluteDay(state);contract.terminationReason=reason;contract.ship={status:"departed",dueAbsoluteDay:null,attemptIndex:0,nextEventAbsoluteDay:null,eventPending:false};relationship.terminated=true;return{terminated:true,reason};}
  transfer(state,contractId){const contract=this.contract(state,contractId);if(!contract||contract.status!=="active")return{ok:false,reason:"Buyer contract is not active."};const projection=this.projection(state,contractId);if(contract.ship.status!=="docked")return{ok:false,reason:"Collection ship is not docked."};if(!projection||projection.ratio<.5)return{ok:false,reason:"At least 50% of the contracted qualifying stock is required."};const removal=this.inventory.removeWeighted(state,contract.resourceType,contract.resourceId,projection.maxTransfer,{minimumQualityKey:contract.minQuality,lowestFirst:true});if(removal.removed<=0)return{ok:false,reason:"No qualifying stock was transferred."};const now=this.absoluteDay(state),ratio=removal.removed/contract.quantity,partial=this.partialChange(ratio),timing=this.timingChange(projection.daysLate),happinessChange=timing+(partial||0),relationship=this.relationship(state,contract.buyerId),actualHappinessChange=this.applyRelationshipChange(state,relationship,happinessChange),revenue=roundMoney(removal.removed*contract.unitRate),fulfilment=this.fulfilmentLabel(ratio);state.company.cash+=revenue;state.company.earn=(Number(state.company.earn)||0)+revenue;state.contract.localRevenue=(Number(state.contract.localRevenue)||0)+revenue;awardBuyerShipment(state);relationship.totalUnits+=removal.removed;relationship.totalRevenue+=revenue;if(fulfilment==="full")relationship.fullDeliveries++;else relationship.partialDeliveries++;if(projection.daysLate>0)relationship.lateDeliveries++;const record={absoluteDay:now,result:fulfilment,quantity:removal.removed,contracted:contract.quantity,revenue,daysLate:projection.daysLate,happinessChange:actualHappinessChange};this.recordCycle(relationship,record);const redTermination=this.updateRedTermination(relationship);if(redTermination)return{ok:true,contract,relationship,removal,revenue,record,...this.terminate(state,contract,"Two consecutive resolved shipment cycles finished in Red.")};this.finishCycle(contract,now);return{ok:true,contract,relationship,removal,revenue,record,terminated:false};}
  continueWaiting(state,contractId){const contract=this.contract(state,contractId);if(!contract||!this.shipWaiting(contract))return{ok:false,reason:"No buyer collection ship is waiting."};const daysLate=Math.max(0,this.absoluteDay(state)-contract.ship.dueAbsoluteDay);if(daysLate>=15||contract.ship.attemptIndex>=3)return{ok:false,reason:"This is the final collection opportunity."};contract.ship.eventPending=false;contract.ship.attemptIndex++;contract.ship.nextEventAbsoluteDay=contract.ship.dueAbsoluteDay+ATTEMPT_OFFSETS[contract.ship.attemptIndex];return{ok:true,nextAttemptAbsoluteDay:contract.ship.nextEventAbsoluteDay,attemptIndex:contract.ship.attemptIndex};}
  resolveMiss(state,contractId){const contract=this.contract(state,contractId);if(!contract||!this.shipWaiting(contract))return{ok:false,reason:"No buyer collection ship is waiting."};const now=this.absoluteDay(state),daysLate=Math.max(0,now-contract.ship.dueAbsoluteDay);if(daysLate<15&&contract.ship.attemptIndex<3)return{ok:false,reason:"The final collection opportunity has not been reached."};const relationship=this.relationship(state,contract.buyerId),missNumber=Math.min(3,relationship.misses+1),penalty=[0,-10,-20,-30][missNumber];relationship.misses++;relationship.missedDeliveries++;const actualHappinessChange=this.applyRelationshipChange(state,relationship,penalty),record={absoluteDay:now,result:"missed",quantity:0,contracted:contract.quantity,revenue:0,daysLate,happinessChange:actualHappinessChange,missNumber};this.recordCycle(relationship,record);const redTermination=this.updateRedTermination(relationship);if(missNumber>=3)return{ok:true,record,relationship,...this.terminate(state,contract,"Third missed shipment.")};if(redTermination)return{ok:true,record,relationship,...this.terminate(state,contract,"Two consecutive resolved shipment cycles finished in Red.")};this.finishCycle(contract,now);return{ok:true,record,relationship,terminated:false};}
  cancelContract(state,contractId){const contract=this.contract(state,contractId);if(!contract||contract.status!=="active")return{ok:false,reason:"Buyer contract is not active."};if(this.shipWaiting(contract))return{ok:false,reason:"Contract cancellation is blocked while the buyer collection ship is waiting."};const relationship=this.relationship(state,contract.buyerId),actual=this.applyRelationshipChange(state,relationship,-5),now=this.absoluteDay(state);relationship.cooldownUntilAbsoluteDay=now+contract.intervalDays;contract.status="cancelled";contract.cancelledAbsoluteDay=now;contract.ship={status:"departed",dueAbsoluteDay:null,attemptIndex:0,nextEventAbsoluteDay:null,eventPending:false};this.recordCycle(relationship,{absoluteDay:now,result:"player-cancelled",quantity:0,contracted:contract.quantity,revenue:0,daysLate:0,happinessChange:actual});return{ok:true,contract,relationship,cooldownUntilAbsoluteDay:relationship.cooldownUntilAbsoluteDay};}
  clearEventPending(state,contractId){const contract=this.contract(state,contractId);if(contract?.ship)contract.ship.eventPending=false;return !!contract;}
  snapshotContract(state,contractId){const contract=this.contract(state,contractId);if(!contract)return null;const offer=this.offer(state,contract.offerId),buyer=buyerIdentity(contract.buyerId),ship=buyerShipClass(contract.shipClassId),relationship=this.relationship(state,contract.buyerId);return{contract:clone(contract),offer,buyer,ship,relationship:clone(relationship),projection:this.projection(state,contractId)};}
}
