import { supportsOverdrive,setOperatingMode,advanceOverdriveRisk,isAccidentShutdown,advanceShutdownDay } from "./extraction-overdrive.js";

export class CollectionService {
  constructor(resourceService,inventoryService,technologyService){this.resources=resourceService;this.inventory=inventoryService;this.technology=technologyService;}
  supportsOverdrive(tile){return supportsOverdrive(tile);}
  setOperatingMode(state,tile,mode){if(state?.status==="dead")return{ok:false,reason:"This colony has been lost."};if(state?.contract?.ended)return{ok:false,reason:"The mining contract has ended."};return setOperatingMode(tile,mode);}
  isShutdown(tile){return isAccidentShutdown(tile);}
  shutdownSites(state){return Object.values(state.tiles||{}).filter(tile=>isAccidentShutdown(tile));}
  advanceShutdowns(tiles){for(const tile of tiles||[])advanceShutdownDay(tile);}
  activeSites(state){if(state.contract?.ended||state.status==="dead")return[];let sites=Object.values(state.tiles).filter(tile=>tile.developed&&!tile.depleted&&!tile.productionStopped&&!isAccidentShutdown(tile)&&this.technology.canExploit(state,tile));if(state.colony?.emergencyMode)sites=sites.filter(tile=>tile.type==="food"||tile.type==="fuel");return sites;}
  collectDay(state,tile){if(tile?.productionStopped)return{rate:0,collected:0,renewable:this.resources.isRenewable(tile),exhausted:false,renewableEvent:null,accident:null};const rate=this.resources.collectionRate(state,tile);if(this.resources.isRenewable(tile)){const renewableEvent=this.resources.updateRenewable(tile);return{rate,collected:rate,renewable:true,exhausted:!!tile.renewableWiped,renewableEvent,accident:null};}const remaining=Math.max(0,tile.reserve||0),collected=Math.min(rate,remaining);tile.reserve=Math.max(0,remaining-collected);const exhausted=tile.reserve<=0;if(exhausted)tile.depleted=true;const accident=!exhausted&&collected>0&&supportsOverdrive(tile)?advanceOverdriveRisk(state,tile):null;return{rate,collected,renewable:false,exhausted,renewableEvent:null,accident};}
  current(state){const groups=new Map();for(const tile of this.activeSites(state)){const key=this.inventory.key(tile.type,tile.resourceId),renewable=this.resources.isRenewable(tile);let row=groups.get(key);if(!row){row={key,name:tile.name,category:this.resources.categoryName(tile.type),type:tile.type,resourceId:tile.resourceId,rate:0,stock:this.inventory.amountFor(state,tile.type,tile.resourceId),renewable:true,remaining:0,sites:0};groups.set(key,row);}row.rate+=this.resources.collectionRate(state,tile);row.sites++;if(!renewable){row.renewable=false;row.remaining+=Math.max(0,tile.reserve||0);}}return[...groups.values()].sort((a,b)=>a.category.localeCompare(b.category)||a.name.localeCompare(b.name));}
}
