import { CONFIG } from "../core/config.js?v=5.5.2";
import { clamp } from "../core/utils.js?v=5.5.2";

export class ColonyService {
  constructor(inventoryService,technologyService){this.inventory=inventoryService;this.technology=technologyService;}
  buildStock(state){return this.inventory.amount(state,"build");}
  addLocalCost(state,amount){state.contract.localCosts=(state.contract.localCosts||0)+Math.max(0,amount||0);}
  supportLoad(state){return Math.max(.5,Number(state.contract?.supportLoad)||1);}
  populationCapacity(state){return Math.max(0,Math.min(state.colony.housingCapacity,state.metrics.powerPopulationCap||state.colony.housingCapacity));}
  industryPopulationRequirement(level){const l=Math.max(1,Math.round(Number(level)||1));if(l<=10){const n=l-1;return Math.round(100+80*n+10*n*n);}return Math.round(1630+(l-10)*330);}
  industryPopulationFactor(state,level=state.colony.industryLevel){const required=this.industryPopulationRequirement(level);return clamp((Number(state.pop)||0)/Math.max(1,required),0,1);}
  siteIndustryLoad(tile){const level=Math.max(1,Math.round(Number(tile?.level)||1));return Math.round(CONFIG.INDUSTRY_SITE_LOAD_BASE*Math.pow(CONFIG.INDUSTRY_SITE_LOAD_GROWTH,level-1));}
  industryOperationalCapacity(state){if(state.status==="dead"||state.colony?.emergencyMode)return 0;return Math.max(0,state.colony.industryLevel*100*this.industryPopulationFactor(state));}
  industryNetwork(state,sites=[]){const capacity=this.industryOperationalCapacity(state);let survivalLoad=0,commercialLoad=0;for(const tile of sites){const load=this.siteIndustryLoad(tile);if(tile.type==="food"||tile.type==="fuel")survivalLoad+=load;else commercialLoad+=load;}const remaining=Math.max(0,capacity-survivalLoad),commercialFactor=state.colony?.emergencyMode?0:commercialLoad>0?clamp(remaining/commercialLoad,0,1):1,totalLoad=survivalLoad+commercialLoad;return{industryCapacity:capacity,industryLoad:totalLoad,industrySurvivalLoad:survivalLoad,industryCommercialLoad:commercialLoad,industryCommercialFactor:commercialFactor,industryOverloaded:totalLoad>capacity+.001};}
  workforceAvailable(state){return state.status==="dead"?0:Math.max(0,Math.floor((Number(state.pop)||0)*CONFIG.WORKFORCE_SHARE));}
  siteWorkforce(state,tile,levelOverride=null){const level=Math.max(1,Math.round(Number(levelOverride??tile?.level)||1)),miningLevel=Math.max(1,Number(tile?.requiredMiningLevel)||1),complexity=1+.18*(miningLevel-1),efficiency=tile?.type==="food"?(state.metrics.foodWorkforceEfficiency||1):(state.metrics.miningWorkforceEfficiency||1),intensity=tile?.sustainability==="renewable"||tile?.type==="food"||tile?.resourceId==="biomass"||tile?.resourceId==="fiber"?clamp(Number(tile?.harvestIntensity)||1,.25,2):1,intensityFactor=.5+.5*intensity;return Math.max(1,Math.ceil(CONFIG.SITE_WORKFORCE_BASE*Math.pow(CONFIG.SITE_WORKFORCE_GROWTH,level-1)*complexity*efficiency*intensityFactor));}
  workforceSites(state){if(state.contract?.ended||state.status==="dead")return[];let sites=Object.values(state.tiles||{}).filter(tile=>tile.developed&&!tile.depleted);if(state.colony?.emergencyMode)sites=sites.filter(tile=>tile.type==="food"||tile.type==="fuel");return sites;}
  workforceNetwork(state,sites=this.workforceSites(state)){const available=this.workforceAvailable(state);let survivalRequired=0,commercialRequired=0;for(const tile of sites){const required=this.siteWorkforce(state,tile);if(tile.type==="food"||tile.type==="fuel")survivalRequired+=required;else commercialRequired+=required;}const survivalFactor=survivalRequired>0?clamp(available/survivalRequired,0,1):1,remaining=Math.max(0,available-survivalRequired),commercialFactor=state.colony?.emergencyMode?0:commercialRequired>0?clamp(remaining/commercialRequired,0,1):1,required=survivalRequired+commercialRequired;return{workforceAvailable:available,workforceRequired:required,workforceSurvivalRequired:survivalRequired,workforceCommercialRequired:commercialRequired,workforceSurvivalFactor:survivalFactor,workforceCommercialFactor:commercialFactor,workforceFree:Math.max(0,available-required),workforceShortfall:Math.max(0,required-available)};}
  freeWorkforce(state){return this.workforceNetwork(state).workforceFree;}
  processingBonus(industryValue){const value=Math.max(0,Number(industryValue)||0),points=[[100,0],[200,.05],[300,.10],[500,.20],[1000,.35],[2000,CONFIG.INDUSTRY_PROCESSING_MAX_BONUS]];if(value<=points[0][0])return 0;for(let i=1;i<points.length;i++){const [hi,bonus]=points[i],[lo,loBonus]=points[i-1];if(value<=hi){const t=(value-lo)/(hi-lo);return loBonus+t*(bonus-loBonus);}}return CONFIG.INDUSTRY_PROCESSING_MAX_BONUS;}
  processingMultiplier(state){return 1+this.processingBonus(state.metrics?.industry||0);}
  siteUpgradeIndustryRequirement(siteLevel){const level=Math.max(1,Math.round(Number(siteLevel)||1));if(level<=1)return 1;if(level===2)return 2;if(level===3)return 3;if(level===4)return 5;if(level===5)return 7;return 7+(level-5)*3;}
  housingBuildCost(state){return Math.round(CONFIG.HOUSING_BASE_BUILD*Math.pow(1.55,Math.max(0,state.colony.housingLevel-1)));}
  housingCashCost(state){return Math.round(CONFIG.HOUSING_BASE_CASH*Math.pow(1.45,Math.max(0,state.colony.housingLevel-1)));}
  industryBuildCost(state){return Math.round(CONFIG.INDUSTRY_BASE_BUILD*Math.pow(1.55,Math.max(0,state.colony.industryLevel-1)));}
  industryCashCost(state){return Math.round(CONFIG.INDUSTRY_BASE_CASH*Math.pow(1.48,Math.max(0,state.colony.industryLevel-1)));}
  canExpandHousing(state){if(state.status==="dead")return{ok:false,reason:"This colony has been lost."};const nextCap=state.colony.housingCapacity+160;if(nextCap>state.metrics.powerPopulationCap)return{ok:false,reason:`Power Tech L${state.metrics.powerTech} supports up to ${state.metrics.powerPopulationCap} population.`};const build=this.housingBuildCost(state),cash=this.housingCashCost(state);if(this.buildStock(state)<build)return{ok:false,reason:`Need ${build} Build materials.`};if(state.company.cash<cash)return{ok:false,reason:"Insufficient cash."};return{ok:true,build,cash,nextCap};}
  expandHousing(state){const check=this.canExpandHousing(state);if(!check.ok)return check;this.inventory.consumeCategory(state,"build",check.build);state.company.cash-=check.cash;this.addLocalCost(state,check.cash);state.colony.housingLevel++;state.colony.housingCapacity=check.nextCap;return{ok:true,...check};}
  canExpandIndustry(state){if(state.status==="dead")return{ok:false,reason:"This colony has been lost."};const next=state.colony.industryLevel+1;if(next>state.metrics.powerIndustryCap)return{ok:false,reason:`Power Tech L${state.metrics.powerTech} supports Industry L${state.metrics.powerIndustryCap}.`};const build=this.industryBuildCost(state),cash=this.industryCashCost(state),populationRequired=this.industryPopulationRequirement(next);if(this.buildStock(state)<build)return{ok:false,reason:`Need ${build} Build materials.`,populationRequired};if(state.company.cash<cash)return{ok:false,reason:"Insufficient cash.",populationRequired};return{ok:true,build,cash,next,populationRequired};}
  expandIndustry(state){const check=this.canExpandIndustry(state);if(!check.ok)return check;this.inventory.consumeCategory(state,"build",check.build);state.company.cash-=check.cash;this.addLocalCost(state,check.cash);state.colony.industryLevel=check.next;return{ok:true,...check};}
  demand(state,activeSites=0){if(state.status==="dead")return{powerDemand:0,capacity:state.metrics.powerCapacity||1,capacityFactor:1,foodDemand:0,fuelDemand:0,oreDemand:0,staffFactor:0,populationRequired:this.industryPopulationRequirement(state.colony.industryLevel),supportLoad:this.supportLoad(state)};const emergency=!!state.colony.emergencyMode,supportLoad=this.supportLoad(state),staffFactor=this.industryPopulationFactor(state),populationRequired=this.industryPopulationRequirement(state.colony.industryLevel),lifeSupport=state.pop*CONFIG.LIFE_SUPPORT_POWER_PER_COLONIST*supportLoad*(emergency?CONFIG.EMERGENCY_LIFE_SUPPORT_MULTIPLIER:1),industryPower=emergency?0:state.colony.industryLevel*CONFIG.INDUSTRY_POWER_PER_LEVEL*staffFactor,sitePower=activeSites*CONFIG.SITE_POWER_DEMAND,powerDemand=Math.max(.1,lifeSupport+industryPower+sitePower),capacity=state.metrics.powerCapacity||1,capacityFactor=clamp(capacity/Math.max(.1,powerDemand),0,1),foodDemand=Math.max(.1,state.pop*CONFIG.FOOD_PER_COLONIST),fuelDemand=Math.max(.05,powerDemand*(state.metrics.fuelIntensity||.1)),oreDemand=emergency?0:Math.max(.05,state.colony.industryLevel*CONFIG.ORE_PER_INDUSTRY_LEVEL*staffFactor);return{powerDemand,capacity,capacityFactor,foodDemand,fuelDemand,oreDemand,staffFactor,populationRequired,supportLoad};}
  operatingCost(state,activeSites=0){if(state.status==="dead")return 0;const tier=1+.20*Math.max(0,(state.contract.colonyTier||1)-1),support=this.supportLoad(state),base=state.pop*.22+state.colony.industryLevel*4+state.colony.housingLevel*1.2+activeSites*1.5,statusMult=state.status==="liability"?CONFIG.LIABILITY_COST_MULTIPLIER:state.status==="holdover"?CONFIG.HOLDOVER_COST_MULTIPLIER:1,emergencyMult=state.colony.emergencyMode?CONFIG.EMERGENCY_OPERATING_COST_MULTIPLIER:1;return Math.max(1,base*tier*support*statusMult*emergencyMult);}
  supplyDays(stock,production,demand){const deficit=Math.max(0,(Number(demand)||0)-(Number(production)||0));return deficit<=.0001?null:Math.max(0,(Number(stock)||0)/deficit);}
  relocationCost(state){return Math.round(CONFIG.RELOCATION_BASE_COST+state.pop*CONFIG.RELOCATION_PER_COLONIST+state.colony.industryLevel*CONFIG.RELOCATION_PER_INDUSTRY_LEVEL);}
  syntheticFoodRate(state){return state.contract.naturalFood===false?(state.metrics.syntheticFood||0):Math.max(0,(state.metrics.syntheticFood||0)*.35);}
}
