import { CONFIG } from "../core/config.js?v=5.3.0";
import { clamp } from "../core/utils.js?v=5.3.0";

export class ColonyService {
  constructor(inventoryService,technologyService){this.inventory=inventoryService;this.technology=technologyService;}
  buildStock(state){return this.inventory.amount(state,"build");}
  addLocalCost(state,amount){state.contract.localCosts=(state.contract.localCosts||0)+Math.max(0,amount||0);}
  supportLoad(state){return Math.max(.5,Number(state.contract?.supportLoad)||1);}
  populationCapacity(state){return Math.max(0,Math.min(state.colony.housingCapacity,state.metrics.powerPopulationCap||state.colony.housingCapacity));}
  industryPopulationRequirement(level){const l=Math.max(1,Math.round(Number(level)||1));if(l<=10){const n=l-1;return Math.round(100+80*n+10*n*n);}return Math.round(1630+(l-10)*330);}
  industryPopulationFactor(state,level=state.colony.industryLevel){const required=this.industryPopulationRequirement(level);return clamp((Number(state.pop)||0)/Math.max(1,required),0,1);}
  housingBuildCost(state){return Math.round(70*Math.pow(1.42,Math.max(0,state.colony.housingLevel-1)));}
  housingCashCost(state){return Math.round(1800*Math.pow(1.28,Math.max(0,state.colony.housingLevel-1)));}
  industryBuildCost(state){return Math.round(95*Math.pow(1.48,Math.max(0,state.colony.industryLevel-1)));}
  industryCashCost(state){return Math.round(2600*Math.pow(1.34,Math.max(0,state.colony.industryLevel-1)));}
  canExpandHousing(state){if(state.status==="dead")return{ok:false,reason:"This colony has been lost."};const nextCap=state.colony.housingCapacity+160;if(nextCap>state.metrics.powerPopulationCap)return{ok:false,reason:`Power Tech L${state.metrics.powerTech} supports up to ${state.metrics.powerPopulationCap} population.`};const build=this.housingBuildCost(state),cash=this.housingCashCost(state);if(this.buildStock(state)<build)return{ok:false,reason:`Need ${build} Build materials.`};if(state.company.cash<cash)return{ok:false,reason:"Insufficient cash."};return{ok:true,build,cash,nextCap};}
  expandHousing(state){const check=this.canExpandHousing(state);if(!check.ok)return check;this.inventory.consumeCategory(state,"build",check.build);state.company.cash-=check.cash;this.addLocalCost(state,check.cash);state.colony.housingLevel++;state.colony.housingCapacity=check.nextCap;return{ok:true,...check};}
  canExpandIndustry(state){if(state.status==="dead")return{ok:false,reason:"This colony has been lost."};const next=state.colony.industryLevel+1;if(next>state.metrics.powerIndustryCap)return{ok:false,reason:`Power Tech L${state.metrics.powerTech} supports Industry L${state.metrics.powerIndustryCap}.`};const build=this.industryBuildCost(state),cash=this.industryCashCost(state),populationRequired=this.industryPopulationRequirement(next);if(this.buildStock(state)<build)return{ok:false,reason:`Need ${build} Build materials.`,populationRequired};if(state.company.cash<cash)return{ok:false,reason:"Insufficient cash.",populationRequired};return{ok:true,build,cash,next,populationRequired};}
  expandIndustry(state){const check=this.canExpandIndustry(state);if(!check.ok)return check;this.inventory.consumeCategory(state,"build",check.build);state.company.cash-=check.cash;this.addLocalCost(state,check.cash);state.colony.industryLevel=check.next;return{ok:true,...check};}
  demand(state,activeSites=0){
    if(state.status==="dead")return{powerDemand:0,capacity:state.metrics.powerCapacity||1,capacityFactor:1,foodDemand:0,fuelDemand:0,oreDemand:0,staffFactor:0,populationRequired:this.industryPopulationRequirement(state.colony.industryLevel),supportLoad:this.supportLoad(state)};
    const emergency=!!state.colony.emergencyMode,supportLoad=this.supportLoad(state),staffFactor=this.industryPopulationFactor(state),populationRequired=this.industryPopulationRequirement(state.colony.industryLevel),lifeSupport=state.pop*CONFIG.LIFE_SUPPORT_POWER_PER_COLONIST*supportLoad*(emergency?CONFIG.EMERGENCY_LIFE_SUPPORT_MULTIPLIER:1),industryPower=emergency?0:state.colony.industryLevel*CONFIG.INDUSTRY_POWER_PER_LEVEL*staffFactor,sitePower=activeSites*CONFIG.SITE_POWER_DEMAND,powerDemand=Math.max(.1,lifeSupport+industryPower+sitePower),capacity=state.metrics.powerCapacity||1,capacityFactor=clamp(capacity/Math.max(.1,powerDemand),0,1),foodDemand=Math.max(.1,state.pop*CONFIG.FOOD_PER_COLONIST),fuelDemand=Math.max(.05,powerDemand*(state.metrics.fuelIntensity||.1)),oreDemand=emergency?0:Math.max(.05,state.colony.industryLevel*CONFIG.ORE_PER_INDUSTRY_LEVEL*staffFactor);return{powerDemand,capacity,capacityFactor,foodDemand,fuelDemand,oreDemand,staffFactor,populationRequired,supportLoad};
  }
  operatingCost(state,activeSites=0){if(state.status==="dead")return 0;const tier=1+.20*Math.max(0,(state.contract.colonyTier||1)-1),support=this.supportLoad(state),base=state.pop*.22+state.colony.industryLevel*4+state.colony.housingLevel*1.2+activeSites*1.5,statusMult=state.status==="liability"?CONFIG.LIABILITY_COST_MULTIPLIER:state.status==="holdover"?CONFIG.HOLDOVER_COST_MULTIPLIER:1,emergencyMult=state.colony.emergencyMode?CONFIG.EMERGENCY_OPERATING_COST_MULTIPLIER:1;return Math.max(1,base*tier*support*statusMult*emergencyMult);}
  supplyDays(stock,production,demand){const deficit=Math.max(0,(Number(demand)||0)-(Number(production)||0));return deficit<=.0001?null:Math.max(0,(Number(stock)||0)/deficit);}
  relocationCost(state){return Math.round(CONFIG.RELOCATION_BASE_COST+state.pop*CONFIG.RELOCATION_PER_COLONIST+state.colony.industryLevel*CONFIG.RELOCATION_PER_INDUSTRY_LEVEL);}
  syntheticFoodRate(state){return state.contract.naturalFood===false?(state.metrics.syntheticFood||0):Math.max(0,(state.metrics.syntheticFood||0)*.35);}
}
