import { CONTRACT_ARCHETYPES } from "../data/contracts.js";

export class ContractService {
  first(){const a=CONTRACT_ARCHETYPES[0];return this.make(a,1,0,true);}
  archetype(contract){return CONTRACT_ARCHETYPES.find(x=>x.id===contract.arch)||CONTRACT_ARCHETYPES[0];}
  make(a,progressTier,index=0,intro=false){const scale=1+(Math.max(1,progressTier)-1)*.34+(a.colonyTier-1)*.14;return{uid:`${intro?"intro":a.id}-${Date.now()}-${index}`,tier:progressTier,colonyTier:a.colonyTier,name:intro?"Koplin Mining Charter — Contract 01":`${a.name} — Claim T${a.colonyTier}`,arch:a.id,environment:a.environment,hazard:a.hazard,supportSystem:a.supportSystem,techAccess:a.techAccess,requiredTech:{...a.requiredTech},naturalFood:a.naturalFood,years:10,ext:0,extUsed:0,advance:intro?0:Math.round(60000*progressTier*(1+.18*(a.colonyTier-1))),goals:{food:Math.round(620*scale*(a.naturalFood?1:.55)),industry:Math.round(520*scale),pop:Math.round(1050*scale)},bands:{silver:Math.round(450000*scale),gold:Math.round(1000000*scale),plat:Math.round(2200000*scale)},startEarn:0,desc:a.hazard};}
  options(progressTier){const maxTier=Math.min(5,Math.max(2,progressTier+1));const pool=CONTRACT_ARCHETYPES.filter(a=>a.colonyTier<=maxTier+1).sort((a,b)=>a.colonyTier-b.colonyTier||Math.random()-.5);const picks=[];for(const a of pool){if(picks.length>=5)break;picks.push(a);}while(picks.length<5)picks.push(CONTRACT_ARCHETYPES[picks.length%CONTRACT_ARCHETYPES.length]);return picks.map((a,i)=>this.make(a,progressTier,i));}
  start(state,contract){state.company.cash+=contract.advance||0;contract.startEarn=state.company.earn;state.contract=contract;state.year=1;state.day=1;state.pop=120;state.speed=1;state.status="playing";state.tiles={};state.scans=[];state.scanQueue=[];state.camera={x:-4,y:-4};}
  score(state){const g=state.contract.goals,profit=state.company.earn-state.contract.startEarn,ratios={food:state.metrics.food/g.food,industry:state.metrics.industry/g.industry,pop:state.pop/g.pop},passed=Object.values(ratios).every(x=>x>=1);let rating=passed?"Bronze":"Failed";if(passed&&profit>=state.contract.bands.silver)rating="Silver";if(passed&&profit>=state.contract.bands.gold&&Math.min(...Object.values(ratios))>=1.2)rating="Gold";if(passed&&profit>=state.contract.bands.plat&&Math.min(...Object.values(ratios))>=1.5)rating="Platinum";return{passed,rating,profit,ratios};}
  extend(state){if(state.contract.extUsed>=3)return false;const n=state.contract.extUsed+1,fee=25000*n*state.contract.tier;if(state.company.cash<fee)return false;state.company.cash-=fee;state.contract.extUsed++;state.contract.ext++;return true;}
}
