import { CONFIG } from "../core/config.js?v=5.5.1";
import { CONTRACT_ARCHETYPES } from "../data/contracts.js?v=5.5.1";

export class ContractService {
  absoluteDay(state){return(Math.max(1,Number(state.year)||1)-1)*CONFIG.DAYS_PER_YEAR+Math.max(1,Number(state.day)||1);}
  contractAgeDays(state){return Math.max(1,this.absoluteDay(state)-Math.max(1,Number(state.contract?.startAbsoluteDay)||1)+1);}
  contractYear(state){return Math.floor((this.contractAgeDays(state)-1)/CONFIG.DAYS_PER_YEAR)+1;}
  contractDay(state){return(this.contractAgeDays(state)-1)%CONFIG.DAYS_PER_YEAR+1;}
  first(){const a=CONTRACT_ARCHETYPES[0];return this.make(a,1,0,true);}
  archetype(contract){return CONTRACT_ARCHETYPES.find(x=>x.id===contract.arch)||CONTRACT_ARCHETYPES[0];}
  make(a,progressTier,index=0,intro=false){const scale=1+(Math.max(1,progressTier)-1)*.34+(a.colonyTier-1)*.14;return{uid:`${intro?"intro":a.id}-${Date.now()}-${index}`,tier:progressTier,colonyTier:a.colonyTier,name:intro?"Koplin Mining Charter — Contract 01":`${a.name} — Claim T${a.colonyTier}`,colonyName:intro?"Colony 01":null,arch:a.id,environment:a.environment,hazard:a.hazard,supportSystem:a.supportSystem,supportLoad:a.supportLoad||1,techAccess:a.techAccess,requiredTech:{...a.requiredTech},naturalFood:a.naturalFood,years:10,ext:0,extUsed:0,renewals:0,completed:false,completionAwarded:false,ended:false,advance:intro?0:Math.round(60000*progressTier*(1+.18*(a.colonyTier-1))),goals:{food:Math.round(120*scale*(a.naturalFood?1:.25)),industry:Math.round(520*scale),pop:Math.round(1050*scale)},bands:{silver:Math.round(450000*scale),gold:Math.round(1000000*scale),plat:Math.round(2200000*scale)},startEarn:0,localRevenue:0,localCosts:0,desc:a.hazard};}
  options(progressTier){const maxTier=Math.min(5,Math.max(2,progressTier+1));const pool=CONTRACT_ARCHETYPES.filter(a=>a.colonyTier<=maxTier+1).sort((a,b)=>a.colonyTier-b.colonyTier||Math.random()-.5);const picks=[];for(const a of pool){if(picks.length>=5)break;picks.push(a);}while(picks.length<5)picks.push(CONTRACT_ARCHETYPES[picks.length%CONTRACT_ARCHETYPES.length]);return picks.map((a,i)=>this.make(a,progressTier,i));}
  score(state){const g=state.contract.goals,profit=(Number(state.contract.localRevenue)||0)-(Number(state.contract.localCosts)||0),ratios={food:g.food?state.metrics.food/g.food:1,industry:g.industry?state.metrics.industry/g.industry:1,pop:g.pop?state.pop/g.pop:1},passed=state.status!=="dead"&&Object.values(ratios).every(x=>x>=1);let rating=passed?"Bronze":"Failed";if(passed&&profit>=state.contract.bands.silver)rating="Silver";if(passed&&profit>=state.contract.bands.gold&&Math.min(...Object.values(ratios))>=1.2)rating="Gold";if(passed&&profit>=state.contract.bands.plat&&Math.min(...Object.values(ratios))>=1.5)rating="Platinum";return{passed,rating,profit,ratios,revenue:state.contract.localRevenue||0,costs:state.contract.localCosts||0};}
  deadline(state){return state.contract.years+state.contract.ext;}
  deadlineDays(state){return this.deadline(state)*CONFIG.DAYS_PER_YEAR;}
  deadlineState(state){if(state.status==="dead"||this.contractAgeDays(state)<=this.deadlineDays(state)||state.status!=="playing")return null;if(state.contract.completed)return"renewal-ended";const score=this.score(state);if(score.passed)return"complete";if(state.contract.extUsed<CONFIG.MAX_EXTENSIONS)return"extension";return"failed";}
  awardCompletion(state){const score=this.score(state);if(!score.passed)return{ok:false,score};if(!state.contract.completionAwarded){state.company.wins++;state.company.rep+=({Bronze:1,Silver:2,Gold:4,Platinum:7}[score.rating]||1);state.contract.completionAwarded=true;}state.contract.completed=true;state.status="holdover";return{ok:true,score};}
  enterHoldover(state){state.status="holdover";state.contract.completed=true;return true;}
  extensionFee(state){const n=state.contract.extUsed+1;return 25000*n*state.contract.tier;}
  extend(state){if(state.contract.extUsed>=CONFIG.MAX_EXTENSIONS)return false;const fee=this.extensionFee(state);if(state.company.cash<fee)return false;state.company.cash-=fee;state.contract.localCosts=(state.contract.localCosts||0)+fee;state.contract.extUsed++;state.contract.ext++;state.status="playing";return true;}
  renewalFee(state){const tier=Math.max(1,state.contract.tier||1),world=1+.35*Math.max(0,(state.contract.colonyTier||1)-1),renewal=Math.pow(2.1,state.contract.renewals||0);return Math.round(100000*tier*world*renewal);}
  renew(state){if(!state.contract.completed||state.contract.ended||state.status==="dead")return{ok:false,reason:"This colony is not eligible for renewal."};const fee=this.renewalFee(state);if(state.company.cash<fee)return{ok:false,reason:"Insufficient cash.",fee};state.company.cash-=fee;state.contract.localCosts=(state.contract.localCosts||0)+fee;state.contract.renewals=(state.contract.renewals||0)+1;state.contract.ext+=CONFIG.RENEWAL_YEARS;state.status="playing";state.speed=1;return{ok:true,fee,years:CONFIG.RENEWAL_YEARS};}
  isOperating(state){return["playing","holdover","liability"].includes(state.status);}
  canOpenAdditional(state){return!state.company.gameOver&&(state.company.wins||0)>=1;}
  resourceHealth(state){let finiteInitial=0,finiteRemaining=0,renewable=0,known=0;for(const tile of Object.values(state.tiles||{})){if(!tile.revealed)continue;known++;if(tile.sustainability==="renewable"||tile.type==="food"||tile.resourceId==="biomass"||tile.resourceId==="fiber"){if(!tile.depleted&&!tile.renewableWiped)renewable++;continue;}const initial=Math.max(0,Number(tile.initialReserve)||0),remaining=Math.max(0,Number(tile.reserve)||0);finiteInitial+=initial;finiteRemaining+=Math.min(initial||remaining,remaining);}const ratio=finiteInitial>0?finiteRemaining/finiteInitial:0,accepted=renewable>0||ratio>=CONFIG.RETURN_MIN_RESOURCE_RATIO;return{accepted,ratio,renewable,known,threshold:CONFIG.RETURN_MIN_RESOURCE_RATIO};}
  endAsLiability(state){if(state.status==="dead")return false;state.contract.ended=true;state.trade.active=false;state.status="liability";state.speed=1;return true;}
}
