import { CONFIG } from "../core/config.js?v=5.3.0";

export class SimulationEngine {
  constructor(resourceService,technologyService,collectionService,tradeService,inventoryService,colonyService){Object.assign(this,{resources:resourceService,technology:technologyService,collection:collectionService,trade:tradeService,inventory:inventoryService,colony:colonyService});}
  production(state){let food=0,build=0,fuel=0,ore=0;const sites=this.collection.activeSites(state);for(const tile of sites){const rate=this.resources.collectionRate(state,tile);if(tile.type==="food")food+=rate;else if(tile.type==="build")build+=rate;else if(tile.type==="fuel")fuel+=rate;else ore+=rate;}const synthetic=state.status==="dead"?0:this.colony.syntheticFoodRate(state);food+=synthetic;return{food,build,fuel,ore,synthetic};}
  availableRatio(stock,production,demand){return demand>0?Math.min(1,(Math.max(0,stock)+Math.max(0,production))/demand):1;}
  recalculate(state){
    this.technology.recompute(state);const sites=this.collection.activeSites(state),prod=this.production(state),activeCount=sites.length,d=this.colony.demand(state,activeCount),foodStock=this.inventory.amount(state,"food"),buildStock=this.inventory.amount(state,"build"),fuelStock=this.inventory.amount(state,"fuel"),oreStock=this.inventory.amount(state,"ore"),foodSupply=this.availableRatio(foodStock,prod.food,d.foodDemand),fuelSupply=this.availableRatio(fuelStock,prod.fuel,d.fuelDemand),oreSupply=d.oreDemand>0?this.availableRatio(oreStock,prod.ore,d.oreDemand):1,powerFactor=state.status==="dead"?0:Math.min(1,d.capacityFactor,fuelSupply),industryFactor=state.status==="dead"||state.colony.emergencyMode?0:Math.min(powerFactor,oreSupply,d.staffFactor),industry=state.colony.industryLevel*100*industryFactor,operatingCost=this.colony.operatingCost(state,activeCount),foodDays=this.colony.supplyDays(foodStock,prod.food,d.foodDemand),fuelDays=this.colony.supplyDays(fuelStock,prod.fuel,d.fuelDemand),oreDays=d.oreDemand>0?this.colony.supplyDays(oreStock,prod.ore,d.oreDemand):null,survivalSupply=state.status==="dead"?0:Math.min(foodSupply,powerFactor);
    Object.assign(state.metrics,{food:prod.food,buildProduction:prod.build,fuelProduction:prod.fuel,oreProduction:prod.ore,industry,powerDemand:d.powerDemand,powerCapacity:d.capacity,foodDemand:d.foodDemand,fuelDemand:d.fuelDemand,oreDemand:d.oreDemand,foodSupply,fuelSupply,oreSupply,powerFactor,industryStaffFactor:d.staffFactor,industryPopulationRequired:d.populationRequired,supportLoad:d.supportLoad,survivalSupply,foodDays,fuelDays,oreDays,operatingCost,stockValue:this.trade.stockValue(state),foodStock,buildStock,fuelStock,oreStock});
  }
  mortalityRate(stable){if(stable>=.7)return 0;if(stable>=.4){const t=(.7-stable)/.3;return CONFIG.CRITICAL_MORTALITY_MIN+t*(CONFIG.CRITICAL_MORTALITY_MAX-CONFIG.CRITICAL_MORTALITY_MIN);}const t=(.4-Math.max(0,stable))/.4;return CONFIG.CRITICAL_MORTALITY_MAX+t*(CONFIG.COLLAPSE_MORTALITY_MAX-CONFIG.CRITICAL_MORTALITY_MAX);}
  killColony(state){if(state.status==="dead")return false;state.pop=0;state.status="dead";state.speed=0;state.contract.ended=true;state.contract.failedByDeath=true;state.contract.deathYear=state.year;state.contract.deathDay=state.day;state.trade.active=false;state.trade.arrivedAt=null;state.colony.emergencyMode=false;state.company.rep=Math.max(0,(Number(state.company.rep)||0)-CONFIG.COLONY_DEATH_REP_PENALTY);return true;}
  tick(state){
    if(state.status==="dead")return{colonyDied:false,deaths:0,populationDelta:0};
    this.technology.recompute(state);const active=[...this.collection.activeSites(state)];let foodProd=0,buildProd=0,fuelProd=0,oreProd=0;
    for(const tile of active){const result=this.collection.collectDay(state,tile),q=result.collected;this.inventory.storeTile(state,tile,q);if(tile.type==="food")foodProd+=q;else if(tile.type==="build")buildProd+=q;else if(tile.type==="fuel")fuelProd+=q;else oreProd+=q;}
    const synthetic=this.colony.syntheticFoodRate(state);if(synthetic>0){this.inventory.store(state,"food","synthetic","Synthetic Nutrient",synthetic);foodProd+=synthetic;}
    const d=this.colony.demand(state,active.length),foodUse=this.inventory.consumeCategory(state,"food",d.foodDemand),fuelUse=this.inventory.consumeCategory(state,"fuel",d.fuelDemand),powerFactor=Math.min(d.capacityFactor,fuelUse.ratio),oreUse=d.oreDemand>0?this.inventory.consumeCategory(state,"ore",d.oreDemand):{ratio:1,consumed:0},industryFactor=state.colony.emergencyMode?0:Math.min(powerFactor,oreUse.ratio,d.staffFactor),industry=state.colony.industryLevel*100*industryFactor;
    const operatingCost=this.colony.operatingCost(state,active.length);state.company.cash-=operatingCost;state.contract.localCosts=(state.contract.localCosts||0)+operatingCost;
    const before=state.pop,stable=Math.min(foodUse.ratio,powerFactor),target=this.colony.populationCapacity(state);let deaths=0;
    if(stable>=.95&&!state.colony.emergencyMode&&state.pop<target){const growth=Math.max(.002,state.pop*CONFIG.NATURAL_GROWTH_RATE);state.pop=Math.min(target,state.pop+growth);}else if(stable<.7&&state.pop>0){const rate=this.mortalityRate(stable);deaths=Math.min(state.pop,Math.max(.05,state.pop*rate));state.pop=Math.max(0,state.pop-deaths);if(state.pop<.5)state.pop=0;}
    const colonyDied=state.pop<=0?this.killColony(state):false,foodStock=this.inventory.amount(state,"food"),buildStock=this.inventory.amount(state,"build"),fuelStock=this.inventory.amount(state,"fuel"),oreStock=this.inventory.amount(state,"ore"),foodDays=this.colony.supplyDays(foodStock,foodProd,d.foodDemand),fuelDays=this.colony.supplyDays(fuelStock,fuelProd,d.fuelDemand),oreDays=d.oreDemand>0?this.colony.supplyDays(oreStock,oreProd,d.oreDemand):null;
    Object.assign(state.metrics,{food:foodProd,buildProduction:buildProd,fuelProduction:fuelProd,oreProduction:oreProd,industry:colonyDied?0:industry,foodDemand:d.foodDemand,fuelDemand:d.fuelDemand,oreDemand:d.oreDemand,foodSupply:foodUse.ratio,fuelSupply:fuelUse.ratio,oreSupply:oreUse.ratio,powerDemand:d.powerDemand,powerCapacity:d.capacity,powerFactor:colonyDied?0:powerFactor,industryStaffFactor:d.staffFactor,industryPopulationRequired:d.populationRequired,supportLoad:d.supportLoad,survivalSupply:colonyDied?0:stable,foodDays,fuelDays,oreDays,lastDeaths:deaths,populationDelta:state.pop-before,operatingCost,totalOperatingCost:(state.metrics.totalOperatingCost||0)+operatingCost,stockValue:this.trade.stockValue(state),foodStock,buildStock,fuelStock,oreStock});
    state.day++;if(state.day>CONFIG.DAYS_PER_YEAR){state.day=1;state.year++;}return{colonyDied,deaths,populationDelta:state.pop-before};
  }
}
