export class SimulationEngine {
  constructor(resourceService,technologyService,collectionService,tradeService,inventoryService,colonyService){Object.assign(this,{resources:resourceService,technology:technologyService,collection:collectionService,trade:tradeService,inventory:inventoryService,colony:colonyService});}
  production(state){let food=0,build=0,fuel=0,ore=0;for(const tile of this.collection.activeSites(state)){const rate=this.resources.collectionRate(state,tile);if(tile.type==="food")food+=rate;else if(tile.type==="build")build+=rate;else if(tile.type==="fuel")fuel+=rate;else ore+=rate;}const synthetic=this.colony.syntheticFoodRate(state);food+=synthetic;return{food,build,fuel,ore,synthetic};}
  recalculate(state){this.technology.recompute(state);const prod=this.production(state),activeCount=this.collection.activeSites(state).length,d=this.colony.demand(state,activeCount),foodStock=this.inventory.amount(state,"food"),buildStock=this.inventory.amount(state,"build"),fuelStock=this.inventory.amount(state,"fuel"),oreStock=this.inventory.amount(state,"ore"),foodSupply=d.foodDemand>0?Math.min(1,foodStock/d.foodDemand):1,fuelSupply=d.fuelDemand>0?Math.min(1,fuelStock/d.fuelDemand):1,oreSupply=d.oreDemand>0?Math.min(1,oreStock/d.oreDemand):1,powerFactor=Math.min(1,d.capacityFactor,fuelSupply),industry=state.colony.industryLevel*100*powerFactor*oreSupply;Object.assign(state.metrics,{food:prod.food,industry,powerDemand:d.powerDemand,powerCapacity:d.capacity,foodDemand:d.foodDemand,fuelDemand:d.fuelDemand,oreDemand:d.oreDemand,foodSupply,fuelSupply,oreSupply,powerFactor,stockValue:this.trade.stockValue(state),foodStock,buildStock,fuelStock,oreStock});}
  tick(state){
    this.technology.recompute(state);
    const active=[...this.collection.activeSites(state)];let foodProd=0,buildProd=0,fuelProd=0,oreProd=0;
    for(const tile of active){const result=this.collection.collectDay(state,tile),q=result.collected;this.inventory.storeTile(state,tile,q);if(tile.type==="food")foodProd+=q;else if(tile.type==="build")buildProd+=q;else if(tile.type==="fuel")fuelProd+=q;else oreProd+=q;}
    const synthetic=this.colony.syntheticFoodRate(state);if(synthetic>0){this.inventory.store(state,"food","synthetic","Synthetic Nutrient",synthetic);foodProd+=synthetic;}
    const d=this.colony.demand(state,active.length),foodUse=this.inventory.consumeCategory(state,"food",d.foodDemand),fuelUse=this.inventory.consumeCategory(state,"fuel",d.fuelDemand),powerFactor=Math.min(d.capacityFactor,fuelUse.ratio),oreUse=this.inventory.consumeCategory(state,"ore",d.oreDemand),industryFactor=Math.min(powerFactor,oreUse.ratio),industry=state.colony.industryLevel*100*industryFactor;
    const stable=Math.min(foodUse.ratio,powerFactor),target=Math.min(state.colony.housingCapacity,state.metrics.powerPopulationCap);if(stable>=.95&&state.pop<target)state.pop+=Math.max(.03,(target-state.pop)*.0015);else if(stable<.75)state.pop=Math.max(40,state.pop-Math.max(.02,state.pop*(.75-stable)*.0012));
    Object.assign(state.metrics,{food:foodProd,industry,foodDemand:d.foodDemand,fuelDemand:d.fuelDemand,oreDemand:d.oreDemand,foodSupply:foodUse.ratio,fuelSupply:fuelUse.ratio,oreSupply:oreUse.ratio,powerDemand:d.powerDemand,powerCapacity:d.capacity,powerFactor,stockValue:this.trade.stockValue(state),foodStock:this.inventory.amount(state,"food"),buildStock:this.inventory.amount(state,"build"),fuelStock:this.inventory.amount(state,"fuel"),oreStock:this.inventory.amount(state,"ore")});
    state.day++;if(state.day>360){state.day=1;state.year++;}
  }
}
