export class SiteService {
  constructor(contractService,technologyService,inventoryService,colonyService=null){this.contracts=contractService;this.technology=technologyService;this.inventory=inventoryService;this.colony=colonyService;}
  distance(tile){return Math.hypot(tile.x,tile.y);}
  addLocalCost(state,amount){state.contract.localCosts=(state.contract.localCosts||0)+Math.max(0,amount||0);}
  developCashCost(state,tile){const a=this.contracts.archetype(state.contract);return Math.round((1800+Math.sqrt(tile.quality)*70)*(1+this.distance(tile)*.018)*a.cost);}
  developBuildCost(state,tile){const a=this.contracts.archetype(state.contract);return Math.round((28+Math.sqrt(tile.quality)*.42+this.distance(tile)*1.2)*a.cost);}
  upgradeCashCost(state,tile){return Math.round(this.developCashCost(state,tile)*Math.pow(1.68,Math.max(0,tile.level)));}
  upgradeBuildCost(state,tile){return Math.round(this.developBuildCost(state,tile)*Math.pow(1.38,Math.max(0,tile.level)));}
  developCost(state,tile){return this.developCashCost(state,tile);}
  upgradeCost(state,tile){return this.upgradeCashCost(state,tile);}
  developRequirements(state,tile){const cash=this.developCashCost(state,tile),build=this.developBuildCost(state,tile),requiredLevel=tile.requiredMiningLevel||1,techOk=this.technology.canExploit(state,tile);if(state.contract.ended)return{ok:false,cash,build,requiredLevel,reason:"Mining contract ended. This colony is support-only."};if(!tile.revealed||tile.developed||tile.depleted)return{ok:false,cash,build,requiredLevel,reason:"Site unavailable."};if(!techOk)return{ok:false,cash,build,requiredLevel,reason:`Requires Mining L${requiredLevel}: ${tile.requiredMiningTech||"Extraction technology"}.`};if(this.inventory.amount(state,"build")<build)return{ok:false,cash,build,requiredLevel,reason:`Need ${build} Build materials.`};if(state.company.cash<cash)return{ok:false,cash,build,requiredLevel,reason:"Insufficient cash."};return{ok:true,cash,build,requiredLevel};}
  develop(state,tile){const r=this.developRequirements(state,tile);if(!r.ok)return r;this.inventory.consumeCategory(state,"build",r.build);state.company.cash-=r.cash;this.addLocalCost(state,r.cash);tile.developed=true;tile.level=1;return{ok:true,...r};}
  upgradeRequirements(state,tile){const cash=this.upgradeCashCost(state,tile),build=this.upgradeBuildCost(state,tile),nextLevel=Math.max(1,Number(tile.level)||1)+1,industryRequired=this.colony?.siteUpgradeIndustryRequirement(nextLevel)||1;if(state.contract.ended)return{ok:false,cash,build,industryRequired,reason:"Mining contract ended. This colony is support-only."};if(!tile.developed||tile.depleted)return{ok:false,cash,build,industryRequired,reason:"Site unavailable."};if(!this.technology.canExploit(state,tile))return{ok:false,cash,build,industryRequired,reason:`Requires Mining L${tile.requiredMiningLevel||1}.`};if((state.colony?.industryLevel||1)<industryRequired)return{ok:false,cash,build,industryRequired,reason:`Upgrade to site L${nextLevel} requires Industry L${industryRequired}.`};if(this.inventory.amount(state,"build")<build)return{ok:false,cash,build,industryRequired,reason:`Need ${build} Build materials.`};if(state.company.cash<cash)return{ok:false,cash,build,industryRequired,reason:"Insufficient cash."};return{ok:true,cash,build,industryRequired};}
  upgrade(state,tile){const r=this.upgradeRequirements(state,tile);if(!r.ok)return r;this.inventory.consumeCategory(state,"build",r.build);state.company.cash-=r.cash;this.addLocalCost(state,r.cash);tile.level++;return{ok:true,...r};}
}
