import { CONFIG } from "../core/config.js?v=5.4.0";

export class TradeService {
  constructor(resourceService,inventoryService){this.resources=resourceService;this.inventory=inventoryService;}
  absoluteDay(state){return(Math.max(1,state.year)-1)*CONFIG.DAYS_PER_YEAR+Math.max(1,state.day);}
  catalog(){return this.resources.catalog().map(def=>({key:this.inventory.key(def.type,def.id),type:def.type,resourceId:def.id,name:def.name,category:def.category,rarity:def.rarity,sellPrice:def.sellPrice})).sort((a,b)=>a.category.localeCompare(b.category)||a.name.localeCompare(b.name));}
  stock(state){return this.inventory.stock(state);}
  processingBonus(state){return Math.max(0,Math.min(CONFIG.INDUSTRY_PROCESSING_MAX_BONUS,Number(state?.metrics?.processingBonus)||0));}
  processingMultiplier(state){return 1+this.processingBonus(state);}
  qualityRows(entry,state=null){return this.inventory.bands(entry).map(band=>{const unitPrice=state?this.exportPrice(state,entry.type,entry.resourceId,band.key):this.sellPrice(entry.type,entry.resourceId,band.key);return{...band,unitPrice,value:band.amount*unitPrice};});}
  store(state,tile,amount){return this.inventory.storeTile(state,tile,amount);}
  sellPrice(itemOrType,resourceId=null,qualityBandKey=null){if(typeof itemOrType==="object"){const item=itemOrType;return this.resources.sellPrice(item.type,item.resourceId,qualityBandKey||item.qualityBandKey||null);}return this.resources.sellPrice(itemOrType,resourceId,qualityBandKey);}
  exportPrice(state,itemOrType,resourceId=null,qualityBandKey=null){return this.sellPrice(itemOrType,resourceId,qualityBandKey)*this.processingMultiplier(state);}
  buyPrice(itemOrType,resourceId=null){return this.sellPrice(itemOrType,resourceId)*CONFIG.CORPORATE_BUY_MARKUP;}
  stockValue(state){return this.stock(state).reduce((sum,e)=>sum+this.qualityRows(e,state).reduce((s,b)=>s+b.value,0),0);}
  cargoCapacity(state){return Math.min(CONFIG.TRADE_MAX_CARGO,CONFIG.TRADE_BASE_CARGO+Math.max(0,Number(state.company.rep)||0)*CONFIG.TRADE_CARGO_PER_REP);}
  cargoRemaining(state){return Math.max(0,this.cargoCapacity(state)-(Number(state.trade.cargoUsed)||0));}
  passengerRemaining(state){return Math.max(0,CONFIG.TRADE_PASSENGER_CAPACITY-(Number(state.trade.passengersUsed)||0));}
  colonistCapacity(state){return Math.max(0,Math.floor(Math.min(state.colony.housingCapacity,state.metrics.powerPopulationCap||state.colony.housingCapacity)-state.pop));}
  colonistTransferCost(state,amount){return Math.round(Math.max(0,Number(amount)||0)*CONFIG.COLONIST_TRANSFER_COST*Math.max(.5,Number(state.contract.supportLoad)||1));}
  canTransferColonists(state,amount){const qty=Math.max(0,Math.floor(Number(amount)||0)),cost=this.colonistTransferCost(state,qty);if(!state.trade.active)return{ok:false,reason:"No corporate ship is docked.",qty,cost};if(state.status==="dead"||state.contract.ended)return{ok:false,reason:"This colony cannot receive colonists.",qty,cost};if(qty<=0)return{ok:false,reason:"No colonists selected.",qty,cost};if(this.passengerRemaining(state)<qty)return{ok:false,reason:`Only ${this.passengerRemaining(state)} passenger berths remain this visit.`,qty,cost};if(this.colonistCapacity(state)<qty)return{ok:false,reason:`Only ${this.colonistCapacity(state)} supported housing places are available.`,qty,cost};if(state.company.cash<cost)return{ok:false,reason:"Insufficient cash for colonist transfer.",qty,cost};return{ok:true,qty,cost};}
  transferColonists(state,amount){const r=this.canTransferColonists(state,amount);if(!r.ok)return r;state.company.cash-=r.cost;state.contract.localCosts=(state.contract.localCosts||0)+r.cost;state.pop+=r.qty;state.trade.passengersUsed=(Number(state.trade.passengersUsed)||0)+r.qty;return{ok:true,qty:r.qty,cost:r.cost,pop:state.pop};}
  shouldArrive(state){const supported=["playing","holdover","liability"].includes(state.status),charterAllows=!state.contract.ended||state.status==="liability";return supported&&charterAllows&&!state.trade.active&&this.absoluteDay(state)>=state.trade.nextArrivalDay;}
  arrive(state){if(state.trade.active||state.status==="dead")return false;state.trade.active=true;state.trade.returnSpeed=state.speed>0?state.speed:1;state.trade.arrivedAt=this.absoluteDay(state);state.trade.cargoUsed=0;state.trade.passengersUsed=0;state.trade.visits++;do{state.trade.nextArrivalDay+=CONFIG.TRADE_INTERVAL_DAYS;}while(state.trade.nextArrivalDay<=state.trade.arrivedAt);state.speed=0;return true;}
  depart(state){if(!state.trade.active)return false;state.trade.active=false;state.trade.arrivedAt=null;if(["playing","holdover","liability"].includes(state.status))state.speed=state.trade.returnSpeed||1;return true;}
  daysUntilArrival(state){return state.trade.active?0:Math.max(0,state.trade.nextArrivalDay-this.absoluteDay(state));}
  sellBand(state,key,bandKey,amount){
    if(!state.trade.active)return{ok:false,reason:"No corporate ship is docked."};const entry=state.inventory[key];if(!entry)return{ok:false,reason:"No stock available."};this.inventory.ensureEntry(state,entry.type,entry.resourceId,entry.name);const band=entry.qualityBands?.[bandKey],available=Math.max(0,Number(band?.amount)||0);if(!available)return{ok:false,reason:"No stock available in that quality band."};const qty=Math.min(available,Math.max(0,Number(amount)||0));if(qty<=0)return{ok:false,reason:"Nothing selected."};const unitPrice=this.exportPrice(state,entry.type,entry.resourceId,bandKey),revenue=qty*unitPrice;band.amount-=qty;this.inventory.syncEntry(entry);state.company.cash+=revenue;state.company.earn+=revenue;state.contract.localRevenue=(state.contract.localRevenue||0)+revenue;return{ok:true,qty,revenue,unitPrice,bandKey,entry,processingBonus:this.processingBonus(state)};
  }
  sell(state,key,amount,bandKey=null){
    if(bandKey)return this.sellBand(state,key,bandKey,amount);if(!state.trade.active)return{ok:false,reason:"No corporate ship is docked."};const entry=state.inventory[key];if(!entry||this.inventory.syncEntry(entry).amount<=0)return{ok:false,reason:"No stock available."};let remaining=Math.min(entry.amount,Math.max(0,Number(amount)||0)),qty=0,revenue=0;for(const band of this.qualityRows(entry,state).sort((a,b)=>a.unitPrice-b.unitPrice)){if(remaining<=0)break;const r=this.sellBand(state,key,band.key,Math.min(remaining,band.amount));if(r.ok){remaining-=r.qty;qty+=r.qty;revenue+=r.revenue;}}return{ok:qty>0,qty,revenue,entry};
  }
  sellAll(state){let revenue=0,qty=0;for(const entry of this.stock(state)){for(const band of [...this.qualityRows(entry,state)]){const r=this.sellBand(state,entry.key,band.key,band.amount);if(r.ok){revenue+=r.revenue;qty+=r.qty;}}}return{ok:qty>0,revenue,qty};}
  buy(state,key,amount){if(!state.trade.active)return{ok:false,reason:"No corporate ship is docked."};const item=this.catalog().find(x=>x.key===key);if(!item)return{ok:false,reason:"Unknown resource."};const requested=Math.max(0,Math.floor(Number(amount)||0));if(!requested)return{ok:false,reason:"Nothing selected."};const cargo=this.cargoRemaining(state);if(cargo<=0)return{ok:false,reason:"Ship import cargo capacity is exhausted for this visit."};const price=this.buyPrice(item),affordable=Math.floor(Math.max(0,state.company.cash)/price),qty=Math.min(requested,affordable,cargo);if(qty<=0)return{ok:false,reason:"Insufficient cash."};const cost=qty*price;this.inventory.store(state,item.type,item.resourceId,item.name,qty);const entry=this.inventory.ensureEntry(state,item.type,item.resourceId,item.name);state.company.cash-=cost;state.contract.localCosts=(state.contract.localCosts||0)+cost;state.trade.cargoUsed=(Number(state.trade.cargoUsed)||0)+qty;return{ok:true,qty,cost,entry,cargoRemaining:this.cargoRemaining(state)};}
}
