import { CONFIG } from "../core/config.js";
import { ExpansionService } from "./expansion-service.js";
import { ensureSpaceport,hasFreeBerth } from "./spaceport-model.js";

/** Canonical corporate trade service, including service radius and shared Spaceport berth rules. */
export class TradeService {
  constructor(resourceService,inventoryService){this.resources=resourceService;this.inventory=inventoryService;this.expansion=new ExpansionService(inventoryService,resourceService);}
  absoluteDay(state){return(Math.max(1,state.year)-1)*CONFIG.DAYS_PER_YEAR+Math.max(1,state.day);}
  serviceAvailable(state){return this.expansion.corporateServiceAvailable(state);}
  catalog(){return this.resources.catalog().map(def=>({key:this.inventory.key(def.type,def.id),type:def.type,resourceId:def.id,name:def.name,category:def.category,rarity:def.rarity,sellPrice:def.sellPrice})).sort((a,b)=>a.category.localeCompare(b.category)||a.name.localeCompare(b.name));}
  stock(state){return this.inventory.stock(state);}
  colonyTradeReserve(state){state.colony||={};if(Number.isFinite(Number(state.colony.tradeReserve)))return Math.max(0,Math.floor(Number(state.colony.tradeReserve)||0));const legacy=Object.values(state.colony.tradeReserves||{}).reduce((max,value)=>Math.max(max,Math.max(0,Number(value)||0)),0);state.colony.tradeReserve=Math.floor(legacy);return state.colony.tradeReserve;}
  setColonyTradeReserve(state,amount){state.colony||={};state.colony.tradeReserve=Math.max(0,Math.floor(Number(amount)||0));delete state.colony.tradeReserves;return state.colony.tradeReserve;}
  tradeReserve(state,key=null){return this.colonyTradeReserve(state);}
  reserveShortfall(state,key){const entry=state.inventory?.[key],stock=entry?this.inventory.syncEntry(entry).amount:0;return Math.max(0,this.colonyTradeReserve(state)-stock);}
  sellableAmount(state,entry){return Math.max(0,this.inventory.syncEntry(entry).amount-this.colonyTradeReserve(state));}
  processingBonus(state){return Math.max(0,Math.min(CONFIG.INDUSTRY_PROCESSING_MAX_BONUS,Number(state?.metrics?.processingBonus)||0));}
  processingMultiplier(state){return 1+this.processingBonus(state);}
  qualityRows(entry,state=null){return this.inventory.bands(entry).map(band=>{const unitPrice=state?this.exportPrice(state,entry.type,entry.resourceId,band.key):this.sellPrice(entry.type,entry.resourceId,band.key);return{...band,unitPrice,value:band.amount*unitPrice};});}
  entryValue(state,entry){return this.qualityRows(entry,state).reduce((sum,row)=>sum+row.value,0);}
  entrySellableValue(state,entry){let remaining=this.sellableAmount(state,entry),value=0;for(const row of this.qualityRows(entry,state).sort((a,b)=>b.unitPrice-a.unitPrice)){if(remaining<=0)break;const take=Math.min(remaining,row.amount);remaining-=take;value+=take*row.unitPrice;}return value;}
  sellableStock(state){return this.stock(state).map(entry=>({...entry,reserve:this.colonyTradeReserve(state),sellableAmount:this.sellableAmount(state,entry),saleValue:this.entrySellableValue(state,entry)})).filter(entry=>entry.sellableAmount>.0001).sort((a,b)=>b.saleValue-a.saleValue||b.sellableAmount-a.sellableAmount||a.name.localeCompare(b.name));}
  quoteSell(state,key,amount){const entry=state.inventory?.[key];if(!entry)return{qty:0,revenue:0};let remaining=Math.min(Math.max(0,Number(amount)||0),this.sellableAmount(state,entry),this.exportRemaining(state)),qty=0,revenue=0;for(const row of this.qualityRows(entry,state).sort((a,b)=>b.unitPrice-a.unitPrice)){if(remaining<=0)break;const take=Math.min(remaining,row.amount);remaining-=take;qty+=take;revenue+=take*row.unitPrice;}return{qty,revenue};}
  sellQuoteForEntries(state,entries){const allowed=new Map(),lots=[];for(const entry of entries){allowed.set(entry.key,this.sellableAmount(state,entry));for(const band of this.qualityRows(entry,state))lots.push({entry,band});}lots.sort((a,b)=>b.band.unitPrice-a.band.unitPrice||b.band.value-a.band.value);let room=this.exportRemaining(state),qty=0,revenue=0;for(const {entry,band} of lots){if(room<=0)break;const can=Math.max(0,allowed.get(entry.key)||0),take=Math.min(room,can,band.amount);if(take<=0)continue;allowed.set(entry.key,can-take);room-=take;qty+=take;revenue+=take*band.unitPrice;}return{qty,revenue,exportRemaining:room};}
  sellAllQuote(state){return this.sellQuoteForEntries(state,this.stock(state));}
  sellCategoryQuote(state,type){return this.sellQuoteForEntries(state,this.stock(state).filter(entry=>entry.type===type));}
  store(state,tile,amount){return this.inventory.storeTile(state,tile,amount);}
  sellPrice(itemOrType,resourceId=null,qualityBandKey=null){if(typeof itemOrType==="object"){const item=itemOrType;return this.resources.sellPrice(item.type,item.resourceId,qualityBandKey||item.qualityBandKey||null);}return this.resources.sellPrice(itemOrType,resourceId,qualityBandKey);}
  exportPrice(state,itemOrType,resourceId=null,qualityBandKey=null){return this.sellPrice(itemOrType,resourceId,qualityBandKey)*this.processingMultiplier(state);}
  buyPrice(itemOrType,resourceId=null){return this.sellPrice(itemOrType,resourceId)*CONFIG.CORPORATE_BUY_MARKUP;}
  stockValue(state){return this.stock(state).reduce((sum,e)=>sum+this.entryValue(state,e),0);}
  cargoCapacity(state){return Math.min(CONFIG.TRADE_MAX_CARGO,CONFIG.TRADE_BASE_CARGO+Math.max(0,Number(state.company.rep)||0)*CONFIG.TRADE_CARGO_PER_REP);}
  cargoRemaining(state){return Math.max(0,this.cargoCapacity(state)-(Number(state.trade.cargoUsed)||0));}
  exportCapacity(state){return Math.min(CONFIG.TRADE_MAX_EXPORT_CARGO,CONFIG.TRADE_BASE_EXPORT_CARGO+Math.max(0,Number(state.company.rep)||0)*CONFIG.TRADE_EXPORT_PER_REP);}
  exportRemaining(state){return Math.max(0,this.exportCapacity(state)-(Number(state.trade.exportUsed)||0));}
  passengerRemaining(state){return Math.max(0,CONFIG.TRADE_PASSENGER_CAPACITY-(Number(state.trade.passengersUsed)||0));}
  pendingTransportPopulation(state){return(state.colony?.transportOrders||[]).reduce((sum,o)=>sum+Math.max(0,Number(o.amount)||0),0);}
  colonistCapacity(state){return Math.max(0,Math.floor(Math.min(state.colony.housingCapacity,state.metrics.powerPopulationCap||state.colony.housingCapacity)-state.pop-this.pendingTransportPopulation(state)));}
  colonistFoodSurplus(state){return(Number(state.metrics?.food)||0)-(Number(state.metrics?.foodDemand)||0);}
  colonistFoodSupportedCapacity(state){return Math.max(0,Math.floor(this.colonistFoodSurplus(state)/Math.max(.0001,CONFIG.FOOD_PER_COLONIST)));}
  colonistSafeCapacity(state){return Math.max(0,Math.min(this.colonistCapacity(state),this.passengerRemaining(state),this.colonistFoodSupportedCapacity(state)));}
  colonistFoodSurplusAfter(state,amount){return this.colonistFoodSurplus(state)-Math.max(0,Number(amount)||0)*CONFIG.FOOD_PER_COLONIST;}
  colonistTransferCost(state,amount){return Math.round(Math.max(0,Number(amount)||0)*CONFIG.COLONIST_TRANSFER_COST*Math.max(.5,Number(state.contract.supportLoad)||1));}
  canTransferColonists(state,amount){const qty=Math.max(0,Math.floor(Number(amount)||0)),cost=this.colonistTransferCost(state,qty);if(!state.trade.active)return{ok:false,reason:"No corporate ship is docked.",qty,cost};if(state.status==="dead"||state.contract.ended)return{ok:false,reason:"This colony cannot receive colonists.",qty,cost};if(qty<=0)return{ok:false,reason:"No colonists selected.",qty,cost};if(this.passengerRemaining(state)<qty)return{ok:false,reason:`Only ${this.passengerRemaining(state)} passenger berths remain this visit.`,qty,cost};if(this.colonistCapacity(state)<qty)return{ok:false,reason:`Only ${this.colonistCapacity(state)} supported housing places remain after pending transports.`,qty,cost};if(state.company.cash<cost)return{ok:false,reason:"Insufficient cash for colonist transfer.",qty,cost};return{ok:true,qty,cost};}
  transferColonists(state,amount){const r=this.canTransferColonists(state,amount);if(!r.ok)return r;state.company.cash-=r.cost;state.contract.localCosts=(state.contract.localCosts||0)+r.cost;state.pop+=r.qty;state.trade.passengersUsed=(Number(state.trade.passengersUsed)||0)+r.qty;return{ok:true,qty:r.qty,cost:r.cost,pop:state.pop};}
  scheduledAndSupported(state){if(!this.serviceAvailable(state))return false;const supported=["playing","holdover","liability"].includes(state.status),charterAllows=!state.contract.ended||state.status==="liability";return supported&&charterAllows&&!state.trade.active&&this.absoluteDay(state)>=state.trade.nextArrivalDay;}
  shouldArrive(state){
    ensureSpaceport(state);if(!this.scheduledAndSupported(state))return false;
    if(!hasFreeBerth(state)){state.trade.orbitalHolding=true;state.trade.orbitalSinceAbsoluteDay??=this.absoluteDay(state);return false;}
    return true;
  }
  arrive(state){
    ensureSpaceport(state);if(!this.serviceAvailable(state)||state.trade.active||state.status==="dead")return false;if(!hasFreeBerth(state)){state.trade.orbitalHolding=true;state.trade.orbitalSinceAbsoluteDay??=this.absoluteDay(state);return false;}
    state.trade.active=true;state.trade.orbitalHolding=false;state.trade.orbitalSinceAbsoluteDay=null;state.trade.arrivedAt=this.absoluteDay(state);state.trade.cargoUsed=0;state.trade.exportUsed=0;state.trade.passengersUsed=0;state.trade.visits++;do{state.trade.nextArrivalDay+=CONFIG.TRADE_INTERVAL_DAYS;}while(state.trade.nextArrivalDay<=state.trade.arrivedAt);return true;
  }
  depart(state){if(!state.trade.active)return false;state.trade.active=false;state.trade.arrivedAt=null;return true;}
  daysUntilArrival(state){return this.serviceAvailable(state)?(state.trade.active||state.trade.orbitalHolding?0:Math.max(0,state.trade.nextArrivalDay-this.absoluteDay(state))):Infinity;}
  sellBand(state,key,bandKey,amount){if(!state.trade.active)return{ok:false,reason:"No corporate ship is docked."};const entry=state.inventory[key];if(!entry)return{ok:false,reason:"No stock available."};this.inventory.ensureEntry(state,entry.type,entry.resourceId,entry.name);const band=entry.qualityBands?.[bandKey],available=Math.max(0,Number(band?.amount)||0);if(!available)return{ok:false,reason:"No stock available in that quality band."};const exportRoom=this.exportRemaining(state);if(exportRoom<=0)return{ok:false,reason:"Ship export capacity is exhausted for this visit."};const aboveReserve=this.sellableAmount(state,entry);if(aboveReserve<=0)return{ok:false,reason:"This stock is protected by the colony trade reserve."};const qty=Math.min(available,Math.max(0,Number(amount)||0),exportRoom,aboveReserve);if(qty<=0)return{ok:false,reason:"Nothing selected."};const unitPrice=this.exportPrice(state,entry.type,entry.resourceId,bandKey),revenue=qty*unitPrice;band.amount-=qty;this.inventory.syncEntry(entry);state.company.cash+=revenue;state.company.earn+=revenue;state.contract.localRevenue=(state.contract.localRevenue||0)+revenue;state.trade.exportUsed=(Number(state.trade.exportUsed)||0)+qty;return{ok:true,qty,revenue,unitPrice,bandKey,entry,processingBonus:this.processingBonus(state),exportRemaining:this.exportRemaining(state)};}
  sell(state,key,amount,bandKey=null){if(bandKey)return this.sellBand(state,key,bandKey,amount);if(!state.trade.active)return{ok:false,reason:"No corporate ship is docked."};const entry=state.inventory[key];if(!entry||this.inventory.syncEntry(entry).amount<=0)return{ok:false,reason:"No stock available."};let remaining=Math.min(this.sellableAmount(state,entry),Math.max(0,Number(amount)||0)),qty=0,revenue=0;if(remaining<=0)return{ok:false,reason:"This stock is protected by the colony trade reserve."};for(const band of this.qualityRows(entry,state).sort((a,b)=>b.unitPrice-a.unitPrice)){if(remaining<=0||this.exportRemaining(state)<=0)break;const r=this.sellBand(state,key,band.key,Math.min(remaining,band.amount));if(r.ok){remaining-=r.qty;qty+=r.qty;revenue+=r.revenue;}}return{ok:qty>0,qty,revenue,entry,exportRemaining:this.exportRemaining(state)};}
  sellEntries(state,entries){const candidates=[];for(const entry of entries)for(const band of this.qualityRows(entry,state))candidates.push({entry,band});candidates.sort((a,b)=>b.band.unitPrice-a.band.unitPrice||b.band.value-a.band.value);let revenue=0,qty=0;for(const {entry,band} of candidates){if(this.exportRemaining(state)<=0)break;const r=this.sellBand(state,entry.key,band.key,band.amount);if(r.ok){revenue+=r.revenue;qty+=r.qty;}}return{ok:qty>0,revenue,qty,exportRemaining:this.exportRemaining(state),reason:qty>0?null:"Nothing is available above the colony reserve or export capacity."};}
  sellAll(state){return this.sellEntries(state,this.stock(state));}
  sellCategory(state,type){return this.sellEntries(state,this.stock(state).filter(entry=>entry.type===type));}
  buy(state,key,amount){if(!state.trade.active)return{ok:false,reason:"No corporate ship is docked."};const item=this.catalog().find(x=>x.key===key);if(!item)return{ok:false,reason:"Unknown resource."};const requested=Math.max(0,Math.floor(Number(amount)||0));if(!requested)return{ok:false,reason:"Nothing selected."};const cargo=this.cargoRemaining(state);if(cargo<=0)return{ok:false,reason:"Ship import cargo capacity is exhausted for this visit."};const price=this.buyPrice(item),affordable=Math.floor(Math.max(0,state.company.cash)/price),qty=Math.min(requested,affordable,cargo);if(qty<=0)return{ok:false,reason:"Insufficient cash."};const cost=qty*price;this.inventory.store(state,item.type,item.resourceId,item.name,qty);const entry=this.inventory.ensureEntry(state,item.type,item.resourceId,item.name);state.company.cash-=cost;state.contract.localCosts=(state.contract.localCosts||0)+cost;state.trade.cargoUsed=(Number(state.trade.cargoUsed)||0)+qty;return{ok:true,qty,cost,entry,cargoRemaining:this.cargoRemaining(state)};}
}
