import { RESOURCE_TYPES } from "../data/resources.js";
import { clamp, hashString, seededRandom, tileKey } from "../core/utils.js";

export class WorldService {
  constructor(resourceService,contractService){this.resources=resourceService;this.contracts=contractService;}
  seed(state,x,y){return hashString(`${state.seed}|${state.contract.uid}|${x}|${y}`);}
  get(state,x,y){const key=tileKey(x,y);return state.tiles[key]||=( {x,y,revealed:false,developed:false,level:0,depleted:false} );}
  familyWeights(state){const a=this.contracts.archetype(state.contract);return{...a.weights,a};}
  familyFor(state,random){const {food,build,fuel,ore}=this.familyWeights(state),total=food+build+fuel+ore,roll=random()*total;if(roll<food)return"food";if(roll<food+build)return"build";if(roll<food+build+fuel)return"fuel";return"ore";}
  renewableAbundance(random){const roll=random();if(roll<.52)return{label:"Limited",factor:.45+random()*.45};if(roll<.82)return{label:"Established",factor:.90+random()*.55};if(roll<.96)return{label:"Large",factor:1.45+random()*.85};return{label:"Vast",factor:2.30+random()*2.20};}
  finiteDeposit(random,reserveBias=1,type="ore"){const roll=random();let label,years;if(roll<.16){label="Small";years=1.5+random()*5.5;}else if(roll<.52){label="Modest";years=7+random()*20;}else if(roll<.80){label="Large";years=27+random()*55;}else if(roll<.95){label="Huge";years=82+random()*120;}else{label="Colossal";years=202+random()*350;}years*=reserveBias*(type==="ore"?.92:1);return{label,years:Math.max(.5,years)};}
  reveal(state,x,y){const tile=this.get(state,x,y);if(tile.revealed)return tile;const random=seededRandom(this.seed(state,x,y)),{a}=this.familyWeights(state),type=this.familyFor(state,random),def=this.resources.pick(RESOURCE_TYPES[type],random);let quality=this.resources.quality(random,def.qualityBias,a.rare);quality=clamp(Math.round(quality),1,10000);const shared={revealed:true,type,family:type,resourceId:def.id,name:def.name,resourceRarity:def.rarity,resourceMult:def.multiplier,quality,requiredMiningLevel:def.miningLevel,requiredMiningTech:def.unlock};if(def.renewable){const abundance=this.renewableAbundance(random);Object.assign(tile,shared,{sustainability:"renewable",abundance:abundance.factor,abundanceLabel:abundance.label,reserve:null,initialReserve:null,depleted:false});return tile;}const deposit=this.finiteDeposit(random,a.res,type),baseline=this.resources.baseOutput(quality)*(def.multiplier||1),reserve=Math.max(1,Math.round(baseline*360*deposit.years));Object.assign(tile,shared,{sustainability:"finite",abundance:1,depositScale:deposit.label,reserve,initialReserve:reserve});return tile;}
  hint(state,x,y){const level=state.metrics.hint||0;if(level<=0)return"Unknown";const random=seededRandom(this.seed(state,x,y)),type=this.familyFor(state,random),label=this.resources.categoryName(type);if(level===1)return`Possible ${label.toLowerCase()} signal`;if(level===2)return`${label} • ${["Low","Moderate","Good","High","Rare"][Math.floor(random()*5)]} signal`;return`${label} • quality band detected`;}
}
